const wordCategoriesES = [
    { category: 'Frutas', words: ['BANANA', 'MANZANA', 'NARANJA', 'PIÑA', 'FRESA', 'UVA', 'MANGO', 'SANDÍA', 'PERA', 'PAPAYA', 'COCO', 'LIMÓN', 'CEREZA', 'MORA', 'MARACUYÁ', 'DURAZNO', 'AGUACATE', 'MELÓN', 'KIWI', 'FRAMBUESA', 'ARÁNDANO', 'CIRUELA', 'MANDARINA', 'HIGO', 'DAMASCO', 'NECTARINA', 'LIMA', 'TORONJA', 'GRANADA'],
      similar: { 'BANANA': ['MANZANA', 'PERA'], 'MANZANA': ['PERA', 'DURAZNO'], 'NARANJA': ['MANDARINA', 'LIMÓN'], 'FRESA': ['FRAMBUESA', 'MORA'] }
    },
    { category: 'Animales', words: ['PERRO', 'GATO', 'CABALLO', 'VACA', 'CERDO', 'GALLINA', 'PATO', 'CONEJO', 'LEÓN', 'TIGRE', 'OSO', 'MONO', 'ELEFANTE', 'JIRAFA', 'CEBRA', 'SERPIENTE', 'TORTUGA', 'RANA', 'PEZ', 'TIBURÓN', 'BALLENA', 'DELFÍN', 'PINGÜINO', 'ÁGUILA', 'BÚHO', 'LORO', 'MARIPOSA', 'ABEJA', 'HORMIGA', 'LOBO', 'ZORRO', 'VENADO', 'GORILA', 'CAMELLO', 'PANDA', 'RATÓN', 'HÁMSTER', 'OVEJA', 'CABRA', 'BURRO', 'PAVO'],
      similar: { 'PERRO': ['GATO', 'LOBO'], 'GATO': ['PERRO', 'CONEJO'], 'LEÓN': ['TIGRE', 'LEOPARDO'], 'CABALLO': ['BURRO', 'CEBRA'] }
    },
    { category: 'Comidas', words: ['PIZZA', 'HAMBURGUESA', 'PERRO CALIENTE', 'PAPAS FRITAS', 'PASTA', 'ARROZ', 'FRIJOLES', 'BISTEC', 'POLLO', 'ENSALADA', 'SOPA', 'PAN', 'TOSTADA', 'SÁNDWICH', 'PANQUEQUE', 'TORTILLA', 'HUEVO FRITO', 'TOCINO', 'SALCHICHA', 'JAMÓN', 'QUESO', 'SUSHI', 'TACO', 'BURRITO', 'NACHOS', 'RISOTTO', 'PASTEL', 'LASAÑA', 'FIDEOS', 'CURRY', 'EMPANADA', 'AREPA', 'CEVICHE'],
      similar: { 'PIZZA': ['EMPANADA', 'PASTEL'], 'HAMBURGUESA': ['SÁNDWICH', 'PERRO CALIENTE'], 'ARROZ': ['FRIJOLES', 'PASTA'], 'POLLO': ['BISTEC', 'PESCADO'] }
    },
    { category: 'Postres', words: ['CHOCOLATE', 'HELADO', 'PASTEL', 'TORTA', 'GALLETA', 'BROWNIE', 'CUPCAKE', 'DONA', 'PUDÍN', 'GELATINA', 'CARAMELO', 'PALETA', 'DULCE', 'CHEESECAKE', 'MOUSSE', 'WAFFLE', 'CREPA', 'MALTEADA', 'ALGODÓN DE AZÚCAR', 'FLAN', 'CHURROS', 'TRES LECHES', 'ALFAJOR'],
      similar: { 'PASTEL': ['TORTA', 'CUPCAKE'], 'HELADO': ['MALTEADA', 'PALETA'], 'GALLETA': ['BROWNIE', 'MUFFIN'], 'CHOCOLATE': ['BROWNIE', 'TRUFA'] }
    },
    { category: 'Bebidas', words: ['AGUA', 'CAFÉ', 'TÉ', 'LECHE', 'JUGO', 'REFRESCO', 'CERVEZA', 'VINO', 'CHAMPÁN', 'WHISKY', 'VODKA', 'CÓCTEL', 'BATIDO', 'MALTEADA', 'LIMONADA', 'CHOCOLATE CALIENTE', 'CAPUCHINO', 'ESPRESSO', 'BEBIDA ENERGÉTICA', 'TÉ HELADO', 'COCA-COLA', 'SPRITE', 'FANTA', 'HORCHATA', 'SANGRÍA'],
      similar: { 'CAFÉ': ['TÉ', 'CAPUCHINO'], 'REFRESCO': ['JUGO', 'LIMONADA'], 'CERVEZA': ['VINO', 'CHAMPÁN'], 'AGUA': ['TÉ', 'JUGO'] }
    },
    { category: 'Deportes', words: ['FÚTBOL', 'BALONCESTO', 'VOLEIBOL', 'TENIS', 'NATACIÓN', 'CORRER', 'CICLISMO', 'PATINETA', 'SURF', 'BOXEO', 'LUCHA', 'GIMNASIA', 'BAILE', 'BALLET', 'PATINAJE', 'GOLF', 'BÉISBOL', 'BILLAR', 'BOLICHE', 'PING PONG', 'ESCALADA', 'PESCA', 'EQUITACIÓN', 'REMO', 'BUCEO', 'ESQUÍ', 'YOGA', 'PESAS', 'KARATE', 'JUDO'],
      similar: { 'FÚTBOL': ['BALONCESTO', 'VOLEIBOL'], 'NATACIÓN': ['BUCEO', 'SURF'], 'CORRER': ['CICLISMO', 'CAMINAR'], 'TENIS': ['PING PONG', 'BÁDMINTON'] }
    },
    { category: 'Instrumentos', words: ['GUITARRA', 'PIANO', 'BATERÍA', 'VIOLÍN', 'FLAUTA', 'SAXOFÓN', 'TROMPETA', 'ARMÓNICA', 'ACORDEÓN', 'ARPA', 'CHELO', 'BAJO', 'TECLADO', 'UKELELE', 'BANJO', 'CLARINETE', 'TROMBÓN', 'PANDERETA', 'TRIÁNGULO', 'XILÓFONO', 'ÓRGANO', 'MANDOLINA', 'MARACAS', 'BONGÓ'],
      similar: { 'GUITARRA': ['BAJO', 'UKELELE'], 'PIANO': ['TECLADO', 'ÓRGANO'], 'FLAUTA': ['CLARINETE', 'SAXOFÓN'], 'BATERÍA': ['PANDERETA', 'BONGÓ'] }
    },
    { category: 'Profesiones', words: ['MÉDICO', 'ENFERMERO', 'DENTISTA', 'VETERINARIO', 'PROFESOR', 'ABOGADO', 'INGENIERO', 'ARQUITECTO', 'POLICÍA', 'BOMBERO', 'PILOTO', 'CONDUCTOR', 'MESERO', 'COCINERO', 'CHEF', 'PANADERO', 'PESCADOR', 'ALBAÑIL', 'PINTOR', 'ELECTRICISTA', 'MECÁNICO', 'BARBERO', 'PELUQUERO', 'FOTÓGRAFO', 'PERIODISTA', 'ACTOR', 'CANTANTE', 'MÚSICO', 'ATLETA', 'JUGADOR', 'VENDEDOR', 'CARTERO'],
      similar: { 'MÉDICO': ['ENFERMERO', 'DENTISTA'], 'PROFESOR': ['MAESTRO', 'TUTOR'], 'POLICÍA': ['BOMBERO', 'SOLDADO'], 'COCINERO': ['CHEF', 'PANADERO'] }
    },
    { category: 'Transporte', words: ['CARRO', 'MOTO', 'BICICLETA', 'AUTOBÚS', 'CAMIÓN', 'CAMIONETA', 'TAXI', 'TREN', 'METRO', 'AVIÓN', 'HELICÓPTERO', 'BARCO', 'LANCHA', 'CANOA', 'MOTO ACUÁTICA', 'SUBMARINO', 'COHETE', 'PATINETA', 'SCOOTER', 'TRACTOR', 'AMBULANCIA', 'TELEFÉRICO'],
      similar: { 'CARRO': ['MOTO', 'TAXI'], 'AUTOBÚS': ['CAMIONETA', 'METRO'], 'AVIÓN': ['HELICÓPTERO', 'COHETE'], 'BARCO': ['LANCHA', 'CANOA'] }
    },
    { category: 'Casa', words: ['SOFÁ', 'CAMA', 'MESA', 'SILLA', 'ARMARIO', 'ESTANTE', 'TELEVISOR', 'COMPUTADORA', 'TELÉFONO', 'REFRIGERADOR', 'ESTUFA', 'MICROONDAS', 'LICUADORA', 'VENTILADOR', 'AIRE ACONDICIONADO', 'LÁMPARA', 'ESPEJO', 'RELOJ', 'FLORERO', 'ALFOMBRA', 'CORTINA', 'ALMOHADA', 'COBIJA', 'TOALLA', 'JABÓN', 'SARTÉN', 'PLATO', 'VASO', 'TENEDOR', 'CUCHILLO', 'CUCHARA'],
      similar: { 'SOFÁ': ['SILLA', 'CAMA'], 'MESA': ['ESCRITORIO', 'MOSTRADOR'], 'TELEVISOR': ['COMPUTADORA', 'TELÉFONO'], 'REFRIGERADOR': ['CONGELADOR', 'MICROONDAS'] }
    },
    { category: 'Ropa', words: ['CAMISETA', 'CAMISA', 'BLUSA', 'SUÉTER', 'CHAQUETA', 'ABRIGO', 'PANTALÓN', 'BERMUDA', 'FALDA', 'VESTIDO', 'PIJAMA', 'ROPA INTERIOR', 'CALCETINES', 'TENIS', 'ZAPATOS', 'SANDALIAS', 'CHANCLAS', 'BOTAS', 'CINTURÓN', 'GORRA', 'SOMBRERO', 'BUFANDA', 'GUANTES', 'LENTES', 'BOLSA', 'MOCHILA', 'RELOJ', 'PULSERA', 'COLLAR', 'ARETES', 'ANILLO', 'BIKINI', 'TRAJE DE BAÑO'],
      similar: { 'CAMISETA': ['CAMISA', 'BLUSA'], 'PANTALÓN': ['BERMUDA', 'JEANS'], 'TENIS': ['ZAPATOS', 'BOTAS'], 'CHAQUETA': ['ABRIGO', 'SUÉTER'] }
    },
    { category: 'Lugares', words: ['CASA', 'APARTAMENTO', 'ESCUELA', 'HOSPITAL', 'IGLESIA', 'CENTRO COMERCIAL', 'SUPERMERCADO', 'PANADERÍA', 'FARMACIA', 'BANCO', 'RESTAURANTE', 'CAFETERÍA', 'BAR', 'CINE', 'TEATRO', 'MUSEO', 'BIBLIOTECA', 'PARQUE', 'PLAYA', 'PISCINA', 'GIMNASIO', 'ESTADIO', 'HOTEL', 'AEROPUERTO', 'ESTACIÓN', 'TIENDA', 'SALÓN', 'TALLER'],
      similar: { 'CASA': ['APARTAMENTO', 'EDIFICIO'], 'ESCUELA': ['UNIVERSIDAD', 'BIBLIOTECA'], 'RESTAURANTE': ['CAFETERÍA', 'BAR'], 'CENTRO COMERCIAL': ['TIENDA', 'SUPERMERCADO'] }
    },
    { category: 'Naturaleza', words: ['SOL', 'LUNA', 'ESTRELLA', 'CIELO', 'NUBE', 'LLUVIA', 'TRUENO', 'RAYO', 'ARCOÍRIS', 'VIENTO', 'NIEVE', 'HIELO', 'RÍO', 'MAR', 'OCÉANO', 'LAGO', 'CASCADA', 'OLA', 'PLAYA', 'ARENA', 'MONTAÑA', 'CERRO', 'VALLE', 'DESIERTO', 'BOSQUE', 'ÁRBOL', 'PLANTA', 'FLOR', 'HOJA', 'CÉSPED', 'PIEDRA', 'VOLCÁN', 'CUEVA'],
      similar: { 'SOL': ['LUNA', 'ESTRELLA'], 'LLUVIA': ['NIEVE', 'TORMENTA'], 'RÍO': ['LAGO', 'MAR'], 'MONTAÑA': ['CERRO', 'VOLCÁN'] }
    },
    { category: 'Flores', words: ['ROSA', 'MARGARITA', 'GIRASOL', 'TULIPÁN', 'LIRIO', 'VIOLETA', 'ORQUÍDEA', 'CLAVEL', 'JAZMÍN', 'LAVANDA', 'HORTENSIA', 'HIBISCO', 'DALIA', 'CRISANTEMO', 'CAMELIA', 'MAGNOLIA', 'AMAPOLA', 'NARCISO', 'PETUNIA', 'GARDENIA'],
      similar: { 'ROSA': ['CLAVEL', 'TULIPÁN'], 'GIRASOL': ['MARGARITA', 'DALIA'], 'ORQUÍDEA': ['LIRIO', 'TULIPÁN'] }
    },
    { category: 'Colores', words: ['ROJO', 'AZUL', 'AMARILLO', 'VERDE', 'NARANJA', 'MORADO', 'ROSA', 'MARRÓN', 'NEGRO', 'BLANCO', 'GRIS', 'BEIGE', 'DORADO', 'PLATEADO', 'VINO', 'LILA', 'VIOLETA', 'TURQUESA', 'CORAL', 'SALMÓN', 'MOSTAZA', 'CREMA', 'CARAMELO', 'BRONCE'],
      similar: { 'ROJO': ['NARANJA', 'ROSA'], 'AZUL': ['MORADO', 'TURQUESA'], 'VERDE': ['AMARILLO', 'AZUL'], 'ROSA': ['ROJO', 'MORADO'] }
    },
    { category: 'Cuerpo', words: ['CABEZA', 'CABELLO', 'CARA', 'OJO', 'NARIZ', 'BOCA', 'OREJA', 'DIENTE', 'LENGUA', 'CUELLO', 'HOMBRO', 'BRAZO', 'CODO', 'MANO', 'DEDO', 'UÑA', 'PECHO', 'BARRIGA', 'ESPALDA', 'PIERNA', 'RODILLA', 'PIE', 'TALÓN', 'CORAZÓN', 'PULMÓN', 'CEREBRO'],
      similar: { 'OJO': ['NARIZ', 'BOCA'], 'MANO': ['PIE', 'BRAZO'], 'PIERNA': ['BRAZO', 'PIE'], 'CABEZA': ['CARA', 'CABELLO'] }
    },
    { category: 'Escuela', words: ['LÁPIZ', 'BOLÍGRAFO', 'BORRADOR', 'SACAPUNTAS', 'REGLA', 'CUADERNO', 'LIBRO', 'REVISTA', 'CARPETA', 'MOCHILA', 'ESTUCHE', 'TIJERAS', 'PEGAMENTO', 'CINTA', 'GRAPADORA', 'PAPEL', 'PIZARRA', 'TIZA', 'ESCRITORIO', 'COMPUTADORA', 'CALCULADORA', 'MAPA', 'GLOBO', 'EXAMEN', 'NOTA', 'DIPLOMA'],
      similar: { 'LÁPIZ': ['BOLÍGRAFO', 'TIZA'], 'CUADERNO': ['LIBRO', 'REVISTA'], 'MOCHILA': ['CARPETA', 'BOLSA'], 'BORRADOR': ['SACAPUNTAS', 'CORRECTOR'] }
    },
    { category: 'Juguetes', words: ['PELOTA', 'MUÑECA', 'CARRITO', 'COMETA', 'YOYO', 'TROMPO', 'BICICLETA', 'PATINETA', 'PATINES', 'LEGO', 'ROMPECABEZAS', 'DOMINÓ', 'AJEDREZ', 'CARTAS', 'DADO', 'VIDEOJUEGO', 'MUÑECO', 'PELUCHE', 'OSITO', 'ROBOT', 'AVIÓN', 'PLASTILINA', 'SLIME', 'BURBUJAS', 'GLOBO', 'COLUMPIO', 'RESBALADILLA', 'CUERDA', 'DISFRAZ', 'MÁSCARA'],
      similar: { 'PELOTA': ['FRISBEE', 'GLOBO'], 'MUÑECA': ['MUÑECO', 'PELUCHE'], 'CARRITO': ['AVIÓN', 'BARCO'], 'VIDEOJUEGO': ['COMPUTADORA', 'TABLET'] }
    },
    { category: 'Tecnología', words: ['WHATSAPP', 'INSTAGRAM', 'FACEBOOK', 'TWITTER', 'TIKTOK', 'YOUTUBE', 'NETFLIX', 'SPOTIFY', 'GOOGLE', 'AMAZON', 'UBER', 'AIRBNB', 'LINKEDIN', 'TELEGRAM', 'DISCORD', 'ZOOM', 'TINDER', 'GMAIL', 'WORD', 'EXCEL', 'PHOTOSHOP', 'WINDOWS', 'ANDROID', 'IPHONE'],
      similar: { 'WHATSAPP': ['TELEGRAM', 'MESSENGER'], 'INSTAGRAM': ['TIKTOK', 'FACEBOOK'], 'NETFLIX': ['YOUTUBE', 'PRIME VIDEO'], 'GOOGLE': ['BING', 'YAHOO'] }
    },
    { category: 'Videojuegos', words: ['MINECRAFT', 'FORTNITE', 'FREE FIRE', 'AMONG US', 'ROBLOX', 'FIFA', 'GTA', 'MARIO', 'SONIC', 'ZELDA', 'POKEMON', 'PACMAN', 'TETRIS', 'CANDY CRUSH', 'LEAGUE OF LEGENDS', 'VALORANT', 'COUNTER STRIKE', 'CALL OF DUTY', 'GOD OF WAR', 'LOS SIMS', 'NEED FOR SPEED', 'ROCKET LEAGUE', 'FALL GUYS'],
      similar: { 'FORTNITE': ['FREE FIRE', 'PUBG'], 'MARIO': ['SONIC', 'DONKEY KONG'], 'FIFA': ['PES', 'FÚTBOL'], 'MINECRAFT': ['ROBLOX', 'TERRARIA'] }
    },
    { category: 'Películas', words: ['TITANIC', 'AVATAR', 'MATRIX', 'STAR WARS', 'HARRY POTTER', 'VENGADORES', 'HOMBRE ARAÑA', 'BATMAN', 'SUPERMAN', 'TOY STORY', 'SHREK', 'FROZEN', 'REY LEÓN', 'BUSCANDO A NEMO', 'MOANA', 'MINIONS', 'CARS', 'FRIENDS', 'GAME OF THRONES', 'STRANGER THINGS', 'LA CASA DE PAPEL', 'BREAKING BAD', 'THE OFFICE', 'EL JUEGO DEL CALAMAR'],
      similar: { 'BATMAN': ['SUPERMAN', 'HOMBRE ARAÑA'], 'FROZEN': ['MOANA', 'ENREDADOS'], 'TOY STORY': ['CARS', 'MINIONS'], 'VENGADORES': ['LIGA DE LA JUSTICIA', 'X-MEN'] }
    },
    { category: 'Superhéroes', words: ['SUPERMAN', 'BATMAN', 'HOMBRE ARAÑA', 'HULK', 'THOR', 'CAPITÁN AMÉRICA', 'IRON MAN', 'MUJER MARAVILLA', 'FLASH', 'AQUAMAN', 'WOLVERINE', 'DEADPOOL', 'PANTERA NEGRA', 'THANOS', 'GUASÓN', 'LOKI', 'VENOM'],
      similar: { 'SUPERMAN': ['BATMAN', 'FLASH'], 'HOMBRE ARAÑA': ['VENOM', 'DEADPOOL'], 'THOR': ['HULK', 'CAPITÁN AMÉRICA'], 'BATMAN': ['GUASÓN', 'ROBIN'] }
    },
    { category: 'Caricaturas', words: ['MICKEY', 'MINNIE', 'PATO DONALD', 'BOB ESPONJA', 'PATRICIO', 'TOM', 'JERRY', 'BUGS BUNNY', 'SCOOBY DOO', 'GARFIELD', 'SNOOPY', 'BART SIMPSON', 'HOMERO SIMPSON', 'FINN', 'JAKE', 'BEN 10', 'NARUTO', 'GOKU', 'PIKACHU', 'PEPPA PIG', 'PATRULLA CANINA', 'ELSA', 'ANNA', 'RAPUNZEL'],
      similar: { 'MICKEY': ['MINNIE', 'PATO DONALD'], 'TOM': ['JERRY', 'BUGS BUNNY'], 'GOKU': ['NARUTO', 'LUFFY'], 'ELSA': ['ANNA', 'RAPUNZEL'] }
    },
    { category: 'Marcas', words: ['NIKE', 'ADIDAS', 'PUMA', 'APPLE', 'SAMSUNG', 'COCA-COLA', 'PEPSI', 'MCDONALDS', 'BURGER KING', 'STARBUCKS', 'NESTLE', 'COLGATE', 'GILLETTE', 'NIVEA', 'DOVE'],
      similar: { 'NIKE': ['ADIDAS', 'PUMA'], 'COCA-COLA': ['PEPSI', 'FANTA'], 'MCDONALDS': ['BURGER KING', 'KFC'], 'APPLE': ['SAMSUNG', 'GOOGLE'] }
    },
    { category: 'Música', words: ['ROCK', 'POP', 'REGGAETÓN', 'RAP', 'HIP HOP', 'SALSA', 'BACHATA', 'MERENGUE', 'CUMBIA', 'REGGAE', 'ELECTRÓNICA', 'JAZZ', 'BLUES', 'COUNTRY', 'METAL', 'PUNK', 'ROMÁNTICA', 'K-POP', 'CLÁSICA', 'MARIACHI', 'RANCHERA', 'BANDA'],
      similar: { 'ROCK': ['METAL', 'PUNK'], 'SALSA': ['BACHATA', 'MERENGUE'], 'RAP': ['HIP HOP', 'TRAP'], 'CUMBIA': ['REGGAETÓN', 'SALSA'] }
    },
    { category: 'Fiestas', words: ['NAVIDAD', 'AÑO NUEVO', 'PASCUA', 'HALLOWEEN', 'DÍA DE MUERTOS', 'SAN VALENTÍN', 'DÍA DE LA MADRE', 'DÍA DEL PADRE', 'CUMPLEAÑOS', 'BODA', 'GRADUACIÓN', 'BAUTIZO', 'QUINCEAÑERA', 'FIESTA', 'PARRILLADA', 'PICNIC', 'CONCIERTO', 'FESTIVAL', 'CARNAVAL'],
      similar: { 'NAVIDAD': ['AÑO NUEVO', 'PASCUA'], 'HALLOWEEN': ['DÍA DE MUERTOS', 'CARNAVAL'], 'CUMPLEAÑOS': ['BODA', 'GRADUACIÓN'], 'PARRILLADA': ['PICNIC', 'FIESTA'] }
    },
    { category: 'Fantasía', words: ['DRAGÓN', 'UNICORNIO', 'HADA', 'SIRENA', 'BRUJA', 'MAGO', 'VAMPIRO', 'HOMBRE LOBO', 'ZOMBI', 'FANTASMA', 'MOMIA', 'ESQUELETO', 'GIGANTE', 'ENANO', 'DEMONIO', 'ÁNGEL', 'CUPIDO', 'ELFO', 'DUENDE', 'TROL', 'FÉNIX'],
      similar: { 'VAMPIRO': ['HOMBRE LOBO', 'ZOMBI'], 'HADA': ['ÁNGEL', 'SIRENA'], 'BRUJA': ['MAGO', 'HECHICERO'], 'DRAGÓN': ['UNICORNIO', 'FÉNIX'] }
    },
    { category: 'Sentimientos', words: ['ALEGRÍA', 'TRISTEZA', 'ENOJO', 'MIEDO', 'AMOR', 'ODIO', 'PAZ', 'FELICIDAD', 'NOSTALGIA', 'ESPERANZA', 'ORGULLO', 'VERGÜENZA', 'CELOS', 'SOLEDAD', 'PEREZA', 'HAMBRE', 'SUEÑO', 'CANSANCIO', 'DOLOR', 'PLACER', 'SORPRESA', 'PASIÓN', 'VALENTÍA'],
      similar: { 'ALEGRÍA': ['FELICIDAD', 'PLACER'], 'TRISTEZA': ['NOSTALGIA', 'SOLEDAD'], 'ENOJO': ['ODIO', 'FRUSTRACIÓN'], 'AMOR': ['PASIÓN', 'CARIÑO'] }
    },
    { category: 'Clima', words: ['VERANO', 'INVIERNO', 'PRIMAVERA', 'OTOÑO', 'CALOR', 'FRÍO', 'LLUVIA', 'SOL', 'NUBE', 'VIENTO', 'TORMENTA', 'TRUENO', 'RAYO', 'NIEVE', 'NIEBLA', 'HELADA', 'SEQUÍA', 'INUNDACIÓN', 'TORNADO', 'HURACÁN'],
      similar: { 'VERANO': ['PRIMAVERA', 'CALOR'], 'INVIERNO': ['OTOÑO', 'FRÍO'], 'LLUVIA': ['TORMENTA', 'NIEVE'], 'SOL': ['CALOR', 'VERANO'] }
    }
];
