const wordCategoriesPT = [
    { category: 'Frutas', words: ['BANANA', 'MAÇÃ', 'LARANJA', 'ABACAXI', 'MORANGO', 'UVA', 'MANGA', 'MELANCIA', 'PERA', 'MAMÃO', 'LIMÃO', 'COCO', 'CEREJA', 'GOIABA', 'MARACUJÁ', 'ABACATE', 'MELÃO', 'KIWI', 'PÊSSEGO', 'TANGERINA', 'AMEIXA', 'AÇAÍ', 'JABUTICABA', 'FRAMBOESA', 'PITANGA', 'CARAMBOLA'],
      similar: { 'BANANA': ['MAÇÃ', 'PERA'], 'MAÇÃ': ['PERA', 'PÊSSEGO'], 'LARANJA': ['TANGERINA', 'LIMÃO'], 'MORANGO': ['FRAMBOESA', 'CEREJA'], 'MELANCIA': ['MELÃO', 'ABACAXI'], 'UVA': ['CEREJA', 'AMEIXA'] }
    },
    { category: 'Animais', words: ['CACHORRO', 'GATO', 'CAVALO', 'VACA', 'PORCO', 'GALINHA', 'PATO', 'COELHO', 'LEÃO', 'TIGRE', 'URSO', 'MACACO', 'ELEFANTE', 'GIRAFA', 'ZEBRA', 'COBRA', 'TARTARUGA', 'SAPO', 'PEIXE', 'TUBARÃO', 'BALEIA', 'GOLFINHO', 'PINGUIM', 'PAPAGAIO', 'CORUJA', 'ÁGUIA', 'BORBOLETA', 'ABELHA', 'FORMIGA', 'ARANHA', 'LOBO', 'RAPOSA', 'RATO', 'OVELHA', 'CABRA', 'BURRO', 'JACARÉ', 'FOCA', 'POLVO', 'CARANGUEJO'],
      similar: { 'CACHORRO': ['GATO', 'LOBO'], 'GATO': ['CACHORRO', 'COELHO'], 'LEÃO': ['TIGRE', 'LOBO'], 'CAVALO': ['BURRO', 'ZEBRA'], 'GALINHA': ['PATO', 'GALO'], 'PEIXE': ['TUBARÃO', 'GOLFINHO'], 'COBRA': ['JACARÉ', 'LAGARTO'] }
    },
    { category: 'Comidas', words: ['PIZZA', 'HAMBÚRGUER', 'BATATA FRITA', 'MACARRÃO', 'ARROZ', 'FEIJÃO', 'CHURRASCO', 'FRANGO', 'SALADA', 'SOPA', 'PASTEL', 'COXINHA', 'PÃO', 'SANDUÍCHE', 'OVO', 'BACON', 'QUEIJO', 'PRESUNTO', 'SALSICHA', 'BIFE', 'LASANHA', 'PANQUECA', 'TORTA', 'TAPIOCA', 'PIPOCA', 'SUSHI', 'NUGGETS', 'CACHORRO QUENTE', 'ESTROGONOFE', 'FEIJOADA', 'CARNE', 'PEIXE', 'CAMARÃO'],
      similar: { 'PIZZA': ['HAMBÚRGUER', 'PASTEL'], 'HAMBÚRGUER': ['SANDUÍCHE', 'CACHORRO QUENTE'], 'ARROZ': ['FEIJÃO', 'MACARRÃO'], 'FRANGO': ['BIFE', 'CARNE'], 'PÃO': ['TORTA', 'BOLO'] }
    },
    { category: 'Doces', words: ['CHOCOLATE', 'BRIGADEIRO', 'SORVETE', 'BOLO', 'PUDIM', 'PICOLÉ', 'BISCOITO', 'BOLACHA', 'BOMBOM', 'PIRULITO', 'CHICLETE', 'BALA', 'GELATINA', 'PAÇOCA', 'COOKIE', 'BROWNIE', 'DONUT', 'CHURROS', 'ALGODÃO DOCE', 'CUPCAKE', 'MOUSSE', 'PAVÊ', 'TORTA', 'BEIJINHO', 'COCADA', 'GOIABADA', 'MARIA MOLE', 'PÉ DE MOLEQUE'],
      similar: { 'BRIGADEIRO': ['BEIJINHO', 'BOMBOM'], 'SORVETE': ['PICOLÉ', 'MILK SHAKE'], 'BOLO': ['TORTA', 'PUDIM'], 'CHOCOLATE': ['BRIGADEIRO', 'BROWNIE'], 'BISCOITO': ['BOLACHA', 'COOKIE'] }
    },
    { category: 'Bebidas', words: ['ÁGUA', 'CAFÉ', 'CHÁ', 'LEITE', 'SUCO', 'REFRIGERANTE', 'CERVEJA', 'VINHO', 'CHOCOLATE QUENTE', 'LIMONADA', 'VITAMINA', 'MILKSHAKE', 'GUARANÁ', 'COCA-COLA', 'FANTA', 'SPRITE', 'ÁGUA DE COCO', 'MATE', 'ENERGÉTICO', 'CAPPUCCINO', 'IOGURTE', 'ACHOCOLATADO', 'CAIPIRINHA', 'BATIDA'],
      similar: { 'CAFÉ': ['CHÁ', 'CAPPUCCINO'], 'REFRIGERANTE': ['SUCO', 'GUARANÁ'], 'CERVEJA': ['VINHO', 'CAIPIRINHA'], 'ÁGUA': ['ÁGUA DE COCO', 'CHÁ'], 'LEITE': ['IOGURTE', 'ACHOCOLATADO'] }
    },
    { category: 'Esportes', words: ['FUTEBOL', 'BASQUETE', 'VÔLEI', 'TÊNIS', 'NATAÇÃO', 'CORRIDA', 'CICLISMO', 'SKATE', 'SURF', 'JUDÔ', 'BOXE', 'CAPOEIRA', 'GINÁSTICA', 'DANÇA', 'PATINAÇÃO', 'GOLFE', 'BOLICHE', 'SINUCA', 'PING PONG', 'CAMINHADA', 'ACADEMIA', 'YOGA', 'HANDEBOL', 'FUTSAL', 'KARATÊ', 'MUSCULAÇÃO', 'ESCALADA', 'PESCA'],
      similar: { 'FUTEBOL': ['FUTSAL', 'BASQUETE'], 'BASQUETE': ['VÔLEI', 'HANDEBOL'], 'NATAÇÃO': ['SURF', 'MERGULHO'], 'CORRIDA': ['CICLISMO', 'CAMINHADA'], 'BOXE': ['JUDÔ', 'KARATÊ'] }
    },
    { category: 'Instrumentos', words: ['VIOLÃO', 'GUITARRA', 'BATERIA', 'PIANO', 'TECLADO', 'FLAUTA', 'VIOLINO', 'PANDEIRO', 'TAMBOR', 'GAITA', 'TRIÂNGULO', 'SANFONA', 'SAXOFONE', 'TROMPETE', 'CAVAQUINHO', 'UKULELE', 'HARPA', 'SINO', 'CHOCALHO', 'BERIMBAU', 'ACORDEÃO', 'BAIXO'],
      similar: { 'VIOLÃO': ['GUITARRA', 'CAVAQUINHO'], 'PIANO': ['TECLADO', 'ÓRGÃO'], 'FLAUTA': ['GAITA', 'SAXOFONE'], 'BATERIA': ['TAMBOR', 'PANDEIRO'], 'SANFONA': ['ACORDEÃO', 'GAITA'] }
    },
    { category: 'Profissões', words: ['MÉDICO', 'PROFESSOR', 'POLICIAL', 'BOMBEIRO', 'DENTISTA', 'ENFERMEIRO', 'ADVOGADO', 'MOTORISTA', 'COZINHEIRO', 'PADEIRO', 'PEDREIRO', 'PINTOR', 'ELETRICISTA', 'MECÂNICO', 'CABELEIREIRO', 'GARÇOM', 'VETERINÁRIO', 'PILOTO', 'JOGADOR', 'CANTOR', 'ATOR', 'FOTÓGRAFO', 'CARTEIRO', 'VENDEDOR', 'PESCADOR', 'AGRICULTOR', 'JORNALISTA', 'SECRETÁRIA'],
      similar: { 'MÉDICO': ['ENFERMEIRO', 'DENTISTA'], 'PROFESSOR': ['DIRETOR', 'PEDAGOGO'], 'POLICIAL': ['BOMBEIRO', 'SOLDADO'], 'COZINHEIRO': ['PADEIRO', 'GARÇOM'] }
    },
    { category: 'Transportes', words: ['CARRO', 'MOTO', 'BICICLETA', 'ÔNIBUS', 'CAMINHÃO', 'TÁXI', 'TREM', 'METRÔ', 'AVIÃO', 'HELICÓPTERO', 'NAVIO', 'BARCO', 'FOGUETE', 'PATINETE', 'SKATE', 'AMBULÂNCIA', 'VAN', 'JIPE', 'TRICICLO', 'CANOA', 'LANCHA', 'JET SKI', 'BONDINHO', 'TRATOR'],
      similar: { 'CARRO': ['MOTO', 'TÁXI'], 'ÔNIBUS': ['VAN', 'METRÔ'], 'AVIÃO': ['HELICÓPTERO', 'FOGUETE'], 'BARCO': ['LANCHA', 'CANOA'], 'BICICLETA': ['MOTO', 'PATINETE'] }
    },
    { category: 'Casa', words: ['SOFÁ', 'CAMA', 'MESA', 'CADEIRA', 'ARMÁRIO', 'TELEVISÃO', 'GELADEIRA', 'FOGÃO', 'VENTILADOR', 'LÂMPADA', 'ESPELHO', 'QUADRO', 'RELÓGIO', 'TAPETE', 'CORTINA', 'TRAVESSEIRO', 'COBERTOR', 'TOALHA', 'PANELA', 'PRATO', 'COPO', 'TALHER', 'FACA', 'GARFO', 'COLHER', 'BANHEIRA', 'CHUVEIRO', 'PIA', 'VASO', 'PORTA', 'JANELA', 'ESCADA', 'TELHADO'],
      similar: { 'SOFÁ': ['CADEIRA', 'CAMA'], 'CAMA': ['SOFÁ', 'COLCHÃO'], 'TELEVISÃO': ['RÁDIO', 'COMPUTADOR'], 'GELADEIRA': ['FREEZER', 'FOGÃO'], 'PORTA': ['JANELA', 'PORTÃO'] }
    },
    { category: 'Roupas', words: ['CAMISETA', 'CALÇA', 'BERMUDA', 'VESTIDO', 'SAIA', 'CASACO', 'JAQUETA', 'MOLETOM', 'PIJAMA', 'MEIA', 'TÊNIS', 'SAPATO', 'SANDÁLIA', 'CHINELO', 'BOTA', 'BONÉ', 'CHAPÉU', 'CACHECOL', 'LUVA', 'ÓCULOS', 'BOLSA', 'MOCHILA', 'CINTO', 'GRAVATA', 'SUTIÃ', 'CUECA', 'CALCINHA', 'BIQUÍNI', 'SUNGA', 'BLUSA', 'CAMISA', 'SHORT'],
      similar: { 'CAMISETA': ['CAMISA', 'BLUSA'], 'CALÇA': ['BERMUDA', 'SHORT'], 'TÊNIS': ['SAPATO', 'SANDÁLIA'], 'CASACO': ['JAQUETA', 'MOLETOM'], 'BONÉ': ['CHAPÉU', 'TOUCA'] }
    },
    { category: 'Lugares', words: ['CASA', 'ESCOLA', 'HOSPITAL', 'IGREJA', 'SHOPPING', 'MERCADO', 'PADARIA', 'FARMÁCIA', 'BANCO', 'RESTAURANTE', 'CINEMA', 'PARQUE', 'PRAÇA', 'PRAIA', 'PISCINA', 'ACADEMIA', 'ESTÁDIO', 'HOTEL', 'AEROPORTO', 'FAZENDA', 'ZOOLÓGICO', 'MUSEU', 'BIBLIOTECA', 'TEATRO', 'LOJA', 'FEIRA', 'OFICINA', 'POSTO', 'DELEGACIA', 'PREFEITURA'],
      similar: { 'CASA': ['APARTAMENTO', 'PRÉDIO'], 'ESCOLA': ['FACULDADE', 'CRECHE'], 'RESTAURANTE': ['LANCHONETE', 'BAR'], 'SHOPPING': ['LOJA', 'MERCADO'], 'PARQUE': ['PRAÇA', 'JARDIM'] }
    },
    { category: 'Natureza', words: ['SOL', 'LUA', 'ESTRELA', 'CÉU', 'NUVEM', 'CHUVA', 'ARCO-ÍRIS', 'VENTO', 'NEVE', 'RIO', 'MAR', 'LAGO', 'CACHOEIRA', 'PRAIA', 'MONTANHA', 'FLORESTA', 'ÁRVORE', 'FLOR', 'GRAMA', 'TERRA', 'PEDRA', 'AREIA', 'VULCÃO', 'CAVERNA', 'DESERTO', 'ILHA', 'ONDA', 'TROVÃO', 'RAIO', 'RELÂMPAGO', 'FOGO', 'GELO'],
      similar: { 'SOL': ['LUA', 'ESTRELA'], 'CHUVA': ['NEVE', 'GRANIZO'], 'RIO': ['LAGO', 'MAR'], 'MONTANHA': ['MORRO', 'VULCÃO'], 'ÁRVORE': ['PLANTA', 'FLOR'] }
    },
    { category: 'Cores', words: ['VERMELHO', 'AZUL', 'AMARELO', 'VERDE', 'LARANJA', 'ROXO', 'ROSA', 'MARROM', 'PRETO', 'BRANCO', 'CINZA', 'DOURADO', 'PRATEADO', 'BEGE', 'LILÁS', 'TURQUESA', 'VIOLETA', 'VINHO', 'CREME', 'BRONZE'],
      similar: { 'VERMELHO': ['LARANJA', 'ROSA'], 'AZUL': ['ROXO', 'TURQUESA'], 'VERDE': ['AMARELO', 'AZUL'], 'ROSA': ['VERMELHO', 'LILÁS'], 'PRETO': ['CINZA', 'MARROM'] }
    },
    { category: 'Corpo', words: ['CABEÇA', 'CABELO', 'OLHO', 'NARIZ', 'BOCA', 'ORELHA', 'DENTE', 'LÍNGUA', 'PESCOÇO', 'OMBRO', 'BRAÇO', 'MÃO', 'DEDO', 'UNHA', 'BARRIGA', 'COSTAS', 'PERNA', 'JOELHO', 'PÉ', 'CORAÇÃO', 'PULMÃO', 'CÉREBRO', 'OSSO', 'SANGUE', 'PELE', 'SOBRANCELHA', 'CÍLIO', 'BIGODE', 'BARBA'],
      similar: { 'OLHO': ['NARIZ', 'BOCA'], 'MÃO': ['PÉ', 'DEDO'], 'PERNA': ['BRAÇO', 'PÉ'], 'CABEÇA': ['ROSTO', 'CABELO'], 'DENTE': ['LÍNGUA', 'BOCA'] }
    },
    { category: 'Escola', words: ['LÁPIS', 'CANETA', 'BORRACHA', 'CADERNO', 'LIVRO', 'MOCHILA', 'ESTOJO', 'TESOURA', 'COLA', 'RÉGUA', 'LOUSA', 'GIZ', 'CARTEIRA', 'GLOBO', 'MAPA', 'PROVA', 'DEVER', 'RECREIO', 'AULA', 'NOTA', 'DIPLOMA', 'UNIFORME', 'LANCHEIRA', 'APONTADOR', 'PAPEL', 'PASTA'],
      similar: { 'LÁPIS': ['CANETA', 'GIZ'], 'CADERNO': ['LIVRO', 'PASTA'], 'MOCHILA': ['BOLSA', 'LANCHEIRA'], 'BORRACHA': ['APONTADOR', 'COLA'] }
    },
    { category: 'Brinquedos', words: ['BOLA', 'BONECA', 'CARRINHO', 'PIPA', 'IOIÔ', 'PIÃO', 'LEGO', 'QUEBRA-CABEÇA', 'DOMINÓ', 'BARALHO', 'DADO', 'VIDEOGAME', 'PELÚCIA', 'ROBÔ', 'MASSINHA', 'BOLHA', 'BALÃO', 'GANGORRA', 'BALANÇO', 'ESCORREGADOR', 'CORDA', 'FANTASIA', 'MÁSCARA', 'PATINS', 'PETECA', 'BAMBOLÊ', 'BOLICHE', 'PEÃO'],
      similar: { 'BOLA': ['PETECA', 'BAMBOLÊ'], 'BONECA': ['PELÚCIA', 'ROBÔ'], 'CARRINHO': ['AVIÃO', 'TRENZINHO'], 'VIDEOGAME': ['COMPUTADOR', 'TABLET'], 'BALANÇO': ['GANGORRA', 'ESCORREGADOR'] }
    },
    { category: 'Ferramentas', words: ['MARTELO', 'CHAVE DE FENDA', 'ALICATE', 'SERROTE', 'FURADEIRA', 'PREGO', 'PARAFUSO', 'ESCADA', 'PÁ', 'ENXADA', 'VASSOURA', 'RODO', 'BALDE', 'MANGUEIRA', 'TESOURA', 'PINCEL', 'ROLO', 'FITA', 'CORDA', 'TRENA', 'MACHADO', 'PICARETA', 'CARRINHO DE MÃO'],
      similar: { 'MARTELO': ['MACHADO', 'PICARETA'], 'VASSOURA': ['RODO', 'PÁ'], 'PINCEL': ['ROLO', 'BROCHA'], 'BALDE': ['REGADOR', 'LATA'], 'PREGO': ['PARAFUSO', 'PORCA'] }
    },
    { category: 'Tecnologia', words: ['CELULAR', 'COMPUTADOR', 'TABLET', 'TELEVISÃO', 'RÁDIO', 'FONE DE OUVIDO', 'CÂMERA', 'CONTROLE', 'MOUSE', 'TECLADO', 'CARREGADOR', 'TOMADA', 'PILHA', 'LANTERNA', 'RELÓGIO', 'CALCULADORA', 'MICROFONE', 'CAIXA DE SOM', 'PENDRIVE', 'IMPRESSORA', 'NOTEBOOK', 'VIDEO GAME', 'DRONE', 'ROBÔ'],
      similar: { 'CELULAR': ['TABLET', 'TELEFONE'], 'COMPUTADOR': ['NOTEBOOK', 'TABLET'], 'TELEVISÃO': ['RÁDIO', 'MONITOR'], 'FONE DE OUVIDO': ['CAIXA DE SOM', 'MICROFONE'] }
    },
    { category: 'Jogos Famosos', words: ['MINECRAFT', 'FORTNITE', 'MARIO', 'SONIC', 'POKEMON', 'TETRIS', 'PACMAN', 'FIFA', 'AMONG US', 'ROBLOX', 'CANDY CRUSH', 'ANGRY BIRDS', 'TEMPLE RUN', 'SUBWAY SURFERS', 'CLASH ROYALE', 'FREE FIRE', 'GTA', 'ZELDA', 'CALL OF DUTY', 'THE SIMS'],
      similar: { 'FORTNITE': ['FREE FIRE', 'PUBG'], 'MARIO': ['SONIC', 'DONKEY KONG'], 'FIFA': ['PES', 'FUTEBOL'], 'MINECRAFT': ['ROBLOX', 'TERRARIA'], 'POKEMON': ['DIGIMON', 'ZELDA'] }
    },
    { category: 'Filmes e Séries', words: ['REI LEÃO', 'FROZEN', 'TOY STORY', 'SHREK', 'CARROS', 'PROCURANDO NEMO', 'MOANA', 'ENCANTO', 'MINIONS', 'MADAGASCAR', 'KUNG FU PANDA', 'A ERA DO GELO', 'HARRY POTTER', 'HOMEM ARANHA', 'BATMAN', 'VINGADORES', 'AVATAR', 'TITANIC', 'STAR WARS', 'JURASSIC PARK'],
      similar: { 'FROZEN': ['MOANA', 'ENCANTO'], 'TOY STORY': ['CARROS', 'MINIONS'], 'REI LEÃO': ['MADAGASCAR', 'KUNG FU PANDA'], 'HOMEM ARANHA': ['BATMAN', 'VINGADORES'] }
    },
    { category: 'Personagens', words: ['MICKEY', 'MINNIE', 'PATO DONALD', 'BOB ESPONJA', 'PATRICK', 'TOM', 'JERRY', 'SCOOBY DOO', 'GARFIELD', 'SNOOPY', 'BART SIMPSON', 'HOMER SIMPSON', 'PEPPA PIG', 'GALINHA PINTADINHA', 'PATRULHA CANINA', 'ELSA', 'ANNA', 'PIKACHU', 'GOKU', 'NARUTO', 'POKÉMON', 'BEN 10', 'HOMEM ARANHA', 'HULK'],
      similar: { 'MICKEY': ['MINNIE', 'PATO DONALD'], 'TOM': ['JERRY', 'GARFIELD'], 'ELSA': ['ANNA', 'RAPUNZEL'], 'BOB ESPONJA': ['PATRICK', 'LULA MOLUSCO'] }
    },
    { category: 'Festas', words: ['NATAL', 'ANO NOVO', 'CARNAVAL', 'PÁSCOA', 'FESTA JUNINA', 'ANIVERSÁRIO', 'CASAMENTO', 'FORMATURA', 'HALLOWEEN', 'DIA DAS MÃES', 'DIA DOS PAIS', 'DIA DAS CRIANÇAS', 'DIA DOS NAMORADOS', 'CHURRASCO', 'PIQUENIQUE', 'SHOW', 'BAILE', 'RÉVEILLON', 'BATIZADO', 'CHÁ DE BEBÊ'],
      similar: { 'NATAL': ['ANO NOVO', 'RÉVEILLON'], 'CARNAVAL': ['FESTA JUNINA', 'BAILE'], 'ANIVERSÁRIO': ['CASAMENTO', 'FORMATURA'], 'CHURRASCO': ['PIQUENIQUE', 'FESTA'] }
    },
    { category: 'Clima e Tempo', words: ['VERÃO', 'INVERNO', 'PRIMAVERA', 'OUTONO', 'CALOR', 'FRIO', 'CHUVA', 'SOL', 'NUVEM', 'VENTO', 'TEMPESTADE', 'TROVÃO', 'RAIO', 'NEVE', 'NEBLINA', 'SECA', 'ENCHENTE', 'TORNADO', 'FURACÃO', 'TERREMOTO', 'MADRUGADA', 'MANHÃ', 'TARDE', 'NOITE'],
      similar: { 'VERÃO': ['PRIMAVERA', 'CALOR'], 'INVERNO': ['OUTONO', 'FRIO'], 'CHUVA': ['TEMPESTADE', 'NEVE'], 'SOL': ['CALOR', 'VERÃO'], 'MANHÃ': ['TARDE', 'NOITE'] }
    },
    { category: 'Ações do Dia a Dia', words: ['DORMIR', 'ACORDAR', 'COMER', 'BEBER', 'CORRER', 'ANDAR', 'PULAR', 'NADAR', 'CANTAR', 'DANÇAR', 'RIR', 'CHORAR', 'GRITAR', 'ESTUDAR', 'TRABALHAR', 'BRINCAR', 'JOGAR', 'DIRIGIR', 'COZINHAR', 'LIMPAR', 'LAVAR', 'PENTEAR', 'ESCOVAR', 'ABRAÇAR', 'BEIJAR', 'REZAR'],
      similar: { 'DORMIR': ['ACORDAR', 'DESCANSAR'], 'COMER': ['BEBER', 'MASTIGAR'], 'CORRER': ['ANDAR', 'PULAR'], 'RIR': ['CHORAR', 'SORRIR'], 'CANTAR': ['DANÇAR', 'TOCAR'] }
    },
    { category: 'Objetos do Dia a Dia', words: ['CHAVE', 'CARTEIRA', 'GUARDA-CHUVA', 'ÓCULOS', 'RELÓGIO', 'CELULAR', 'MALA', 'BOLSA', 'ESCOVA', 'PENTE', 'ESPELHO', 'ISQUEIRO', 'CIGARRO', 'REVISTA', 'JORNAL', 'MOEDA', 'NOTA', 'CARTÃO', 'DOCUMENTO', 'FOTO', 'CANIVETE', 'LENÇO', 'CHICLETE', 'BALA'],
      similar: { 'CHAVE': ['CARTEIRA', 'CELULAR'], 'GUARDA-CHUVA': ['SOMBRINHA', 'CHAPÉU'], 'ESCOVA': ['PENTE', 'SECADOR'], 'MOEDA': ['NOTA', 'CARTÃO'] }
    }
];
