const wordCategoriesEN = [
    { category: 'Fruits', words: ['BANANA', 'APPLE', 'ORANGE', 'PINEAPPLE', 'STRAWBERRY', 'GRAPE', 'MANGO', 'WATERMELON', 'PEAR', 'PAPAYA', 'COCONUT', 'LEMON', 'CHERRY', 'BLACKBERRY', 'PASSION FRUIT', 'PEACH', 'AVOCADO', 'MELON', 'KIWI', 'RASPBERRY', 'BLUEBERRY', 'PLUM', 'TANGERINE', 'FIG', 'APRICOT', 'NECTARINE', 'LIME', 'GRAPEFRUIT', 'POMEGRANATE', 'CRANBERRY'],
      similar: { 'BANANA': ['APPLE', 'PEAR'], 'APPLE': ['PEAR', 'PEACH'], 'ORANGE': ['TANGERINE', 'LEMON'], 'STRAWBERRY': ['RASPBERRY', 'BLACKBERRY'] }
    },
    { category: 'Animals', words: ['DOG', 'CAT', 'HORSE', 'COW', 'PIG', 'CHICKEN', 'DUCK', 'RABBIT', 'LION', 'TIGER', 'BEAR', 'MONKEY', 'ELEPHANT', 'GIRAFFE', 'ZEBRA', 'SNAKE', 'TURTLE', 'FROG', 'FISH', 'SHARK', 'WHALE', 'DOLPHIN', 'PENGUIN', 'EAGLE', 'OWL', 'PARROT', 'BUTTERFLY', 'BEE', 'ANT', 'WOLF', 'FOX', 'DEER', 'GORILLA', 'CAMEL', 'PANDA', 'MOUSE', 'HAMSTER', 'SHEEP', 'GOAT', 'DONKEY', 'TURKEY'],
      similar: { 'DOG': ['CAT', 'WOLF'], 'CAT': ['DOG', 'RABBIT'], 'LION': ['TIGER', 'LEOPARD'], 'HORSE': ['DONKEY', 'ZEBRA'] }
    },
    { category: 'Food', words: ['PIZZA', 'HAMBURGER', 'HOT DOG', 'FRENCH FRIES', 'PASTA', 'RICE', 'BEANS', 'STEAK', 'CHICKEN', 'SALAD', 'SOUP', 'BREAD', 'TOAST', 'SANDWICH', 'PANCAKE', 'OMELETTE', 'FRIED EGG', 'BACON', 'SAUSAGE', 'HAM', 'CHEESE', 'SUSHI', 'TACO', 'BURRITO', 'NACHOS', 'RISOTTO', 'PIE', 'LASAGNA', 'NOODLES', 'CURRY'],
      similar: { 'PIZZA': ['PIE', 'FLATBREAD'], 'HAMBURGER': ['SANDWICH', 'HOT DOG'], 'RICE': ['BEANS', 'PASTA'], 'CHICKEN': ['STEAK', 'FISH'] }
    },
    { category: 'Desserts', words: ['CHOCOLATE', 'ICE CREAM', 'CAKE', 'PIE', 'COOKIE', 'BROWNIE', 'CUPCAKE', 'DONUT', 'PUDDING', 'JELLY', 'CANDY', 'LOLLIPOP', 'CARAMEL', 'CHEESECAKE', 'MOUSSE', 'WAFFLE', 'CREPE', 'MILKSHAKE', 'SUNDAE', 'COTTON CANDY', 'FUDGE', 'TRUFFLE', 'MUFFIN', 'MACARON', 'TIRAMISU'],
      similar: { 'CAKE': ['PIE', 'CUPCAKE'], 'ICE CREAM': ['MILKSHAKE', 'SUNDAE'], 'COOKIE': ['BROWNIE', 'MUFFIN'], 'CHOCOLATE': ['FUDGE', 'TRUFFLE'] }
    },
    { category: 'Drinks', words: ['WATER', 'COFFEE', 'TEA', 'MILK', 'JUICE', 'SODA', 'BEER', 'WINE', 'CHAMPAGNE', 'WHISKEY', 'VODKA', 'COCKTAIL', 'SMOOTHIE', 'MILKSHAKE', 'LEMONADE', 'HOT CHOCOLATE', 'CAPPUCCINO', 'ESPRESSO', 'ENERGY DRINK', 'ICED TEA', 'COKE', 'SPRITE', 'FANTA'],
      similar: { 'COFFEE': ['TEA', 'CAPPUCCINO'], 'SODA': ['JUICE', 'LEMONADE'], 'BEER': ['WINE', 'CHAMPAGNE'], 'WATER': ['TEA', 'JUICE'] }
    },
    { category: 'Sports', words: ['SOCCER', 'BASKETBALL', 'VOLLEYBALL', 'TENNIS', 'SWIMMING', 'RUNNING', 'CYCLING', 'SKATEBOARDING', 'SURFING', 'BOXING', 'WRESTLING', 'GYMNASTICS', 'DANCING', 'BALLET', 'ICE SKATING', 'GOLF', 'BASEBALL', 'POOL', 'BOWLING', 'PING PONG', 'CLIMBING', 'FISHING', 'HORSE RIDING', 'ROWING', 'DIVING', 'SKIING', 'YOGA', 'WEIGHT LIFTING', 'KARATE', 'JUDO'],
      similar: { 'SOCCER': ['BASKETBALL', 'VOLLEYBALL'], 'SWIMMING': ['DIVING', 'SURFING'], 'RUNNING': ['CYCLING', 'WALKING'], 'TENNIS': ['PING PONG', 'BADMINTON'] }
    },
    { category: 'Instruments', words: ['GUITAR', 'PIANO', 'DRUMS', 'VIOLIN', 'FLUTE', 'SAXOPHONE', 'TRUMPET', 'HARMONICA', 'ACCORDION', 'HARP', 'CELLO', 'BASS', 'KEYBOARD', 'UKULELE', 'BANJO', 'CLARINET', 'TROMBONE', 'TAMBOURINE', 'TRIANGLE', 'XYLOPHONE', 'ORGAN', 'MANDOLIN'],
      similar: { 'GUITAR': ['BASS', 'UKULELE'], 'PIANO': ['KEYBOARD', 'ORGAN'], 'FLUTE': ['CLARINET', 'SAXOPHONE'], 'DRUMS': ['TAMBOURINE', 'BONGOS'] }
    },
    { category: 'Jobs', words: ['DOCTOR', 'NURSE', 'DENTIST', 'VET', 'TEACHER', 'LAWYER', 'ENGINEER', 'ARCHITECT', 'POLICE', 'FIREFIGHTER', 'PILOT', 'DRIVER', 'WAITER', 'COOK', 'CHEF', 'BAKER', 'FISHERMAN', 'BUILDER', 'PAINTER', 'ELECTRICIAN', 'MECHANIC', 'BARBER', 'HAIRDRESSER', 'PHOTOGRAPHER', 'JOURNALIST', 'ACTOR', 'SINGER', 'MUSICIAN', 'ATHLETE', 'PLAYER', 'SALESMAN'],
      similar: { 'DOCTOR': ['NURSE', 'DENTIST'], 'TEACHER': ['PROFESSOR', 'TUTOR'], 'POLICE': ['FIREFIGHTER', 'SOLDIER'], 'COOK': ['CHEF', 'BAKER'] }
    },
    { category: 'Transport', words: ['CAR', 'MOTORCYCLE', 'BICYCLE', 'BUS', 'TRUCK', 'VAN', 'TAXI', 'TRAIN', 'SUBWAY', 'AIRPLANE', 'HELICOPTER', 'SHIP', 'BOAT', 'CANOE', 'JET SKI', 'SUBMARINE', 'ROCKET', 'SCOOTER', 'SKATEBOARD', 'TRACTOR', 'AMBULANCE', 'CABLE CAR'],
      similar: { 'CAR': ['MOTORCYCLE', 'TAXI'], 'BUS': ['VAN', 'SUBWAY'], 'AIRPLANE': ['HELICOPTER', 'ROCKET'], 'BOAT': ['SHIP', 'CANOE'] }
    },
    { category: 'House', words: ['SOFA', 'BED', 'TABLE', 'CHAIR', 'CLOSET', 'SHELF', 'TV', 'COMPUTER', 'PHONE', 'FRIDGE', 'STOVE', 'MICROWAVE', 'BLENDER', 'FAN', 'AIR CONDITIONER', 'LAMP', 'MIRROR', 'CLOCK', 'VASE', 'CARPET', 'CURTAIN', 'PILLOW', 'BLANKET', 'TOWEL', 'SOAP', 'PAN', 'PLATE', 'CUP', 'FORK', 'KNIFE', 'SPOON'],
      similar: { 'SOFA': ['CHAIR', 'BED'], 'TABLE': ['DESK', 'COUNTER'], 'TV': ['COMPUTER', 'PHONE'], 'FRIDGE': ['FREEZER', 'MICROWAVE'] }
    },
    { category: 'Clothes', words: ['T-SHIRT', 'SHIRT', 'BLOUSE', 'SWEATER', 'JACKET', 'COAT', 'PANTS', 'SHORTS', 'SKIRT', 'DRESS', 'PAJAMAS', 'UNDERWEAR', 'SOCKS', 'SNEAKERS', 'SHOES', 'SANDALS', 'FLIP FLOPS', 'BOOTS', 'BELT', 'CAP', 'HAT', 'SCARF', 'GLOVES', 'SUNGLASSES', 'BAG', 'BACKPACK', 'WATCH', 'BRACELET', 'NECKLACE', 'EARRINGS', 'RING', 'BIKINI', 'SWIMSUIT'],
      similar: { 'T-SHIRT': ['SHIRT', 'BLOUSE'], 'PANTS': ['SHORTS', 'JEANS'], 'SNEAKERS': ['SHOES', 'BOOTS'], 'JACKET': ['COAT', 'SWEATER'] }
    },
    { category: 'Places', words: ['HOUSE', 'APARTMENT', 'SCHOOL', 'HOSPITAL', 'CHURCH', 'MALL', 'SUPERMARKET', 'BAKERY', 'PHARMACY', 'BANK', 'RESTAURANT', 'CAFE', 'BAR', 'CINEMA', 'THEATER', 'MUSEUM', 'LIBRARY', 'PARK', 'BEACH', 'POOL', 'GYM', 'STADIUM', 'HOTEL', 'AIRPORT', 'STATION', 'STORE', 'SALON', 'GARAGE'],
      similar: { 'HOUSE': ['APARTMENT', 'BUILDING'], 'SCHOOL': ['UNIVERSITY', 'LIBRARY'], 'RESTAURANT': ['CAFE', 'BAR'], 'MALL': ['STORE', 'SUPERMARKET'] }
    },
    { category: 'Nature', words: ['SUN', 'MOON', 'STAR', 'SKY', 'CLOUD', 'RAIN', 'THUNDER', 'LIGHTNING', 'RAINBOW', 'WIND', 'SNOW', 'ICE', 'RIVER', 'SEA', 'OCEAN', 'LAKE', 'WATERFALL', 'WAVE', 'BEACH', 'SAND', 'MOUNTAIN', 'HILL', 'VALLEY', 'DESERT', 'FOREST', 'TREE', 'PLANT', 'FLOWER', 'LEAF', 'GRASS', 'ROCK', 'VOLCANO', 'CAVE'],
      similar: { 'SUN': ['MOON', 'STAR'], 'RAIN': ['SNOW', 'STORM'], 'RIVER': ['LAKE', 'SEA'], 'MOUNTAIN': ['HILL', 'VOLCANO'] }
    },
    { category: 'Flowers', words: ['ROSE', 'DAISY', 'SUNFLOWER', 'TULIP', 'LILY', 'VIOLET', 'ORCHID', 'CARNATION', 'JASMINE', 'LAVENDER', 'HIBISCUS', 'DAHLIA', 'CHRYSANTHEMUM', 'CAMELLIA', 'MAGNOLIA', 'POPPY', 'DAFFODIL', 'PETUNIA', 'IRIS', 'LOTUS'],
      similar: { 'ROSE': ['CARNATION', 'TULIP'], 'SUNFLOWER': ['DAISY', 'GERBERA'], 'ORCHID': ['LILY', 'TULIP'] }
    },
    { category: 'Colors', words: ['RED', 'BLUE', 'YELLOW', 'GREEN', 'ORANGE', 'PURPLE', 'PINK', 'BROWN', 'BLACK', 'WHITE', 'GRAY', 'BEIGE', 'GOLD', 'SILVER', 'BURGUNDY', 'LILAC', 'VIOLET', 'TURQUOISE', 'CORAL', 'SALMON', 'MUSTARD', 'CREAM', 'CARAMEL', 'BRONZE'],
      similar: { 'RED': ['ORANGE', 'PINK'], 'BLUE': ['PURPLE', 'TURQUOISE'], 'GREEN': ['YELLOW', 'BLUE'], 'PINK': ['RED', 'PURPLE'] }
    },
    { category: 'Body', words: ['HEAD', 'HAIR', 'FACE', 'EYE', 'NOSE', 'MOUTH', 'EAR', 'TOOTH', 'TONGUE', 'NECK', 'SHOULDER', 'ARM', 'ELBOW', 'HAND', 'FINGER', 'NAIL', 'CHEST', 'BELLY', 'BACK', 'LEG', 'KNEE', 'FOOT', 'HEEL', 'HEART', 'LUNG', 'BRAIN'],
      similar: { 'EYE': ['NOSE', 'MOUTH'], 'HAND': ['FOOT', 'ARM'], 'LEG': ['ARM', 'FOOT'], 'HEAD': ['FACE', 'HAIR'] }
    },
    { category: 'School', words: ['PENCIL', 'PEN', 'ERASER', 'SHARPENER', 'RULER', 'NOTEBOOK', 'BOOK', 'MAGAZINE', 'FOLDER', 'BACKPACK', 'PENCIL CASE', 'SCISSORS', 'GLUE', 'TAPE', 'STAPLER', 'PAPER', 'BLACKBOARD', 'CHALK', 'DESK', 'COMPUTER', 'CALCULATOR', 'MAP', 'GLOBE', 'TEST', 'GRADE', 'DIPLOMA'],
      similar: { 'PENCIL': ['PEN', 'CHALK'], 'NOTEBOOK': ['BOOK', 'MAGAZINE'], 'BACKPACK': ['FOLDER', 'BAG'], 'ERASER': ['SHARPENER', 'CORRECTION'] }
    },
    { category: 'Toys', words: ['BALL', 'DOLL', 'TOY CAR', 'KITE', 'YO-YO', 'TOP', 'BICYCLE', 'SCOOTER', 'SKATEBOARD', 'ROLLER SKATES', 'LEGO', 'PUZZLE', 'DOMINO', 'CHESS', 'CARDS', 'DICE', 'VIDEO GAME', 'ACTION FIGURE', 'STUFFED ANIMAL', 'TEDDY BEAR', 'ROBOT', 'AIRPLANE', 'PLAYDOUGH', 'SLIME', 'BUBBLES', 'BALLOON', 'SEESAW', 'SWING', 'SLIDE', 'JUMP ROPE', 'COSTUME', 'MASK'],
      similar: { 'BALL': ['FRISBEE', 'BALLOON'], 'DOLL': ['ACTION FIGURE', 'STUFFED ANIMAL'], 'TOY CAR': ['AIRPLANE', 'BOAT'], 'VIDEO GAME': ['COMPUTER', 'TABLET'] }
    },
    { category: 'Technology', words: ['WHATSAPP', 'INSTAGRAM', 'FACEBOOK', 'TWITTER', 'TIKTOK', 'YOUTUBE', 'NETFLIX', 'SPOTIFY', 'GOOGLE', 'AMAZON', 'UBER', 'AIRBNB', 'LINKEDIN', 'TELEGRAM', 'DISCORD', 'ZOOM', 'TINDER', 'GMAIL', 'WORD', 'EXCEL', 'PHOTOSHOP', 'WINDOWS', 'ANDROID', 'IPHONE'],
      similar: { 'WHATSAPP': ['TELEGRAM', 'MESSENGER'], 'INSTAGRAM': ['TIKTOK', 'FACEBOOK'], 'NETFLIX': ['YOUTUBE', 'PRIME VIDEO'], 'GOOGLE': ['BING', 'YAHOO'] }
    },
    { category: 'Games', words: ['MINECRAFT', 'FORTNITE', 'AMONG US', 'ROBLOX', 'FIFA', 'GTA', 'MARIO', 'SONIC', 'ZELDA', 'POKEMON', 'PACMAN', 'TETRIS', 'CANDY CRUSH', 'LEAGUE OF LEGENDS', 'VALORANT', 'COUNTER STRIKE', 'CALL OF DUTY', 'GOD OF WAR', 'THE SIMS', 'NEED FOR SPEED', 'ROCKET LEAGUE', 'FALL GUYS'],
      similar: { 'FORTNITE': ['PUBG', 'APEX'], 'MARIO': ['SONIC', 'DONKEY KONG'], 'FIFA': ['PES', 'FOOTBALL'], 'MINECRAFT': ['ROBLOX', 'TERRARIA'] }
    },
    { category: 'Movies', words: ['TITANIC', 'AVATAR', 'MATRIX', 'STAR WARS', 'HARRY POTTER', 'AVENGERS', 'SPIDER-MAN', 'BATMAN', 'SUPERMAN', 'TOY STORY', 'SHREK', 'FROZEN', 'LION KING', 'FINDING NEMO', 'MOANA', 'MINIONS', 'CARS', 'FRIENDS', 'GAME OF THRONES', 'STRANGER THINGS', 'BREAKING BAD', 'THE OFFICE', 'SQUID GAME'],
      similar: { 'BATMAN': ['SUPERMAN', 'SPIDER-MAN'], 'FROZEN': ['MOANA', 'TANGLED'], 'TOY STORY': ['CARS', 'MINIONS'], 'AVENGERS': ['JUSTICE LEAGUE', 'X-MEN'] }
    },
    { category: 'Superheroes', words: ['SUPERMAN', 'BATMAN', 'SPIDER-MAN', 'HULK', 'THOR', 'CAPTAIN AMERICA', 'IRON MAN', 'WONDER WOMAN', 'FLASH', 'AQUAMAN', 'WOLVERINE', 'DEADPOOL', 'BLACK PANTHER', 'THANOS', 'JOKER', 'LOKI', 'VENOM'],
      similar: { 'SUPERMAN': ['BATMAN', 'FLASH'], 'SPIDER-MAN': ['VENOM', 'DEADPOOL'], 'THOR': ['HULK', 'CAPTAIN AMERICA'], 'BATMAN': ['JOKER', 'ROBIN'] }
    },
    { category: 'Cartoons', words: ['MICKEY', 'MINNIE', 'DONALD DUCK', 'SPONGEBOB', 'PATRICK', 'TOM', 'JERRY', 'BUGS BUNNY', 'SCOOBY DOO', 'GARFIELD', 'SNOOPY', 'BART SIMPSON', 'HOMER SIMPSON', 'FINN', 'JAKE', 'BEN 10', 'NARUTO', 'GOKU', 'PIKACHU', 'PEPPA PIG', 'PAW PATROL', 'ELSA', 'ANNA', 'RAPUNZEL'],
      similar: { 'MICKEY': ['MINNIE', 'DONALD DUCK'], 'TOM': ['JERRY', 'BUGS BUNNY'], 'GOKU': ['NARUTO', 'LUFFY'], 'ELSA': ['ANNA', 'RAPUNZEL'] }
    },
    { category: 'Brands', words: ['NIKE', 'ADIDAS', 'PUMA', 'APPLE', 'SAMSUNG', 'COCA-COLA', 'PEPSI', 'MCDONALDS', 'BURGER KING', 'STARBUCKS', 'NESTLE', 'COLGATE', 'GILLETTE', 'NIVEA', 'DOVE'],
      similar: { 'NIKE': ['ADIDAS', 'PUMA'], 'COCA-COLA': ['PEPSI', 'FANTA'], 'MCDONALDS': ['BURGER KING', 'KFC'], 'APPLE': ['SAMSUNG', 'GOOGLE'] }
    },
    { category: 'Music', words: ['ROCK', 'POP', 'RAP', 'HIP HOP', 'REGGAE', 'ELECTRONIC', 'JAZZ', 'BLUES', 'COUNTRY', 'METAL', 'PUNK', 'GOSPEL', 'K-POP', 'CLASSICAL', 'DISCO', 'SOUL', 'R&B', 'FOLK', 'INDIE'],
      similar: { 'ROCK': ['METAL', 'PUNK'], 'RAP': ['HIP HOP', 'TRAP'], 'POP': ['DISCO', 'DANCE'], 'JAZZ': ['BLUES', 'SOUL'] }
    },
    { category: 'Celebrations', words: ['CHRISTMAS', 'NEW YEAR', 'EASTER', 'HALLOWEEN', 'THANKSGIVING', 'VALENTINES', 'MOTHERS DAY', 'FATHERS DAY', 'BIRTHDAY', 'WEDDING', 'GRADUATION', 'BAPTISM', 'PARTY', 'BBQ', 'PICNIC', 'CONCERT', 'FESTIVAL', 'CARNIVAL'],
      similar: { 'CHRISTMAS': ['NEW YEAR', 'THANKSGIVING'], 'HALLOWEEN': ['CARNIVAL', 'COSTUME PARTY'], 'BIRTHDAY': ['WEDDING', 'GRADUATION'], 'BBQ': ['PICNIC', 'PARTY'] }
    },
    { category: 'Fantasy', words: ['DRAGON', 'UNICORN', 'FAIRY', 'MERMAID', 'WITCH', 'WIZARD', 'VAMPIRE', 'WEREWOLF', 'ZOMBIE', 'GHOST', 'MUMMY', 'SKELETON', 'GIANT', 'DWARF', 'DEMON', 'ANGEL', 'CUPID', 'ELF', 'GNOME', 'TROLL', 'GOBLIN', 'PHOENIX'],
      similar: { 'VAMPIRE': ['WEREWOLF', 'ZOMBIE'], 'FAIRY': ['ANGEL', 'MERMAID'], 'WITCH': ['WIZARD', 'SORCERER'], 'DRAGON': ['UNICORN', 'PHOENIX'] }
    },
    { category: 'Feelings', words: ['HAPPINESS', 'SADNESS', 'ANGER', 'FEAR', 'LOVE', 'HATE', 'PEACE', 'JOY', 'HOPE', 'PRIDE', 'SHAME', 'JEALOUSY', 'LONELINESS', 'LAZINESS', 'HUNGER', 'TIREDNESS', 'PAIN', 'PLEASURE', 'SURPRISE', 'PASSION', 'COURAGE'],
      similar: { 'HAPPINESS': ['JOY', 'PLEASURE'], 'SADNESS': ['LONELINESS', 'GRIEF'], 'ANGER': ['HATE', 'FRUSTRATION'], 'LOVE': ['PASSION', 'AFFECTION'] }
    },
    { category: 'Weather', words: ['SUMMER', 'WINTER', 'SPRING', 'FALL', 'HOT', 'COLD', 'RAIN', 'SUN', 'CLOUD', 'WIND', 'STORM', 'THUNDER', 'LIGHTNING', 'SNOW', 'FOG', 'FROST', 'DROUGHT', 'FLOOD', 'TORNADO', 'HURRICANE'],
      similar: { 'SUMMER': ['SPRING', 'HOT'], 'WINTER': ['FALL', 'COLD'], 'RAIN': ['STORM', 'SNOW'], 'SUN': ['HOT', 'SUMMER'] }
    }
];
