const wordCategories = [
    // FRUTAS (50 palavras)
    { category: 'Frutas', words: ['BANANA', 'MAÇÃ', 'LARANJA', 'ABACAXI', 'MORANGO', 'UVA', 'MANGA', 'MELANCIA', 'PERA', 'MAMÃO', 'GOIABA', 'COCO', 'LIMÃO', 'CEREJA', 'AMORA', 'MARACUJÁ', 'ACEROLA', 'JABUTICABA', 'CAJU', 'FIGO', 'AMEIXA', 'TANGERINA', 'MEXERICA', 'JACA', 'AÇAÍ', 'PÊSSEGO', 'ABACATE', 'MELÃO', 'PITANGA', 'CARAMBOLA', 'FRAMBOESA', 'MIRTILO', 'GRAVIOLA', 'CAQUI', 'LICHIA', 'KIWI', 'LIMA', 'BERGAMOTA', 'ROMÃ', 'NECTARINA', 'DAMASCO', 'SERIGUELA', 'CAJÁ', 'UMBU', 'INGÁ', 'BACURI', 'MURICI', 'BURITI', 'PEQUI', 'MANGABA'] },

    // ANIMAIS (60 palavras)
    { category: 'Animais', words: ['CACHORRO', 'GATO', 'CAVALO', 'VACA', 'PORCO', 'GALINHA', 'PATO', 'COELHO', 'LEÃO', 'TIGRE', 'URSO', 'MACACO', 'ELEFANTE', 'GIRAFA', 'ZEBRA', 'COBRA', 'JACARÉ', 'TARTARUGA', 'SAPO', 'PEIXE', 'TUBARÃO', 'BALEIA', 'GOLFINHO', 'FOCA', 'PINGUIM', 'ÁGUIA', 'CORUJA', 'PAPAGAIO', 'ARARA', 'TUCANO', 'BORBOLETA', 'ABELHA', 'FORMIGA', 'ARANHA', 'MOSCA', 'MOSQUITO', 'BARATA', 'GRILO', 'CIGARRA', 'LOBO', 'RAPOSA', 'VEADO', 'ONÇA', 'PANTERA', 'GORILA', 'CHIMPANZÉ', 'CAMELO', 'CANGURU', 'COALA', 'PANDA', 'PREGUIÇA', 'TATU', 'CAPIVARA', 'RATO', 'HAMSTER', 'PORQUINHO', 'OVELHA', 'CABRA', 'BURRO', 'PERU'] },

    // COMIDAS (60 palavras)
    { category: 'Comidas', words: ['PIZZA', 'HAMBÚRGUER', 'CACHORRO QUENTE', 'BATATA FRITA', 'LASANHA', 'MACARRÃO', 'ESPAGUETE', 'ARROZ', 'FEIJÃO', 'FEIJOADA', 'CHURRASCO', 'BIFE', 'FRANGO', 'PEIXE FRITO', 'SALADA', 'SOPA', 'CALDO', 'PASTEL', 'COXINHA', 'ESFIHA', 'EMPADA', 'QUIBE', 'PÃO', 'TORRADA', 'SANDUÍCHE', 'TAPIOCA', 'CREPE', 'PANQUECA', 'OMELETE', 'OVO FRITO', 'BACON', 'LINGUIÇA', 'SALSICHA', 'PRESUNTO', 'QUEIJO', 'MANTEIGA', 'REQUEIJÃO', 'IOGURTE', 'SUSHI', 'TEMAKI', 'YAKISOBA', 'STROGONOFF', 'ESCONDIDINHO', 'MOQUECA', 'ACARAJÉ', 'TACOS', 'BURRITO', 'NACHOS', 'RISOTO', 'NHOQUE', 'RAVIOLI', 'TORTA', 'QUICHE', 'EMPADÃO', 'CUSCUZ', 'PAMONHA', 'CURAU', 'MINGAU', 'VITAMINA', 'AÇAÍ'] },

    // DOCES E SOBREMESAS (50 palavras)
    { category: 'Doces', words: ['CHOCOLATE', 'BRIGADEIRO', 'BEIJINHO', 'PUDIM', 'SORVETE', 'PICOLÉ', 'BOLO', 'TORTA DOCE', 'CHEESECAKE', 'MOUSSE', 'PAVÊ', 'GELATINA', 'BROWNIE', 'COOKIE', 'BISCOITO', 'BOLACHA', 'WAFER', 'BOMBOM', 'TRUFA', 'PAÇOCA', 'PÉ DE MOLEQUE', 'COCADA', 'MARIA MOLE', 'SUSPIRO', 'CHURROS', 'DONUT', 'SONHO', 'CROISSANT', 'CUPCAKE', 'MACARON', 'ÉCLAIR', 'PROFITEROLE', 'PANETTONE', 'RABANADA', 'ARROZ DOCE', 'CANJICA', 'ALGODÃO DOCE', 'MAÇÃ DO AMOR', 'BANANA SPLIT', 'MILK SHAKE', 'SUNDAE', 'AÇAÍ', 'RAPADURA', 'GOIABADA', 'MARMELADA', 'DOCE DE LEITE', 'LEITE CONDENSADO', 'CREME', 'CHANTILLY', 'CALDA'] },

    // BEBIDAS (45 palavras)
    { category: 'Bebidas', words: ['ÁGUA', 'CAFÉ', 'CHÁ', 'LEITE', 'SUCO', 'REFRIGERANTE', 'COCA-COLA', 'GUARANÁ', 'FANTA', 'SPRITE', 'CERVEJA', 'VINHO', 'CHAMPANHE', 'WHISKY', 'VODKA', 'CACHAÇA', 'CAIPIRINHA', 'MOJITO', 'BATIDA', 'LICOR', 'CONHAQUE', 'RUM', 'TEQUILA', 'GIN', 'ENERGÉTICO', 'ISOTÔNICO', 'ÁGUA DE COCO', 'LIMONADA', 'LARANJADA', 'VITAMINA', 'MILKSHAKE', 'SMOOTHIE', 'CHOCOLATE QUENTE', 'CAPPUCCINO', 'EXPRESSO', 'LATTE', 'MOCHA', 'FRAPPUCCINO', 'MATE', 'CHIMARRÃO', 'TERERÉ', 'QUENTÃO', 'VINHO QUENTE', 'PONCHE', 'REFRESCO'] },

    // ESPORTES (55 palavras)
    { category: 'Esportes', words: ['FUTEBOL', 'BASQUETE', 'VÔLEI', 'TÊNIS', 'NATAÇÃO', 'CORRIDA', 'CICLISMO', 'SKATE', 'SURF', 'HANDEBOL', 'JUDÔ', 'KARATÊ', 'BOXE', 'LUTA', 'WRESTLING', 'MMA', 'GINÁSTICA', 'DANÇA', 'BALÉ', 'PATINAÇÃO', 'HÓQUEI', 'GOLFE', 'BEISEBOL', 'SINUCA', 'BOLICHE', 'DARDOS', 'PING PONG', 'BADMINTON', 'ESCALADA', 'RAPEL', 'TRILHA', 'CAMPING', 'PESCA', 'CAÇA', 'HIPISMO', 'POLO', 'REMO', 'CANOAGEM', 'VELA', 'MERGULHO', 'ESQUI', 'SNOWBOARD', 'PARKOUR', 'CROSSFIT', 'MUSCULAÇÃO', 'ACADEMIA', 'YOGA', 'PILATES', 'ALONGAMENTO', 'FRESCOBOL', 'FUTEVÔLEI', 'FUTSAL', 'RUGBY', 'CRÍQUETE', 'AUTOMOBILISMO'] },

    // INSTRUMENTOS MUSICAIS (40 palavras)
    { category: 'Instrumentos', words: ['VIOLÃO', 'GUITARRA', 'BAIXO', 'BATERIA', 'PIANO', 'TECLADO', 'FLAUTA', 'SAXOFONE', 'TROMPETE', 'TROMBONE', 'VIOLINO', 'VIOLA', 'VIOLONCELO', 'HARPA', 'ACORDEÃO', 'SANFONA', 'GAITA', 'PANDEIRO', 'TAMBOR', 'BONGÔ', 'CONGA', 'TRIÂNGULO', 'CHOCALHO', 'MARACÁ', 'XILOFONE', 'METALOFONE', 'SINO', 'CORNETA', 'CLARINETE', 'OBOÉ', 'FLAUTA DOCE', 'BERIMBAU', 'CUÍCA', 'SURDO', 'CAVAQUINHO', 'BANDOLIM', 'UKULELE', 'BANJO', 'ÓRGÃO', 'SINTETIZADOR'] },

    // PROFISSÕES (55 palavras)
    { category: 'Profissões', words: ['MÉDICO', 'ENFERMEIRO', 'DENTISTA', 'VETERINÁRIO', 'PROFESSOR', 'ADVOGADO', 'ENGENHEIRO', 'ARQUITETO', 'POLICIAL', 'BOMBEIRO', 'SOLDADO', 'PILOTO', 'MOTORISTA', 'CAMINHONEIRO', 'TAXISTA', 'GARÇOM', 'COZINHEIRO', 'CHEF', 'PADEIRO', 'AÇOUGUEIRO', 'PESCADOR', 'AGRICULTOR', 'JARDINEIRO', 'PEDREIRO', 'PINTOR', 'ELETRICISTA', 'ENCANADOR', 'MECÂNICO', 'MARCENEIRO', 'COSTUREIRO', 'BARBEIRO', 'CABELEIREIRO', 'MAQUIADOR', 'FOTÓGRAFO', 'JORNALISTA', 'REPÓRTER', 'ATOR', 'CANTOR', 'MÚSICO', 'DANÇARINO', 'MODELO', 'ATLETA', 'JOGADOR', 'TÉCNICO', 'ÁRBITRO', 'PSICÓLOGO', 'CONTADOR', 'VENDEDOR', 'GERENTE', 'EMPRESÁRIO', 'SECRETÁRIO', 'RECEPCIONISTA', 'CARTEIRO', 'LIXEIRO', 'FAXINEIRO'] },

    // TRANSPORTES (45 palavras)
    { category: 'Transportes', words: ['CARRO', 'MOTO', 'BICICLETA', 'ÔNIBUS', 'CAMINHÃO', 'VAN', 'TÁXI', 'UBER', 'TREM', 'METRÔ', 'AVIÃO', 'HELICÓPTERO', 'NAVIO', 'BARCO', 'LANCHA', 'CANOA', 'JET SKI', 'IATE', 'BALSA', 'SUBMARINO', 'FOGUETE', 'PATINETE', 'SKATE', 'PATINS', 'TRICICLO', 'QUADRICICLO', 'KART', 'BUGGY', 'JIPE', 'PICKUP', 'SUV', 'SEDAN', 'ESPORTIVO', 'CONVERSÍVEL', 'LIMUSINE', 'AMBULÂNCIA', 'BOMBEIRO', 'POLÍCIA', 'ESCOLAR', 'TRATOR', 'COLHEITADEIRA', 'EMPILHADEIRA', 'GUINDASTE', 'TELEFÉRICO', 'BONDINHO'] },

    // OBJETOS DE CASA (55 palavras)
    { category: 'Casa', words: ['SOFÁ', 'CAMA', 'MESA', 'CADEIRA', 'ARMÁRIO', 'GUARDA-ROUPA', 'ESTANTE', 'PRATELEIRA', 'GAVETA', 'TELEVISÃO', 'COMPUTADOR', 'CELULAR', 'TABLET', 'GELADEIRA', 'FOGÃO', 'MICROONDAS', 'FORNO', 'LIQUIDIFICADOR', 'BATEDEIRA', 'CAFETEIRA', 'TORRADEIRA', 'FERRO', 'ASPIRADOR', 'VENTILADOR', 'AR CONDICIONADO', 'AQUECEDOR', 'LÂMPADA', 'ABAJUR', 'LUSTRE', 'ESPELHO', 'QUADRO', 'RELÓGIO', 'VASO', 'TAPETE', 'CORTINA', 'ALMOFADA', 'COBERTOR', 'TRAVESSEIRO', 'LENÇOL', 'TOALHA', 'SABONETE', 'SHAMPOO', 'ESCOVA', 'PASTA DE DENTE', 'PENTE', 'SECADOR', 'PANELA', 'FRIGIDEIRA', 'PRATO', 'COPO', 'TALHER', 'FACA', 'COLHER', 'GARFO', 'XÍCARA'] },

    // ROUPAS E ACESSÓRIOS (50 palavras)
    { category: 'Roupas', words: ['CAMISETA', 'CAMISA', 'BLUSA', 'REGATA', 'MOLETOM', 'CASACO', 'JAQUETA', 'BLAZER', 'TERNO', 'GRAVATA', 'CALÇA', 'BERMUDA', 'SHORT', 'SAIA', 'VESTIDO', 'MACACÃO', 'PIJAMA', 'ROUPÃO', 'CUECA', 'CALCINHA', 'SUTIÃ', 'MEIA', 'TÊNIS', 'SAPATO', 'SANDÁLIA', 'CHINELO', 'BOTA', 'SALTO', 'SAPATILHA', 'CINTO', 'BONÉ', 'CHAPÉU', 'GORRO', 'CACHECOL', 'LUVA', 'ÓCULOS', 'BOLSA', 'MOCHILA', 'CARTEIRA', 'RELÓGIO', 'PULSEIRA', 'COLAR', 'BRINCO', 'ANEL', 'ALIANÇA', 'BIQUÍNI', 'MAIÔ', 'SUNGA', 'ROUPA DE BANHO', 'UNIFORME'] },

    // LUGARES (50 palavras)
    { category: 'Lugares', words: ['CASA', 'APARTAMENTO', 'PRÉDIO', 'ESCOLA', 'FACULDADE', 'HOSPITAL', 'IGREJA', 'SHOPPING', 'MERCADO', 'SUPERMERCADO', 'PADARIA', 'FARMÁCIA', 'BANCO', 'CORREIO', 'RESTAURANTE', 'LANCHONETE', 'BAR', 'BALADA', 'CINEMA', 'TEATRO', 'MUSEU', 'BIBLIOTECA', 'PARQUE', 'PRAÇA', 'PRAIA', 'PISCINA', 'ACADEMIA', 'ESTÁDIO', 'GINÁSIO', 'CLUBE', 'HOTEL', 'POUSADA', 'CAMPING', 'FAZENDA', 'SÍTIO', 'CHÁCARA', 'AEROPORTO', 'RODOVIÁRIA', 'ESTAÇÃO', 'PORTO', 'FEIRA', 'MERCADO', 'BAZAR', 'LOJA', 'BOUTIQUE', 'SALÃO', 'BARBEARIA', 'OFICINA', 'POSTO', 'DELEGACIA'] },

    // NATUREZA (50 palavras)
    { category: 'Natureza', words: ['SOL', 'LUA', 'ESTRELA', 'CÉU', 'NUVEM', 'CHUVA', 'TROVÃO', 'RAIO', 'ARCO-ÍRIS', 'VENTO', 'TORNADO', 'FURACÃO', 'NEVE', 'GELO', 'GRANIZO', 'NEBLINA', 'NEVOEIRO', 'ORVALHO', 'RIO', 'MAR', 'OCEANO', 'LAGO', 'LAGOA', 'CACHOEIRA', 'ONDA', 'MARÉ', 'PRAIA', 'AREIA', 'MONTANHA', 'MORRO', 'COLINA', 'VALE', 'PLANÍCIE', 'DESERTO', 'FLORESTA', 'MATA', 'SELVA', 'ÁRVORE', 'PLANTA', 'FLOR', 'FOLHA', 'RAIZ', 'TRONCO', 'GALHO', 'GRAMA', 'TERRA', 'PEDRA', 'ROCHA', 'VULCÃO', 'CAVERNA'] },

    // FLORES (35 palavras)
    { category: 'Flores', words: ['ROSA', 'MARGARIDA', 'GIRASSOL', 'TULIPA', 'LÍRIO', 'VIOLETA', 'ORQUÍDEA', 'CRAVO', 'JASMIM', 'LAVANDA', 'HORTÊNSIA', 'AZALEIA', 'HIBISCO', 'DÁLIA', 'CRISÂNTEMO', 'BEGÔNIA', 'CAMÉLIA', 'GÉRBERA', 'PEÔNIA', 'MAGNÓLIA', 'FLOR DO CAMPO', 'AMOR PERFEITO', 'BOCA DE LEÃO', 'DENTE DE LEÃO', 'COPO DE LEITE', 'ANTÚRIO', 'BROMÉLIA', 'IPÊ', 'PRIMAVERA', 'FLAMBOYANT', 'CEREJEIRA', 'PAPOULA', 'NARCISO', 'AMARÍLIS', 'PETÚNIA'] },

    // CORES (30 palavras)
    { category: 'Cores', words: ['VERMELHO', 'AZUL', 'AMARELO', 'VERDE', 'LARANJA', 'ROXO', 'ROSA', 'MARROM', 'PRETO', 'BRANCO', 'CINZA', 'BEGE', 'DOURADO', 'PRATEADO', 'VINHO', 'BORDÔ', 'LILÁS', 'VIOLETA', 'TURQUESA', 'CIANO', 'MAGENTA', 'CORAL', 'SALMÃO', 'MOSTARDA', 'OLIVA', 'CREME', 'CARAMELO', 'BRONZE', 'COBRE', 'NUDE'] },

    // PARTES DO CORPO (40 palavras)
    { category: 'Corpo', words: ['CABEÇA', 'CABELO', 'ROSTO', 'TESTA', 'OLHO', 'NARIZ', 'BOCA', 'ORELHA', 'DENTE', 'LÍNGUA', 'LÁBIO', 'QUEIXO', 'BOCHECHA', 'SOBRANCELHA', 'CÍLIO', 'PESCOÇO', 'OMBRO', 'BRAÇO', 'COTOVELO', 'PULSO', 'MÃO', 'DEDO', 'UNHA', 'PEITO', 'BARRIGA', 'UMBIGO', 'COSTAS', 'CINTURA', 'QUADRIL', 'PERNA', 'COXA', 'JOELHO', 'CANELA', 'TORNOZELO', 'PÉ', 'CALCANHAR', 'CORAÇÃO', 'PULMÃO', 'CÉREBRO', 'OSSO'] },

    // ESCOLA E ESCRITÓRIO (45 palavras)
    { category: 'Escola', words: ['LÁPIS', 'CANETA', 'BORRACHA', 'APONTADOR', 'RÉGUA', 'CADERNO', 'LIVRO', 'REVISTA', 'JORNAL', 'PASTA', 'MOCHILA', 'ESTOJO', 'TESOURA', 'COLA', 'FITA', 'GRAMPEADOR', 'GRAMPO', 'CLIPS', 'PAPEL', 'CARTOLINA', 'LOUSA', 'GIZ', 'PINCEL', 'QUADRO', 'CARTEIRA', 'MESA', 'COMPUTADOR', 'IMPRESSORA', 'CALCULADORA', 'GLOBO', 'MAPA', 'DICIONÁRIO', 'AGENDA', 'CALENDÁRIO', 'ENVELOPE', 'CARIMBO', 'PERFURADOR', 'FICHÁRIO', 'PROVA', 'NOTA', 'BOLETIM', 'DIPLOMA', 'CERTIFICADO', 'CADEIRA', 'MARCADOR'] },

    // JOGOS E BRINQUEDOS (50 palavras)
    { category: 'Brinquedos', words: ['BOLA', 'BONECA', 'CARRINHO', 'PIPA', 'IOIÔ', 'PIÃO', 'PETECA', 'BICICLETA', 'PATINETE', 'SKATE', 'PATINS', 'LEGO', 'QUEBRA-CABEÇA', 'DOMINÓ', 'XADREZ', 'DAMA', 'BARALHO', 'DADO', 'VIDEOGAME', 'CONTROLE', 'COMPUTADOR', 'TABLET', 'CELULAR', 'BONECO', 'PELÚCIA', 'URSO', 'DINOSSAURO', 'ROBÔ', 'AVIÃO', 'HELICÓPTERO', 'BARCO', 'TREM', 'MASSINHA', 'SLIME', 'BOLHA', 'BALÃO', 'BEXIGA', 'GANGORRA', 'BALANÇO', 'ESCORREGADOR', 'CAMA ELÁSTICA', 'PISCINA DE BOLINHA', 'BAMBOLÊ', 'CORDA', 'ELÁSTICO', 'FANTASIA', 'MÁSCARA', 'ESPADA', 'ESCUDO', 'COROA'] },

    // FERRAMENTAS (35 palavras)
    { category: 'Ferramentas', words: ['MARTELO', 'CHAVE DE FENDA', 'CHAVE INGLESA', 'ALICATE', 'SERROTE', 'FURADEIRA', 'PARAFUSADEIRA', 'PREGO', 'PARAFUSO', 'PORCA', 'BROCA', 'LIXA', 'PINCEL', 'ROLO', 'TRENA', 'METRO', 'NÍVEL', 'ESCADA', 'PÁ', 'ENXADA', 'PICARETA', 'MACHADO', 'FOICE', 'TESOURA DE PODA', 'MANGUEIRA', 'REGADOR', 'BALDE', 'VASSOURA', 'RODO', 'PÁ DE LIXO', 'ESPANADOR', 'PANO', 'ESPONJA', 'ESCOVA', 'ESFREGÃO'] },

    // ELETRODOMÉSTICOS (35 palavras)
    { category: 'Eletrodomésticos', words: ['GELADEIRA', 'FREEZER', 'FOGÃO', 'MICROONDAS', 'FORNO', 'AIRFRYER', 'FRITADEIRA', 'LIQUIDIFICADOR', 'BATEDEIRA', 'MIXER', 'PROCESSADOR', 'CAFETEIRA', 'CHALEIRA', 'TORRADEIRA', 'SANDUICHEIRA', 'GRILL', 'PANELA ELÉTRICA', 'MÁQUINA DE LAVAR', 'SECADORA', 'FERRO DE PASSAR', 'ASPIRADOR', 'ROBÔ ASPIRADOR', 'VENTILADOR', 'AR CONDICIONADO', 'AQUECEDOR', 'UMIDIFICADOR', 'PURIFICADOR', 'TELEVISÃO', 'RÁDIO', 'SOM', 'HOME THEATER', 'VIDEOCASSETE', 'DVD', 'BLUE-RAY', 'PROJETOR'] },

    // APPS E TECNOLOGIA (40 palavras)
    { category: 'Tecnologia', words: ['WHATSAPP', 'INSTAGRAM', 'FACEBOOK', 'TWITTER', 'TIKTOK', 'YOUTUBE', 'NETFLIX', 'SPOTIFY', 'GOOGLE', 'AMAZON', 'UBER', 'IFOOD', 'MERCADO LIVRE', 'AIRBNB', 'LINKEDIN', 'PINTEREST', 'SNAPCHAT', 'TELEGRAM', 'DISCORD', 'ZOOM', 'TEAMS', 'MEET', 'TINDER', 'WAZE', 'MAPS', 'GMAIL', 'OUTLOOK', 'WORD', 'EXCEL', 'POWERPOINT', 'PHOTOSHOP', 'CANVA', 'DRIVE', 'DROPBOX', 'ICLOUD', 'CHROME', 'SAFARI', 'WINDOWS', 'ANDROID', 'IPHONE'] },

    // JOGOS DIGITAIS (40 palavras)
    { category: 'Games', words: ['MINECRAFT', 'FORTNITE', 'FREE FIRE', 'AMONG US', 'ROBLOX', 'FIFA', 'GTA', 'CALL OF DUTY', 'LEAGUE OF LEGENDS', 'VALORANT', 'COUNTER STRIKE', 'PUBG', 'FALL GUYS', 'CANDY CRUSH', 'CLASH ROYALE', 'CLASH OF CLANS', 'MARIO', 'SONIC', 'ZELDA', 'POKEMON', 'PACMAN', 'TETRIS', 'STREET FIGHTER', 'MORTAL KOMBAT', 'GOD OF WAR', 'THE SIMS', 'RESIDENT EVIL', 'NEED FOR SPEED', 'ROCKET LEAGUE', 'OVERWATCH', 'APEX LEGENDS', 'ANIMAL CROSSING', 'DOTA', 'WORLD OF WARCRAFT', 'DIABLO', 'ASSASSINS CREED', 'RED DEAD', 'CYBERPUNK', 'ELDEN RING', 'DARK SOULS'] },

    // FILMES E SÉRIES (45 palavras)
    { category: 'Filmes', words: ['TITANIC', 'AVATAR', 'MATRIX', 'STAR WARS', 'HARRY POTTER', 'VINGADORES', 'HOMEM ARANHA', 'BATMAN', 'SUPERMAN', 'JURASSIC PARK', 'TOY STORY', 'SHREK', 'FROZEN', 'REI LEÃO', 'PROCURANDO NEMO', 'DIVERTIDA MENTE', 'MOANA', 'ENCANTO', 'COCO', 'MONSTROS SA', 'CARROS', 'MINIONS', 'GAME OF THRONES', 'BREAKING BAD', 'STRANGER THINGS', 'LA CASA DE PAPEL', 'FRIENDS', 'THE OFFICE', 'GREYS ANATOMY', 'WALKING DEAD', 'VIKINGS', 'PEAKY BLINDERS', 'BLACK MIRROR', 'ROUND 6', 'WANDAVISION', 'MANDALORIAN', 'COBRA KAI', 'LUCIFER', 'YOU', 'BRIDGERTON', 'WEDNESDAY', 'EMILY IN PARIS', 'DARK', 'OZARK', 'THE CROWN'] },

    // SUPER-HERÓIS E VILÕES (35 palavras)
    { category: 'Super-heróis', words: ['SUPERMAN', 'BATMAN', 'HOMEM ARANHA', 'HULK', 'THOR', 'CAPITÃO AMÉRICA', 'HOMEM DE FERRO', 'VIÚVA NEGRA', 'GAVIÃO ARQUEIRO', 'PANTERA NEGRA', 'DOUTOR ESTRANHO', 'MULHER MARAVILHA', 'FLASH', 'AQUAMAN', 'LANTERNA VERDE', 'WOLVERINE', 'DEADPOOL', 'THANOS', 'CORINGA', 'LEX LUTHOR', 'LOKI', 'MAGNETO', 'VENOM', 'DUENDE VERDE', 'ULTRON', 'HELA', 'APOCALIPSE', 'DARKSEID', 'CAVEIRA VERMELHA', 'KINGPIN', 'MYSTERIO', 'ELECTRO', 'ABUTRE', 'SANDMAN', 'OCTOPUS'] },

    // PERSONAGENS DE DESENHO (40 palavras)
    { category: 'Desenhos', words: ['MICKEY', 'MINNIE', 'PATO DONALD', 'PATETA', 'PLUTO', 'BOB ESPONJA', 'PATRICK', 'TOM', 'JERRY', 'PERNALONGA', 'PATOLINO', 'SCOOBY DOO', 'POPEYE', 'GARFIELD', 'SNOOPY', 'BART SIMPSON', 'HOMER SIMPSON', 'PETER GRIFFIN', 'STAN MARSH', 'FINN', 'JAKE', 'MORDECAI', 'RIGBY', 'GUMBALL', 'BEN 10', 'NARUTO', 'GOKU', 'LUFFY', 'PIKACHU', 'ASH', 'PEPPA PIG', 'DORA', 'PATRULHA CANINA', 'MOANA', 'ELSA', 'ANNA', 'RAPUNZEL', 'BELA', 'CINDERELA', 'ARIEL'] },

    // MARCAS (40 palavras)
    { category: 'Marcas', words: ['NIKE', 'ADIDAS', 'PUMA', 'APPLE', 'SAMSUNG', 'XIAOMI', 'MOTOROLA', 'LG', 'SONY', 'COCA-COLA', 'PEPSI', 'FANTA', 'GUARANÁ', 'MCDONALDS', 'BURGER KING', 'SUBWAY', 'KFC', 'PIZZA HUT', 'STARBUCKS', 'NESCAFÉ', 'NESTLE', 'KIBON', 'BAUDUCCO', 'SADIA', 'PERDIGÃO', 'OMO', 'ARIEL', 'COLGATE', 'ORAL-B', 'GILLETTE', 'NIVEA', 'DOVE', 'PANTENE', 'LOREAL', 'AVON', 'NATURA', 'BOTICÁRIO', 'HAVAIANAS', 'MELISSA', 'HERING'] },

    // GÊNEROS MUSICAIS (30 palavras)
    { category: 'Música', words: ['ROCK', 'POP', 'SERTANEJO', 'FUNK', 'RAP', 'HIP HOP', 'PAGODE', 'SAMBA', 'FORRÓ', 'AXÉ', 'MPB', 'BOSSA NOVA', 'REGGAE', 'ELETRÔNICA', 'HOUSE', 'TECHNO', 'JAZZ', 'BLUES', 'COUNTRY', 'METAL', 'PUNK', 'INDIE', 'GOSPEL', 'K-POP', 'TRAP', 'DRILL', 'REGGAETON', 'CLÁSSICA', 'ÓPERA', 'DISCO'] },

    // FESTAS E CELEBRAÇÕES (35 palavras)
    { category: 'Festas', words: ['NATAL', 'ANO NOVO', 'CARNAVAL', 'PÁSCOA', 'FESTA JUNINA', 'DIA DAS MÃES', 'DIA DOS PAIS', 'DIA DAS CRIANÇAS', 'DIA DOS NAMORADOS', 'HALLOWEEN', 'ANIVERSÁRIO', 'CASAMENTO', 'NOIVADO', 'FORMATURA', 'BATIZADO', 'PRIMEIRA COMUNHÃO', 'QUINZE ANOS', 'BODAS', 'CHÁ DE BEBÊ', 'CHÁ BAR', 'CHÁ DE PANELA', 'CHURRASCO', 'LUAU', 'FESTA À FANTASIA', 'BAILE', 'BALADA', 'SHOW', 'FESTIVAL', 'RÉVEILLON', 'VIRADA', 'CONFRATERNIZAÇÃO', 'HAPPY HOUR', 'PIQUENIQUE', 'ACAMPAMENTO', 'RETIRO'] },

    // FANTASIA E MITOLOGIA (35 palavras)
    { category: 'Fantasia', words: ['DRAGÃO', 'UNICÓRNIO', 'FADA', 'SEREIA', 'ELFO', 'DUENDE', 'BRUXA', 'MAGO', 'FEITICEIRO', 'VAMPIRO', 'LOBISOMEM', 'ZUMBI', 'FANTASMA', 'MÚMIA', 'ESQUELETO', 'CAVEIRA', 'OGRO', 'TROLL', 'GIGANTE', 'ANÃO', 'GNOMO', 'CENTAURO', 'MINOTAURO', 'FÊNIX', 'GRIFO', 'PEGASUS', 'CICLOPE', 'MEDUSA', 'KRAKEN', 'HIDRA', 'QUIMERA', 'DEMÔNIO', 'ANJO', 'CUPIDO', 'DEUSA'] },

    // SENTIMENTOS (35 palavras)
    { category: 'Sentimentos', words: ['ALEGRIA', 'TRISTEZA', 'RAIVA', 'MEDO', 'AMOR', 'ÓDIO', 'PAZ', 'ANSIEDADE', 'FELICIDADE', 'SAUDADE', 'ESPERANÇA', 'GRATIDÃO', 'ORGULHO', 'VERGONHA', 'CULPA', 'INVEJA', 'CIÚME', 'SOLIDÃO', 'TÉDIO', 'PREGUIÇA', 'FOME', 'SEDE', 'SONO', 'CANSAÇO', 'DOR', 'PRAZER', 'SURPRESA', 'NOJO', 'PAIXÃO', 'CARINHO', 'TERNURA', 'ADMIRAÇÃO', 'RESPEITO', 'CONFIANÇA', 'CORAGEM'] },

    // MEIOS DE COMUNICAÇÃO (30 palavras)
    { category: 'Comunicação', words: ['TELEVISÃO', 'RÁDIO', 'JORNAL', 'REVISTA', 'INTERNET', 'CELULAR', 'TELEFONE', 'COMPUTADOR', 'TABLET', 'NOTEBOOK', 'EMAIL', 'MENSAGEM', 'CARTA', 'CARTÃO', 'CONVITE', 'BILHETE', 'AVISO', 'PLACA', 'OUTDOOR', 'PANFLETO', 'FOLHETO', 'CATÁLOGO', 'LIVRO', 'E-BOOK', 'PODCAST', 'VÍDEO', 'FOTO', 'SELFIE', 'STORY', 'POST'] },

    // MÓVEIS (30 palavras)
    { category: 'Móveis', words: ['SOFÁ', 'POLTRONA', 'CADEIRA', 'BANCO', 'BANQUETA', 'MESA', 'MESA DE CENTRO', 'ESCRIVANINHA', 'CAMA', 'BELICHE', 'BERÇO', 'COLCHÃO', 'ARMÁRIO', 'GUARDA-ROUPA', 'CÔMODA', 'CRIADO-MUDO', 'ESTANTE', 'PRATELEIRA', 'RACK', 'PAINEL', 'PENTEADEIRA', 'SAPATEIRA', 'CABIDEIRO', 'CABIDE', 'BAÚ', 'PUFF', 'REDE', 'ESPREGUIÇADEIRA', 'BANCO DE JARDIM', 'CADEIRA DE PRAIA'] }
];

// CATEGORIAS ADICIONAIS PARA COMPLETAR 1500+

const moreCategories = [
    // COMIDA DE RUA (25 palavras)
    { category: 'Comida de Rua', words: ['PIPOCA', 'ALGODÃO DOCE', 'MAÇÃ DO AMOR', 'CHURROS', 'CREPE', 'TAPIOCA', 'AÇAÍ', 'MILHO VERDE', 'PAMONHA', 'ESPETINHO', 'CHURRASCO', 'PASTEL', 'COXINHA', 'ACARAJÉ', 'CACHORRO QUENTE', 'HAMBÚRGUER', 'BATATA FRITA', 'AMENDOIM', 'CASTANHA', 'SORVETE', 'PICOLÉ', 'GELADINHO', 'CALDO DE CANA', 'ÁGUA DE COCO', 'LIMONADA'] },

    // ANIMAIS DE FAZENDA (25 palavras)
    { category: 'Fazenda', words: ['VACA', 'BOI', 'TOURO', 'BEZERRO', 'CAVALO', 'ÉGUA', 'POTRO', 'BURRO', 'MULA', 'PORCO', 'LEITÃO', 'GALINHA', 'GALO', 'PINTINHO', 'PATO', 'GANSO', 'PERU', 'CABRA', 'BODE', 'OVELHA', 'CARNEIRO', 'CORDEIRO', 'COELHO', 'ABELHA', 'PEIXE'] },

    // MATERIAL ESCOLAR (25 palavras)
    { category: 'Material Escolar', words: ['LÁPIS', 'CANETA', 'BORRACHA', 'APONTADOR', 'RÉGUA', 'COMPASSO', 'TRANSFERIDOR', 'ESQUADRO', 'CADERNO', 'FICHÁRIO', 'PASTA', 'MOCHILA', 'ESTOJO', 'TESOURA', 'COLA', 'DUREX', 'GRAMPEADOR', 'CLIPS', 'MARCA TEXTO', 'CORRETIVO', 'LÁPIS DE COR', 'CANETINHA', 'GIZ DE CERA', 'TINTA', 'PINCEL'] },

    // ITENS DE COZINHA (30 palavras)
    { category: 'Cozinha', words: ['PANELA', 'FRIGIDEIRA', 'CAÇAROLA', 'FORMA', 'ASSADEIRA', 'TRAVESSA', 'TIGELA', 'PRATO', 'XÍCARA', 'CANECA', 'COPO', 'TAÇA', 'COLHER', 'GARFO', 'FACA', 'ESPÁTULA', 'CONCHA', 'ESCUMADEIRA', 'RALADOR', 'DESCASCADOR', 'ABRIDOR', 'SACA-ROLHAS', 'TÁBUA', 'ROLO', 'PENEIRA', 'COADOR', 'JARRA', 'GARRAFA', 'POTE', 'VASILHA'] },

    // PARTES DA CASA (25 palavras)
    { category: 'Partes da Casa', words: ['SALA', 'QUARTO', 'COZINHA', 'BANHEIRO', 'LAVABO', 'VARANDA', 'SACADA', 'GARAGEM', 'JARDIM', 'QUINTAL', 'PISCINA', 'CHURRASQUEIRA', 'ÁREA DE SERVIÇO', 'DESPENSA', 'SÓTÃO', 'PORÃO', 'ESCADA', 'CORREDOR', 'HALL', 'PORTA', 'JANELA', 'TELHADO', 'MURO', 'PORTÃO', 'CERCA'] },

    // ESTAÇÕES E CLIMA (20 palavras)
    { category: 'Clima', words: ['VERÃO', 'INVERNO', 'PRIMAVERA', 'OUTONO', 'CALOR', 'FRIO', 'CHUVA', 'SOL', 'NUVEM', 'VENTO', 'TEMPESTADE', 'TROVÃO', 'RAIO', 'NEVE', 'GRANIZO', 'NEBLINA', 'GEADA', 'SECA', 'ENCHENTE', 'MARÉ'] }
];

// Merge additional categories
wordCategories.push(...moreCategories);
