// WORDS-PT.JS - Palavras em Português (Brasil) — Revisado
//
// Regras deste arquivo:
// 1. Só entram palavras COMUNS, que qualquer pessoa conhece e sobre as quais
//    há muito o que falar (descartadas palavras obscuras ou difíceis).
// 2. TODA palavra tem entrada em `similar` com exatamente 3 opções, ordenadas
//    por proximidade: [0] = muito próxima (impostor demora a se descobrir),
//    [1] = média (equilíbrio ideal), [2] = mais distante (impostor percebe
//    antes, mas ainda consegue disfarçar).
//    A palavra similar nunca é sinônimo da original (senão o impostor nunca
//    se descobre) nem de outro universo (senão ele se entrega na primeira fala).
// 3. `questions` são as perguntas do Modo Perguntas, adequadas à categoria:
//    valem tanto para a palavra verdadeira quanto para a palavra do impostor.

const genericQuestionsPT = [
    'Onde você costuma ver isso?',
    'Com que frequência isso aparece na sua vida?',
    'Pra quem você daria isso de presente?',
    'Que tipo de pessoa mais gosta disso?',
    'Que sentimento isso te traz?',
    'Quanto isso custa, mais ou menos?',
    'O que você usaria junto com isso?',
    'Em que época do ano isso aparece mais?'
];

const animalQuestionsPT = [
    'Onde esse ser vive?',
    'O que ele come?',
    'Que nome você daria se tivesse um?',
    'O que você faria se encontrasse um na sua frente?',
    'Compare o tamanho dele com outra coisa',
    'Como ele se locomove?',
    'Que outro animal vive perto dele?',
    'Onde você viu um de verdade pela última vez?'
];

const comidaQuestionsPT = [
    'Com o que você come isso?',
    'Em qual refeição isso aparece?',
    'Onde você costuma comer isso?',
    'Quem você conhece que prepara isso bem?',
    'Em que ocasião você comeu isso pela última vez?',
    'O que você bebe junto com isso?',
    'O que não pode faltar junto com isso?',
    'Que outra comida combina com essa?'
];

const objetoQuestionsPT = [
    'Em que lugar da casa isso costuma ficar?',
    'Com que frequência você usa isso?',
    'Quanto isso custa, mais ou menos?',
    'De que material isso é feito?',
    'Onde você conseguiu o seu?',
    'Compare o tamanho disso com outro objeto',
    'Pra quem você emprestaria isso?',
    'O que acontece se isso quebrar ou sumir?'
];

const lugarQuestionsPT = [
    'O que você faz nesse lugar?',
    'Com quem você costuma ir a esse lugar?',
    'Com que frequência você vai?',
    'O que você leva quando vai pra lá?',
    'Que sons você ouve nesse lugar?',
    'Quando foi a última vez que você foi?',
    'Que cheiro tem esse lugar?',
    'O que uma criança faria nesse lugar?'
];

const wordCategoriesPT = [
    {
        category: 'Frutas',
        words: ['BANANA', 'MAÇÃ', 'LARANJA', 'ABACAXI', 'MORANGO', 'UVA', 'MANGA', 'MELANCIA', 'PERA', 'MAMÃO', 'LIMÃO', 'COCO', 'GOIABA', 'MARACUJÁ', 'ABACATE', 'MELÃO', 'KIWI', 'PÊSSEGO', 'TANGERINA', 'AÇAÍ', 'JABUTICABA', 'CAJU', 'JACA', 'AMEIXA', 'CEREJA'],
        similar: {
            'BANANA': ['MAMÃO', 'MANGA', 'ABACAXI'],
            'MAÇÃ': ['PERA', 'PÊSSEGO', 'UVA'],
            'LARANJA': ['TANGERINA', 'LIMÃO', 'ABACAXI'],
            'ABACAXI': ['MANGA', 'MELÃO', 'LARANJA'],
            'MORANGO': ['CEREJA', 'UVA', 'MELANCIA'],
            'UVA': ['JABUTICABA', 'CEREJA', 'MORANGO'],
            'MANGA': ['MAMÃO', 'PÊSSEGO', 'ABACAXI'],
            'MELANCIA': ['MELÃO', 'MAMÃO', 'ABACAXI'],
            'PERA': ['MAÇÃ', 'PÊSSEGO', 'GOIABA'],
            'MAMÃO': ['MELÃO', 'MANGA', 'BANANA'],
            'LIMÃO': ['LARANJA', 'TANGERINA', 'MARACUJÁ'],
            'COCO': ['ABACAXI', 'JACA', 'MELÃO'],
            'GOIABA': ['PÊSSEGO', 'MAÇÃ', 'MANGA'],
            'MARACUJÁ': ['KIWI', 'GOIABA', 'LIMÃO'],
            'ABACATE': ['MANGA', 'MAMÃO', 'COCO'],
            'MELÃO': ['MELANCIA', 'MAMÃO', 'ABACAXI'],
            'KIWI': ['MARACUJÁ', 'MORANGO', 'UVA'],
            'PÊSSEGO': ['AMEIXA', 'GOIABA', 'MAÇÃ'],
            'TANGERINA': ['LARANJA', 'LIMÃO', 'UVA'],
            'AÇAÍ': ['JABUTICABA', 'UVA', 'MORANGO'],
            'JABUTICABA': ['UVA', 'AÇAÍ', 'CEREJA'],
            'CAJU': ['GOIABA', 'MANGA', 'ABACAXI'],
            'JACA': ['MANGA', 'ABACAXI', 'COCO'],
            'AMEIXA': ['PÊSSEGO', 'UVA', 'MAÇÃ'],
            'CEREJA': ['MORANGO', 'UVA', 'MAÇÃ']
        },
        questions: [
            'Com o que você come essa fruta?',
            'Que bebida dá pra fazer com ela?',
            'Como você prepara ela pra comer?',
            'Com que outra fruta ela parece?',
            'Em que momento do dia você comeria?',
            'Onde você compra essa fruta?',
            'Compare o tamanho dela com outra coisa',
            'Que sobremesa leva essa fruta?'
        ]
    },
    {
        category: 'Animais de Estimação',
        words: ['CACHORRO', 'GATO', 'HAMSTER', 'COELHO', 'PEIXE', 'TARTARUGA', 'JABUTI', 'PAPAGAIO', 'PERIQUITO', 'CALOPSITA', 'CANÁRIO', 'PORQUINHO DA ÍNDIA'],
        similar: {
            'CACHORRO': ['GATO', 'COELHO', 'HAMSTER'],
            'GATO': ['CACHORRO', 'COELHO', 'HAMSTER'],
            'HAMSTER': ['PORQUINHO DA ÍNDIA', 'COELHO', 'GATO'],
            'COELHO': ['HAMSTER', 'PORQUINHO DA ÍNDIA', 'GATO'],
            'PEIXE': ['TARTARUGA', 'JABUTI', 'HAMSTER'],
            'TARTARUGA': ['JABUTI', 'PEIXE', 'HAMSTER'],
            'JABUTI': ['TARTARUGA', 'PEIXE', 'COELHO'],
            'PAPAGAIO': ['ARARA', 'PERIQUITO', 'CANÁRIO'],
            'PERIQUITO': ['CALOPSITA', 'CANÁRIO', 'PAPAGAIO'],
            'CALOPSITA': ['PERIQUITO', 'PAPAGAIO', 'CANÁRIO'],
            'CANÁRIO': ['PERIQUITO', 'CALOPSITA', 'PAPAGAIO'],
            'PORQUINHO DA ÍNDIA': ['HAMSTER', 'COELHO', 'GATO']
        },
        questions: animalQuestionsPT
    },
    {
        category: 'Animais da Fazenda',
        words: ['VACA', 'BOI', 'CAVALO', 'PORCO', 'GALINHA', 'GALO', 'PINTINHO', 'PATO', 'GANSO', 'PERU', 'OVELHA', 'CARNEIRO', 'CABRA', 'BODE', 'BURRO'],
        similar: {
            'VACA': ['BOI', 'CABRA', 'OVELHA'],
            'BOI': ['VACA', 'CAVALO', 'CABRA'],
            'CAVALO': ['BURRO', 'BOI', 'CABRA'],
            'PORCO': ['JAVALI', 'VACA', 'CABRA'],
            'GALINHA': ['PATO', 'PERU', 'GANSO'],
            'GALO': ['GALINHA', 'PERU', 'PATO'],
            'PINTINHO': ['GALINHA', 'PATO', 'PERU'],
            'PATO': ['GANSO', 'GALINHA', 'PERU'],
            'GANSO': ['PATO', 'GALINHA', 'CISNE'],
            'PERU': ['GALINHA', 'GANSO', 'PATO'],
            'OVELHA': ['CARNEIRO', 'CABRA', 'VACA'],
            'CARNEIRO': ['OVELHA', 'BODE', 'CABRA'],
            'CABRA': ['BODE', 'OVELHA', 'VACA'],
            'BODE': ['CABRA', 'CARNEIRO', 'BURRO'],
            'BURRO': ['CAVALO', 'BOI', 'BODE']
        },
        questions: animalQuestionsPT
    },
    {
        category: 'Animais Selvagens',
        words: ['LEÃO', 'TIGRE', 'URSO', 'LOBO', 'RAPOSA', 'ELEFANTE', 'GIRAFA', 'ZEBRA', 'MACACO', 'GORILA', 'HIPOPÓTAMO', 'RINOCERONTE', 'JACARÉ', 'COBRA', 'ONÇA', 'CANGURU', 'COALA', 'PANDA', 'PREGUIÇA', 'TATU', 'TAMANDUÁ', 'CAPIVARA', 'VEADO'],
        similar: {
            'LEÃO': ['TIGRE', 'ONÇA', 'LOBO'],
            'TIGRE': ['LEÃO', 'ONÇA', 'LOBO'],
            'URSO': ['PANDA', 'GORILA', 'LOBO'],
            'LOBO': ['RAPOSA', 'CACHORRO', 'URSO'],
            'RAPOSA': ['LOBO', 'CACHORRO', 'ONÇA'],
            'ELEFANTE': ['RINOCERONTE', 'HIPOPÓTAMO', 'GIRAFA'],
            'GIRAFA': ['ZEBRA', 'ELEFANTE', 'CAVALO'],
            'ZEBRA': ['CAVALO', 'GIRAFA', 'VEADO'],
            'MACACO': ['GORILA', 'PREGUIÇA', 'COALA'],
            'GORILA': ['MACACO', 'URSO', 'PANDA'],
            'HIPOPÓTAMO': ['RINOCERONTE', 'ELEFANTE', 'JACARÉ'],
            'RINOCERONTE': ['HIPOPÓTAMO', 'ELEFANTE', 'JACARÉ'],
            'JACARÉ': ['CROCODILO', 'HIPOPÓTAMO', 'COBRA'],
            'COBRA': ['LAGARTO', 'JACARÉ', 'ARANHA'],
            'ONÇA': ['TIGRE', 'LEÃO', 'LOBO'],
            'CANGURU': ['COALA', 'VEADO', 'MACACO'],
            'COALA': ['PANDA', 'PREGUIÇA', 'MACACO'],
            'PANDA': ['URSO', 'COALA', 'GORILA'],
            'PREGUIÇA': ['COALA', 'MACACO', 'TAMANDUÁ'],
            'TATU': ['TAMANDUÁ', 'TARTARUGA', 'CAPIVARA'],
            'TAMANDUÁ': ['TATU', 'PREGUIÇA', 'CAPIVARA'],
            'CAPIVARA': ['HIPOPÓTAMO', 'TATU', 'VEADO'],
            'VEADO': ['ZEBRA', 'CAVALO', 'CANGURU']
        },
        questions: animalQuestionsPT
    },
    {
        category: 'Animais do Mar',
        words: ['TUBARÃO', 'BALEIA', 'GOLFINHO', 'POLVO', 'LULA', 'CARANGUEJO', 'CAMARÃO', 'LAGOSTA', 'ESTRELA DO MAR', 'ÁGUA-VIVA', 'CAVALO-MARINHO', 'FOCA', 'PINGUIM', 'ARRAIA', 'ATUM', 'SARDINHA', 'OSTRA'],
        similar: {
            'TUBARÃO': ['BALEIA', 'GOLFINHO', 'ARRAIA'],
            'BALEIA': ['GOLFINHO', 'TUBARÃO', 'FOCA'],
            'GOLFINHO': ['BALEIA', 'FOCA', 'TUBARÃO'],
            'POLVO': ['LULA', 'ÁGUA-VIVA', 'CARANGUEJO'],
            'LULA': ['POLVO', 'ÁGUA-VIVA', 'CAMARÃO'],
            'CARANGUEJO': ['SIRI', 'LAGOSTA', 'CAMARÃO'],
            'CAMARÃO': ['LAGOSTA', 'CARANGUEJO', 'LULA'],
            'LAGOSTA': ['CAMARÃO', 'CARANGUEJO', 'POLVO'],
            'ESTRELA DO MAR': ['ÁGUA-VIVA', 'CAVALO-MARINHO', 'POLVO'],
            'ÁGUA-VIVA': ['POLVO', 'ESTRELA DO MAR', 'LULA'],
            'CAVALO-MARINHO': ['ESTRELA DO MAR', 'ÁGUA-VIVA', 'CAMARÃO'],
            'FOCA': ['LEÃO-MARINHO', 'GOLFINHO', 'PINGUIM'],
            'PINGUIM': ['FOCA', 'PATO', 'GOLFINHO'],
            'ARRAIA': ['TUBARÃO', 'ÁGUA-VIVA', 'POLVO'],
            'ATUM': ['SARDINHA', 'SALMÃO', 'TUBARÃO'],
            'SARDINHA': ['ATUM', 'SALMÃO', 'CAMARÃO'],
            'OSTRA': ['MEXILHÃO', 'CAMARÃO', 'CARANGUEJO']
        },
        questions: animalQuestionsPT
    },
    {
        category: 'Aves',
        words: ['ÁGUIA', 'CORUJA', 'GAVIÃO', 'FALCÃO', 'PAPAGAIO', 'ARARA', 'TUCANO', 'BEIJA-FLOR', 'POMBO', 'PARDAL', 'ANDORINHA', 'FLAMINGO', 'CISNE', 'GARÇA', 'AVESTRUZ', 'PAVÃO', 'PINGUIM', 'CORVO', 'PICA-PAU', 'SABIÁ', 'BEM-TE-VI', 'URUBU', 'GAIVOTA', 'CANÁRIO'],
        similar: {
            'ÁGUIA': ['GAVIÃO', 'FALCÃO', 'CORUJA'],
            'CORUJA': ['GAVIÃO', 'ÁGUIA', 'CORVO'],
            'GAVIÃO': ['FALCÃO', 'ÁGUIA', 'URUBU'],
            'FALCÃO': ['GAVIÃO', 'ÁGUIA', 'CORVO'],
            'PAPAGAIO': ['ARARA', 'PERIQUITO', 'TUCANO'],
            'ARARA': ['PAPAGAIO', 'TUCANO', 'PERIQUITO'],
            'TUCANO': ['ARARA', 'PAPAGAIO', 'PICA-PAU'],
            'BEIJA-FLOR': ['ANDORINHA', 'CANÁRIO', 'PARDAL'],
            'POMBO': ['PARDAL', 'ANDORINHA', 'GAIVOTA'],
            'PARDAL': ['ANDORINHA', 'POMBO', 'SABIÁ'],
            'ANDORINHA': ['PARDAL', 'POMBO', 'BEIJA-FLOR'],
            'FLAMINGO': ['GARÇA', 'CISNE', 'CEGONHA'],
            'CISNE': ['GARÇA', 'PATO', 'FLAMINGO'],
            'GARÇA': ['CISNE', 'FLAMINGO', 'CEGONHA'],
            'AVESTRUZ': ['EMA', 'FLAMINGO', 'PAVÃO'],
            'PAVÃO': ['FLAMINGO', 'AVESTRUZ', 'ARARA'],
            'PINGUIM': ['PATO', 'FOCA', 'AVESTRUZ'],
            'CORVO': ['URUBU', 'GAVIÃO', 'POMBO'],
            'PICA-PAU': ['TUCANO', 'SABIÁ', 'PARDAL'],
            'SABIÁ': ['CANÁRIO', 'BEM-TE-VI', 'PARDAL'],
            'BEM-TE-VI': ['SABIÁ', 'CANÁRIO', 'PARDAL'],
            'URUBU': ['CORVO', 'GAVIÃO', 'ÁGUIA'],
            'GAIVOTA': ['POMBO', 'GARÇA', 'ANDORINHA'],
            'CANÁRIO': ['SABIÁ', 'PARDAL', 'PERIQUITO']
        },
        questions: animalQuestionsPT
    },
    {
        category: 'Comidas',
        words: ['PIZZA', 'HAMBÚRGUER', 'CACHORRO-QUENTE', 'SANDUÍCHE', 'MACARRÃO', 'LASANHA', 'NHOQUE', 'ARROZ', 'FEIJÃO', 'FEIJOADA', 'CHURRASCO', 'BIFE', 'FRANGO ASSADO', 'SALADA', 'SOPA', 'PASTEL', 'COXINHA', 'ESFIHA', 'EMPADA', 'QUIBE', 'PÃO', 'PÃO DE QUEIJO', 'TAPIOCA', 'PANQUECA', 'OMELETE', 'ESTROGONOFE', 'SUSHI', 'BATATA FRITA', 'PURÊ', 'FAROFA'],
        similar: {
            'PIZZA': ['ESFIHA', 'LASANHA', 'PASTEL'],
            'HAMBÚRGUER': ['SANDUÍCHE', 'CACHORRO-QUENTE', 'PIZZA'],
            'CACHORRO-QUENTE': ['HAMBÚRGUER', 'SANDUÍCHE', 'PASTEL'],
            'SANDUÍCHE': ['HAMBÚRGUER', 'CACHORRO-QUENTE', 'PÃO'],
            'MACARRÃO': ['NHOQUE', 'LASANHA', 'ARROZ'],
            'LASANHA': ['MACARRÃO', 'NHOQUE', 'PIZZA'],
            'NHOQUE': ['MACARRÃO', 'LASANHA', 'PURÊ'],
            'ARROZ': ['MACARRÃO', 'PURÊ', 'FEIJÃO'],
            'FEIJÃO': ['FEIJOADA', 'ARROZ', 'SOPA'],
            'FEIJOADA': ['FEIJÃO', 'ESTROGONOFE', 'CHURRASCO'],
            'CHURRASCO': ['BIFE', 'FRANGO ASSADO', 'HAMBÚRGUER'],
            'BIFE': ['CHURRASCO', 'FRANGO ASSADO', 'HAMBÚRGUER'],
            'FRANGO ASSADO': ['CHURRASCO', 'BIFE', 'ESTROGONOFE'],
            'SALADA': ['SOPA', 'OMELETE', 'SANDUÍCHE'],
            'SOPA': ['CALDO', 'SALADA', 'FEIJÃO'],
            'PASTEL': ['COXINHA', 'ESFIHA', 'EMPADA'],
            'COXINHA': ['PASTEL', 'QUIBE', 'EMPADA'],
            'ESFIHA': ['PASTEL', 'PIZZA', 'EMPADA'],
            'EMPADA': ['COXINHA', 'PASTEL', 'PÃO DE QUEIJO'],
            'QUIBE': ['COXINHA', 'ESFIHA', 'BIFE'],
            'PÃO': ['TORRADA', 'PÃO DE QUEIJO', 'BOLO'],
            'PÃO DE QUEIJO': ['PÃO', 'COXINHA', 'TAPIOCA'],
            'TAPIOCA': ['PANQUECA', 'CREPE', 'PÃO DE QUEIJO'],
            'PANQUECA': ['CREPE', 'TAPIOCA', 'OMELETE'],
            'OMELETE': ['PANQUECA', 'OVO FRITO', 'TAPIOCA'],
            'ESTROGONOFE': ['RISOTO', 'FEIJOADA', 'MACARRÃO'],
            'SUSHI': ['TEMAKI', 'YAKISSOBA', 'SALADA'],
            'BATATA FRITA': ['MANDIOCA FRITA', 'PURÊ', 'FAROFA'],
            'PURÊ': ['NHOQUE', 'BATATA FRITA', 'ARROZ'],
            'FAROFA': ['ARROZ', 'PURÊ', 'FEIJÃO']
        },
        questions: comidaQuestionsPT
    },
    {
        category: 'Doces e Sobremesas',
        words: ['BOLO', 'TORTA', 'PUDIM', 'SORVETE', 'PICOLÉ', 'BRIGADEIRO', 'BEIJINHO', 'CHOCOLATE', 'BISCOITO', 'BROWNIE', 'MOUSSE', 'PAVÊ', 'BOMBOM', 'GELATINA', 'CHURROS', 'SONHO', 'PAÇOCA', 'COCADA', 'PÉ DE MOLEQUE', 'QUINDIM', 'MILKSHAKE', 'DOCE DE LEITE', 'GOIABADA', 'ALGODÃO DOCE', 'PIRULITO', 'BALA', 'CHICLETE'],
        similar: {
            'BOLO': ['TORTA', 'BROWNIE', 'PUDIM'],
            'TORTA': ['BOLO', 'PAVÊ', 'PUDIM'],
            'PUDIM': ['QUINDIM', 'MOUSSE', 'GELATINA'],
            'SORVETE': ['PICOLÉ', 'MILKSHAKE', 'MOUSSE'],
            'PICOLÉ': ['SORVETE', 'GELADINHO', 'MILKSHAKE'],
            'BRIGADEIRO': ['BEIJINHO', 'BOMBOM', 'CHOCOLATE'],
            'BEIJINHO': ['BRIGADEIRO', 'COCADA', 'BOMBOM'],
            'CHOCOLATE': ['BOMBOM', 'BRIGADEIRO', 'BISCOITO'],
            'BISCOITO': ['BOLACHA', 'BROWNIE', 'BOLO'],
            'BROWNIE': ['BOLO', 'CHOCOLATE', 'BISCOITO'],
            'MOUSSE': ['PUDIM', 'GELATINA', 'SORVETE'],
            'PAVÊ': ['TORTA', 'MOUSSE', 'PUDIM'],
            'BOMBOM': ['CHOCOLATE', 'BRIGADEIRO', 'BALA'],
            'GELATINA': ['MOUSSE', 'PUDIM', 'GELADINHO'],
            'CHURROS': ['SONHO', 'DONUT', 'BOLO'],
            'SONHO': ['CHURROS', 'DONUT', 'BOLO'],
            'PAÇOCA': ['PÉ DE MOLEQUE', 'COCADA', 'DOCE DE LEITE'],
            'COCADA': ['BEIJINHO', 'PAÇOCA', 'PÉ DE MOLEQUE'],
            'PÉ DE MOLEQUE': ['PAÇOCA', 'COCADA', 'DOCE DE LEITE'],
            'QUINDIM': ['PUDIM', 'COCADA', 'BEIJINHO'],
            'MILKSHAKE': ['SORVETE', 'VITAMINA', 'PICOLÉ'],
            'DOCE DE LEITE': ['LEITE CONDENSADO', 'GOIABADA', 'PAÇOCA'],
            'GOIABADA': ['GELEIA', 'DOCE DE LEITE', 'GELATINA'],
            'ALGODÃO DOCE': ['PIRULITO', 'BALA', 'CHURROS'],
            'PIRULITO': ['BALA', 'CHICLETE', 'BOMBOM'],
            'BALA': ['PIRULITO', 'CHICLETE', 'BOMBOM'],
            'CHICLETE': ['BALA', 'PIRULITO', 'BOMBOM']
        },
        questions: [
            'Em que festa esse doce aparece?',
            'Onde você comeu isso pela última vez?',
            'O que acontece se deixar isso no sol?',
            'Quem você conhece que faz isso bem?',
            'Com que outro doce isso combina?',
            'Onde você compra isso?',
            'Quem na sua família mais gosta disso?',
            'Como se guarda isso?'
        ]
    },
    {
        category: 'Bebidas',
        words: ['ÁGUA', 'CAFÉ', 'CHÁ', 'LEITE', 'SUCO', 'REFRIGERANTE', 'GUARANÁ', 'CERVEJA', 'CHOPP', 'VINHO', 'CHAMPANHE', 'CHOCOLATE QUENTE', 'CAPPUCCINO', 'LIMONADA', 'VITAMINA', 'ÁGUA DE COCO', 'CHIMARRÃO', 'ENERGÉTICO', 'CAIPIRINHA', 'WHISKY', 'VODKA'],
        similar: {
            'ÁGUA': ['ÁGUA DE COCO', 'SUCO', 'CHÁ'],
            'CAFÉ': ['CAPPUCCINO', 'CHÁ', 'CHOCOLATE QUENTE'],
            'CHÁ': ['CAFÉ', 'CHIMARRÃO', 'ÁGUA'],
            'LEITE': ['VITAMINA', 'IOGURTE', 'CHOCOLATE QUENTE'],
            'SUCO': ['VITAMINA', 'LIMONADA', 'REFRIGERANTE'],
            'REFRIGERANTE': ['GUARANÁ', 'SUCO', 'ENERGÉTICO'],
            'GUARANÁ': ['REFRIGERANTE', 'SUCO', 'ENERGÉTICO'],
            'CERVEJA': ['CHOPP', 'VINHO', 'CAIPIRINHA'],
            'CHOPP': ['CERVEJA', 'CHAMPANHE', 'VINHO'],
            'VINHO': ['CHAMPANHE', 'CERVEJA', 'WHISKY'],
            'CHAMPANHE': ['VINHO', 'CHOPP', 'CAIPIRINHA'],
            'CHOCOLATE QUENTE': ['CAPPUCCINO', 'CAFÉ', 'LEITE'],
            'CAPPUCCINO': ['CAFÉ', 'CHOCOLATE QUENTE', 'MILKSHAKE'],
            'LIMONADA': ['SUCO', 'ÁGUA DE COCO', 'CAIPIRINHA'],
            'VITAMINA': ['MILKSHAKE', 'SUCO', 'LEITE'],
            'ÁGUA DE COCO': ['ÁGUA', 'LIMONADA', 'SUCO'],
            'CHIMARRÃO': ['CHÁ', 'TERERÉ', 'CAFÉ'],
            'ENERGÉTICO': ['REFRIGERANTE', 'ISOTÔNICO', 'CAFÉ'],
            'CAIPIRINHA': ['BATIDA', 'CERVEJA', 'VINHO'],
            'WHISKY': ['VODKA', 'VINHO', 'CERVEJA'],
            'VODKA': ['WHISKY', 'CACHAÇA', 'CAIPIRINHA']
        },
        questions: [
            'Em que momento do dia você bebe isso?',
            'Como você prefere beber isso?',
            'Com que comida isso combina?',
            'Quando foi a última vez que você bebeu isso?',
            'Pra quem você serviria isso?',
            'Onde você costuma beber isso?',
            'Em que situação isso combina?',
            'Onde você compraria isso?'
        ]
    },
    {
        category: 'Esportes com Bola',
        words: ['FUTEBOL', 'FUTSAL', 'BASQUETE', 'VÔLEI', 'HANDEBOL', 'TÊNIS', 'PING PONG', 'GOLFE', 'BOLICHE', 'SINUCA', 'BEISEBOL', 'FUTEBOL AMERICANO', 'FUTEVÔLEI', 'FRESCOBOL'],
        similar: {
            'FUTEBOL': ['FUTSAL', 'FUTEVÔLEI', 'HANDEBOL'],
            'FUTSAL': ['FUTEBOL', 'HANDEBOL', 'FUTEVÔLEI'],
            'BASQUETE': ['HANDEBOL', 'VÔLEI', 'FUTEBOL'],
            'VÔLEI': ['FUTEVÔLEI', 'HANDEBOL', 'BASQUETE'],
            'HANDEBOL': ['BASQUETE', 'FUTSAL', 'VÔLEI'],
            'TÊNIS': ['PING PONG', 'FRESCOBOL', 'VÔLEI'],
            'PING PONG': ['TÊNIS', 'FRESCOBOL', 'SINUCA'],
            'GOLFE': ['SINUCA', 'BOLICHE', 'BEISEBOL'],
            'BOLICHE': ['SINUCA', 'GOLFE', 'BASQUETE'],
            'SINUCA': ['BOLICHE', 'GOLFE', 'PING PONG'],
            'BEISEBOL': ['FUTEBOL AMERICANO', 'GOLFE', 'TÊNIS'],
            'FUTEBOL AMERICANO': ['RUGBY', 'BEISEBOL', 'FUTEBOL'],
            'FUTEVÔLEI': ['VÔLEI', 'FUTEBOL', 'FRESCOBOL'],
            'FRESCOBOL': ['PING PONG', 'TÊNIS', 'FUTEVÔLEI']
        },
        questions: [
            'Onde se pratica esse esporte?',
            'Quantas pessoas jogam ao mesmo tempo?',
            'O que você precisa pra jogar, além da bola?',
            'Que parte do corpo mais se usa?',
            'Onde você jogou isso pela última vez?',
            'Que atleta famoso você associa a esse esporte?',
            'Que roupa se usa pra jogar isso?',
            'Que parte do corpo cansa mais?'
        ]
    },
    {
        category: 'Esportes Individuais',
        words: ['NATAÇÃO', 'CORRIDA', 'MARATONA', 'CICLISMO', 'GINÁSTICA', 'SKATE', 'PATINAÇÃO', 'SURFE', 'BOXE', 'JUDÔ', 'KARATÊ', 'JIU-JITSU', 'MUSCULAÇÃO', 'YOGA', 'PILATES', 'CROSSFIT', 'MERGULHO', 'ESCALADA', 'PESCA'],
        similar: {
            'NATAÇÃO': ['MERGULHO', 'SURFE', 'CORRIDA'],
            'CORRIDA': ['MARATONA', 'CICLISMO', 'NATAÇÃO'],
            'MARATONA': ['CORRIDA', 'CICLISMO', 'NATAÇÃO'],
            'CICLISMO': ['CORRIDA', 'SKATE', 'PATINAÇÃO'],
            'GINÁSTICA': ['YOGA', 'PILATES', 'PATINAÇÃO'],
            'SKATE': ['PATINAÇÃO', 'SURFE', 'CICLISMO'],
            'PATINAÇÃO': ['SKATE', 'GINÁSTICA', 'CICLISMO'],
            'SURFE': ['SKATE', 'NATAÇÃO', 'MERGULHO'],
            'BOXE': ['KARATÊ', 'JIU-JITSU', 'MUSCULAÇÃO'],
            'JUDÔ': ['JIU-JITSU', 'KARATÊ', 'BOXE'],
            'KARATÊ': ['JUDÔ', 'BOXE', 'JIU-JITSU'],
            'JIU-JITSU': ['JUDÔ', 'KARATÊ', 'BOXE'],
            'MUSCULAÇÃO': ['CROSSFIT', 'GINÁSTICA', 'BOXE'],
            'YOGA': ['PILATES', 'ALONGAMENTO', 'GINÁSTICA'],
            'PILATES': ['YOGA', 'GINÁSTICA', 'ALONGAMENTO'],
            'CROSSFIT': ['MUSCULAÇÃO', 'GINÁSTICA', 'CORRIDA'],
            'MERGULHO': ['NATAÇÃO', 'PESCA', 'SURFE'],
            'ESCALADA': ['TRILHA', 'GINÁSTICA', 'CICLISMO'],
            'PESCA': ['MERGULHO', 'TRILHA', 'NATAÇÃO']
        },
        questions: [
            'Onde se pratica isso?',
            'Que roupa ou equipamento precisa?',
            'O que mais cansa nesse esporte?',
            'Em que horário você praticaria isso?',
            'Como você fica depois de praticar isso?',
            'Como alguém começa a praticar isso?',
            'O que pode dar errado praticando isso?',
            'Que tipo de pessoa você imagina praticando?'
        ]
    },
    {
        category: 'Instrumentos Musicais',
        words: ['VIOLÃO', 'GUITARRA', 'BAIXO', 'PIANO', 'TECLADO', 'BATERIA', 'VIOLINO', 'FLAUTA', 'SAXOFONE', 'TROMPETE', 'SANFONA', 'GAITA', 'CAVAQUINHO', 'UKULELE', 'PANDEIRO', 'TAMBOR', 'TRIÂNGULO', 'HARPA', 'BERIMBAU'],
        similar: {
            'VIOLÃO': ['CAVAQUINHO', 'GUITARRA', 'UKULELE'],
            'GUITARRA': ['VIOLÃO', 'BAIXO', 'CAVAQUINHO'],
            'BAIXO': ['GUITARRA', 'VIOLÃO', 'TECLADO'],
            'PIANO': ['TECLADO', 'HARPA', 'VIOLÃO'],
            'TECLADO': ['PIANO', 'SANFONA', 'GUITARRA'],
            'BATERIA': ['TAMBOR', 'PANDEIRO', 'TRIÂNGULO'],
            'VIOLINO': ['VIOLONCELO', 'VIOLÃO', 'HARPA'],
            'FLAUTA': ['GAITA', 'SAXOFONE', 'TROMPETE'],
            'SAXOFONE': ['TROMPETE', 'CLARINETE', 'FLAUTA'],
            'TROMPETE': ['SAXOFONE', 'TROMBONE', 'FLAUTA'],
            'SANFONA': ['GAITA', 'TECLADO', 'PIANO'],
            'GAITA': ['FLAUTA', 'SANFONA', 'SAXOFONE'],
            'CAVAQUINHO': ['UKULELE', 'VIOLÃO', 'GUITARRA'],
            'UKULELE': ['CAVAQUINHO', 'VIOLÃO', 'GUITARRA'],
            'PANDEIRO': ['TAMBOR', 'CHOCALHO', 'BATERIA'],
            'TAMBOR': ['PANDEIRO', 'BATERIA', 'BERIMBAU'],
            'TRIÂNGULO': ['CHOCALHO', 'PANDEIRO', 'TAMBOR'],
            'HARPA': ['VIOLINO', 'PIANO', 'VIOLÃO'],
            'BERIMBAU': ['PANDEIRO', 'TAMBOR', 'CHOCALHO']
        },
        questions: [
            'Em que estilo de música isso aparece?',
            'Como se toca isso?',
            'Como você carregaria isso pra um show?',
            'Quanto tempo leva pra aprender a tocar?',
            'Em que tipo de evento isso aparece?',
            'Que famoso você imagina tocando isso?',
            'Que outro instrumento combina com ele?',
            'Compare o tamanho dele com outro objeto'
        ]
    },
    {
        category: 'Profissões',
        words: ['MÉDICO', 'ENFERMEIRO', 'DENTISTA', 'VETERINÁRIO', 'PROFESSOR', 'ADVOGADO', 'JUIZ', 'ENGENHEIRO', 'ARQUITETO', 'POLICIAL', 'BOMBEIRO', 'SEGURANÇA', 'PORTEIRO', 'PILOTO', 'MOTORISTA', 'MOTOBOY', 'COZINHEIRO', 'PADEIRO', 'GARÇOM', 'PEDREIRO', 'ELETRICISTA', 'ENCANADOR', 'MECÂNICO', 'PINTOR', 'CABELEIREIRO', 'FOTÓGRAFO', 'JORNALISTA', 'ATOR', 'CANTOR', 'JOGADOR DE FUTEBOL', 'VENDEDOR', 'PSICÓLOGO', 'PROGRAMADOR', 'FAXINEIRO', 'JARDINEIRO', 'CARTEIRO'],
        similar: {
            'MÉDICO': ['ENFERMEIRO', 'DENTISTA', 'VETERINÁRIO'],
            'ENFERMEIRO': ['MÉDICO', 'DENTISTA', 'PSICÓLOGO'],
            'DENTISTA': ['MÉDICO', 'ENFERMEIRO', 'VETERINÁRIO'],
            'VETERINÁRIO': ['MÉDICO', 'DENTISTA', 'ENFERMEIRO'],
            'PROFESSOR': ['PSICÓLOGO', 'JORNALISTA', 'ADVOGADO'],
            'ADVOGADO': ['JUIZ', 'JORNALISTA', 'PROFESSOR'],
            'JUIZ': ['ADVOGADO', 'POLICIAL', 'PROFESSOR'],
            'ENGENHEIRO': ['ARQUITETO', 'PEDREIRO', 'PROGRAMADOR'],
            'ARQUITETO': ['ENGENHEIRO', 'PEDREIRO', 'PINTOR'],
            'POLICIAL': ['SEGURANÇA', 'BOMBEIRO', 'JUIZ'],
            'BOMBEIRO': ['POLICIAL', 'SEGURANÇA', 'ENFERMEIRO'],
            'SEGURANÇA': ['POLICIAL', 'PORTEIRO', 'BOMBEIRO'],
            'PORTEIRO': ['SEGURANÇA', 'FAXINEIRO', 'VENDEDOR'],
            'PILOTO': ['MOTORISTA', 'MOTOBOY', 'MECÂNICO'],
            'MOTORISTA': ['MOTOBOY', 'PILOTO', 'CARTEIRO'],
            'MOTOBOY': ['MOTORISTA', 'CARTEIRO', 'PILOTO'],
            'COZINHEIRO': ['PADEIRO', 'CONFEITEIRO', 'GARÇOM'],
            'PADEIRO': ['COZINHEIRO', 'CONFEITEIRO', 'GARÇOM'],
            'GARÇOM': ['COZINHEIRO', 'VENDEDOR', 'PADEIRO'],
            'PEDREIRO': ['PINTOR', 'ELETRICISTA', 'ENGENHEIRO'],
            'ELETRICISTA': ['ENCANADOR', 'PEDREIRO', 'MECÂNICO'],
            'ENCANADOR': ['ELETRICISTA', 'PEDREIRO', 'MECÂNICO'],
            'MECÂNICO': ['ELETRICISTA', 'ENCANADOR', 'MOTORISTA'],
            'PINTOR': ['PEDREIRO', 'ENCANADOR', 'ELETRICISTA'],
            'CABELEIREIRO': ['BARBEIRO', 'MANICURE', 'MAQUIADOR'],
            'FOTÓGRAFO': ['JORNALISTA', 'YOUTUBER', 'ATOR'],
            'JORNALISTA': ['FOTÓGRAFO', 'PROFESSOR', 'ADVOGADO'],
            'ATOR': ['CANTOR', 'YOUTUBER', 'JOGADOR DE FUTEBOL'],
            'CANTOR': ['ATOR', 'DANÇARINO', 'YOUTUBER'],
            'JOGADOR DE FUTEBOL': ['ATLETA', 'ATOR', 'CANTOR'],
            'VENDEDOR': ['GARÇOM', 'PADEIRO', 'PORTEIRO'],
            'PSICÓLOGO': ['MÉDICO', 'PROFESSOR', 'ENFERMEIRO'],
            'PROGRAMADOR': ['ENGENHEIRO', 'YOUTUBER', 'FOTÓGRAFO'],
            'FAXINEIRO': ['PORTEIRO', 'JARDINEIRO', 'PEDREIRO'],
            'JARDINEIRO': ['FAXINEIRO', 'PEDREIRO', 'PINTOR'],
            'CARTEIRO': ['MOTOBOY', 'PORTEIRO', 'MOTORISTA']
        },
        questions: [
            'Onde essa pessoa trabalha?',
            'Que roupa ela usa no trabalho?',
            'Que ferramenta ou objeto ela mais usa?',
            'Quando foi a última vez que você precisou dessa pessoa?',
            'Como é a rotina de trabalho dela?',
            'O que precisa estudar pra ser isso?',
            'Qual a parte mais difícil desse trabalho?',
            'Que tipo de criança sonha em ser isso?'
        ]
    },
    {
        category: 'Meios de Transporte',
        words: ['CARRO', 'MOTO', 'BICICLETA', 'ÔNIBUS', 'CAMINHÃO', 'CAMINHONETE', 'VAN', 'TREM', 'METRÔ', 'AVIÃO', 'HELICÓPTERO', 'BARCO', 'NAVIO', 'LANCHA', 'JET SKI', 'PATINETE', 'SKATE', 'TÁXI', 'AMBULÂNCIA', 'CANOA', 'SUBMARINO', 'FOGUETE', 'TRATOR'],
        similar: {
            'CARRO': ['TÁXI', 'CAMINHONETE', 'MOTO'],
            'MOTO': ['BICICLETA', 'PATINETE', 'CARRO'],
            'BICICLETA': ['PATINETE', 'MOTO', 'SKATE'],
            'ÔNIBUS': ['VAN', 'METRÔ', 'TREM'],
            'CAMINHÃO': ['CAMINHONETE', 'TRATOR', 'VAN'],
            'CAMINHONETE': ['CAMINHÃO', 'CARRO', 'VAN'],
            'VAN': ['ÔNIBUS', 'CAMINHONETE', 'CARRO'],
            'TREM': ['METRÔ', 'ÔNIBUS', 'NAVIO'],
            'METRÔ': ['TREM', 'ÔNIBUS', 'VAN'],
            'AVIÃO': ['HELICÓPTERO', 'FOGUETE', 'NAVIO'],
            'HELICÓPTERO': ['AVIÃO', 'DRONE', 'FOGUETE'],
            'BARCO': ['LANCHA', 'CANOA', 'NAVIO'],
            'NAVIO': ['BARCO', 'LANCHA', 'SUBMARINO'],
            'LANCHA': ['BARCO', 'JET SKI', 'NAVIO'],
            'JET SKI': ['LANCHA', 'MOTO', 'BARCO'],
            'PATINETE': ['BICICLETA', 'SKATE', 'MOTO'],
            'SKATE': ['PATINETE', 'BICICLETA', 'PATINS'],
            'TÁXI': ['CARRO', 'VAN', 'ÔNIBUS'],
            'AMBULÂNCIA': ['VAN', 'TÁXI', 'CAMINHONETE'],
            'CANOA': ['CAIAQUE', 'BARCO', 'LANCHA'],
            'SUBMARINO': ['NAVIO', 'BARCO', 'AVIÃO'],
            'FOGUETE': ['AVIÃO', 'HELICÓPTERO', 'SUBMARINO'],
            'TRATOR': ['CAMINHÃO', 'CAMINHONETE', 'VAN']
        },
        questions: [
            'Quando você usaria isso?',
            'Quantas pessoas cabem dentro?',
            'Compare a velocidade dele com outro transporte',
            'Pra onde você iria com ele?',
            'Quando foi a última vez que você andou nisso?',
            'Que barulho ele faz?',
            'O que precisa pra poder conduzir isso?',
            'Onde ele fica guardado?'
        ]
    },
    {
        category: 'Móveis',
        words: ['SOFÁ', 'POLTRONA', 'CAMA', 'BELICHE', 'BERÇO', 'MESA', 'CADEIRA', 'BANQUETA', 'ARMÁRIO', 'GUARDA-ROUPA', 'ESTANTE', 'PRATELEIRA', 'CÔMODA', 'CRIADO-MUDO', 'ESCRIVANINHA', 'RACK', 'SAPATEIRA', 'PUFE', 'REDE'],
        similar: {
            'SOFÁ': ['POLTRONA', 'PUFE', 'CAMA'],
            'POLTRONA': ['SOFÁ', 'CADEIRA', 'PUFE'],
            'CAMA': ['BELICHE', 'SOFÁ', 'REDE'],
            'BELICHE': ['CAMA', 'BERÇO', 'SOFÁ'],
            'BERÇO': ['CAMA', 'BELICHE', 'REDE'],
            'MESA': ['ESCRIVANINHA', 'RACK', 'ESTANTE'],
            'CADEIRA': ['BANQUETA', 'POLTRONA', 'SOFÁ'],
            'BANQUETA': ['CADEIRA', 'PUFE', 'POLTRONA'],
            'ARMÁRIO': ['GUARDA-ROUPA', 'ESTANTE', 'CÔMODA'],
            'GUARDA-ROUPA': ['ARMÁRIO', 'CÔMODA', 'SAPATEIRA'],
            'ESTANTE': ['PRATELEIRA', 'RACK', 'ARMÁRIO'],
            'PRATELEIRA': ['ESTANTE', 'RACK', 'ARMÁRIO'],
            'CÔMODA': ['CRIADO-MUDO', 'GUARDA-ROUPA', 'ARMÁRIO'],
            'CRIADO-MUDO': ['CÔMODA', 'MESA', 'PRATELEIRA'],
            'ESCRIVANINHA': ['MESA', 'CRIADO-MUDO', 'RACK'],
            'RACK': ['ESTANTE', 'PRATELEIRA', 'MESA'],
            'SAPATEIRA': ['GUARDA-ROUPA', 'CÔMODA', 'ESTANTE'],
            'PUFE': ['BANQUETA', 'POLTRONA', 'SOFÁ'],
            'REDE': ['CAMA', 'SOFÁ', 'PUFE']
        },
        questions: [
            'Em que cômodo isso costuma ficar?',
            'O que você guarda ou coloca nele?',
            'O que as pessoas fazem nele?',
            'Quantas pessoas precisam pra carregar ele?',
            'De que material costuma ser?',
            'Quem você conhece que tem um bonito?',
            'Em que posição do cômodo ele fica?',
            'O que uma criança faria com ele?'
        ]
    },
    {
        category: 'Eletrodomésticos',
        words: ['GELADEIRA', 'FREEZER', 'FOGÃO', 'FORNO', 'MICRO-ONDAS', 'AIRFRYER', 'LIQUIDIFICADOR', 'BATEDEIRA', 'CAFETEIRA', 'TORRADEIRA', 'SANDUICHEIRA', 'MÁQUINA DE LAVAR', 'SECADORA', 'FERRO DE PASSAR', 'ASPIRADOR', 'VENTILADOR', 'AR-CONDICIONADO', 'LAVA-LOUÇAS', 'PANELA ELÉTRICA'],
        similar: {
            'GELADEIRA': ['FREEZER', 'FRIGOBAR', 'MÁQUINA DE LAVAR'],
            'FREEZER': ['GELADEIRA', 'FRIGOBAR', 'AR-CONDICIONADO'],
            'FOGÃO': ['FORNO', 'MICRO-ONDAS', 'AIRFRYER'],
            'FORNO': ['FOGÃO', 'AIRFRYER', 'MICRO-ONDAS'],
            'MICRO-ONDAS': ['FORNO', 'AIRFRYER', 'TORRADEIRA'],
            'AIRFRYER': ['FORNO', 'MICRO-ONDAS', 'SANDUICHEIRA'],
            'LIQUIDIFICADOR': ['BATEDEIRA', 'MIXER', 'CAFETEIRA'],
            'BATEDEIRA': ['LIQUIDIFICADOR', 'MIXER', 'SANDUICHEIRA'],
            'CAFETEIRA': ['CHALEIRA', 'LIQUIDIFICADOR', 'TORRADEIRA'],
            'TORRADEIRA': ['SANDUICHEIRA', 'MICRO-ONDAS', 'AIRFRYER'],
            'SANDUICHEIRA': ['TORRADEIRA', 'AIRFRYER', 'PANELA ELÉTRICA'],
            'MÁQUINA DE LAVAR': ['SECADORA', 'LAVA-LOUÇAS', 'GELADEIRA'],
            'SECADORA': ['MÁQUINA DE LAVAR', 'LAVA-LOUÇAS', 'FERRO DE PASSAR'],
            'FERRO DE PASSAR': ['SECADORA', 'MÁQUINA DE LAVAR', 'ASPIRADOR'],
            'ASPIRADOR': ['VENTILADOR', 'FERRO DE PASSAR', 'MÁQUINA DE LAVAR'],
            'VENTILADOR': ['AR-CONDICIONADO', 'ASPIRADOR', 'GELADEIRA'],
            'AR-CONDICIONADO': ['VENTILADOR', 'GELADEIRA', 'FREEZER'],
            'LAVA-LOUÇAS': ['MÁQUINA DE LAVAR', 'SECADORA', 'GELADEIRA'],
            'PANELA ELÉTRICA': ['AIRFRYER', 'MICRO-ONDAS', 'SANDUICHEIRA']
        },
        questions: [
            'Em que cômodo isso fica?',
            'Com que frequência você usa?',
            'O que você coloca dentro dele?',
            'Que barulho ele faz?',
            'Compare o tamanho dele com outro eletrodoméstico',
            'O que acontece se ele quebrar?',
            'Quanto custa um novo, mais ou menos?',
            'Quem você conhece que usa muito isso?'
        ]
    },
    {
        category: 'Eletrônicos',
        words: ['TELEVISÃO', 'CELULAR', 'COMPUTADOR', 'NOTEBOOK', 'TABLET', 'VIDEOGAME', 'CONTROLE', 'FONE DE OUVIDO', 'CAIXA DE SOM', 'CÂMERA', 'MOUSE', 'TECLADO', 'IMPRESSORA', 'MONITOR', 'PENDRIVE', 'DRONE', 'PROJETOR', 'SMARTWATCH', 'ROTEADOR'],
        similar: {
            'TELEVISÃO': ['MONITOR', 'PROJETOR', 'TABLET'],
            'CELULAR': ['TABLET', 'SMARTWATCH', 'NOTEBOOK'],
            'COMPUTADOR': ['NOTEBOOK', 'TABLET', 'VIDEOGAME'],
            'NOTEBOOK': ['COMPUTADOR', 'TABLET', 'CELULAR'],
            'TABLET': ['CELULAR', 'NOTEBOOK', 'TELEVISÃO'],
            'VIDEOGAME': ['COMPUTADOR', 'CONTROLE', 'TELEVISÃO'],
            'CONTROLE': ['MOUSE', 'TECLADO', 'VIDEOGAME'],
            'FONE DE OUVIDO': ['CAIXA DE SOM', 'MICROFONE', 'CELULAR'],
            'CAIXA DE SOM': ['FONE DE OUVIDO', 'MICROFONE', 'TELEVISÃO'],
            'CÂMERA': ['CELULAR', 'DRONE', 'PROJETOR'],
            'MOUSE': ['TECLADO', 'CONTROLE', 'PENDRIVE'],
            'TECLADO': ['MOUSE', 'CONTROLE', 'NOTEBOOK'],
            'IMPRESSORA': ['SCANNER', 'COMPUTADOR', 'ROTEADOR'],
            'MONITOR': ['TELEVISÃO', 'NOTEBOOK', 'PROJETOR'],
            'PENDRIVE': ['CARTÃO DE MEMÓRIA', 'MOUSE', 'CARREGADOR'],
            'DRONE': ['HELICÓPTERO', 'CÂMERA', 'CONTROLE'],
            'PROJETOR': ['TELEVISÃO', 'MONITOR', 'CÂMERA'],
            'SMARTWATCH': ['RELÓGIO', 'CELULAR', 'TABLET'],
            'ROTEADOR': ['MODEM', 'IMPRESSORA', 'CAIXA DE SOM']
        },
        questions: [
            'Onde isso fica na sua casa?',
            'Você usa isso quantas vezes por dia?',
            'Com que outro aparelho ele funciona junto?',
            'O que você faz quando ele trava ou para de funcionar?',
            'Compare o tamanho dele com outro objeto',
            'Quanto custa, mais ou menos?',
            'Quem mais usa isso na sua casa?',
            'O que você faria se ele quebrasse hoje?'
        ]
    },
    {
        category: 'Roupas',
        words: ['CAMISETA', 'CAMISA', 'BLUSA', 'REGATA', 'MOLETOM', 'CASACO', 'JAQUETA', 'BLAZER', 'CALÇA', 'BERMUDA', 'SHORT', 'SAIA', 'VESTIDO', 'MACACÃO', 'PIJAMA', 'ROUPÃO', 'CUECA', 'CALCINHA', 'SUTIÃ', 'MEIA', 'BIQUÍNI', 'MAIÔ', 'SUNGA', 'GRAVATA', 'TERNO'],
        similar: {
            'CAMISETA': ['REGATA', 'BLUSA', 'CAMISA'],
            'CAMISA': ['CAMISETA', 'BLUSA', 'BLAZER'],
            'BLUSA': ['CAMISETA', 'MOLETOM', 'REGATA'],
            'REGATA': ['CAMISETA', 'BLUSA', 'SHORT'],
            'MOLETOM': ['CASACO', 'BLUSA', 'JAQUETA'],
            'CASACO': ['JAQUETA', 'MOLETOM', 'BLAZER'],
            'JAQUETA': ['CASACO', 'MOLETOM', 'BLAZER'],
            'BLAZER': ['TERNO', 'JAQUETA', 'CAMISA'],
            'CALÇA': ['BERMUDA', 'SHORT', 'SAIA'],
            'BERMUDA': ['SHORT', 'CALÇA', 'SUNGA'],
            'SHORT': ['BERMUDA', 'SAIA', 'CALÇA'],
            'SAIA': ['VESTIDO', 'SHORT', 'CALÇA'],
            'VESTIDO': ['SAIA', 'MACACÃO', 'BLUSA'],
            'MACACÃO': ['VESTIDO', 'CALÇA', 'PIJAMA'],
            'PIJAMA': ['CAMISOLA', 'ROUPÃO', 'MOLETOM'],
            'ROUPÃO': ['PIJAMA', 'CASACO', 'VESTIDO'],
            'CUECA': ['SUNGA', 'CALCINHA', 'SHORT'],
            'CALCINHA': ['CUECA', 'BIQUÍNI', 'SUTIÃ'],
            'SUTIÃ': ['BIQUÍNI', 'CALCINHA', 'REGATA'],
            'MEIA': ['LUVA', 'CUECA', 'CACHECOL'],
            'BIQUÍNI': ['MAIÔ', 'SUNGA', 'CALCINHA'],
            'MAIÔ': ['BIQUÍNI', 'SUNGA', 'VESTIDO'],
            'SUNGA': ['BERMUDA', 'BIQUÍNI', 'CUECA'],
            'GRAVATA': ['TERNO', 'BLAZER', 'CACHECOL'],
            'TERNO': ['BLAZER', 'GRAVATA', 'CAMISA']
        },
        questions: [
            'Em que ocasião você usa isso?',
            'Em que parte do corpo se usa?',
            'Em que época do ano você usa mais?',
            'Com que look você usaria isso?',
            'Com que outra peça isso combina?',
            'Você tem quantos desses?',
            'Como você cuida dessa peça?',
            'Qual a cor do seu?'
        ]
    },
    {
        category: 'Calçados',
        words: ['TÊNIS', 'SAPATO', 'SANDÁLIA', 'CHINELO', 'BOTA', 'SAPATILHA', 'CHUTEIRA', 'SALTO ALTO', 'PANTUFA', 'CROCS'],
        similar: {
            'TÊNIS': ['SAPATÊNIS', 'CHUTEIRA', 'SAPATO'],
            'SAPATO': ['MOCASSIM', 'TÊNIS', 'BOTA'],
            'SANDÁLIA': ['CHINELO', 'RASTEIRINHA', 'SAPATILHA'],
            'CHINELO': ['SANDÁLIA', 'CROCS', 'PANTUFA'],
            'BOTA': ['COTURNO', 'GALOCHA', 'SAPATO'],
            'SAPATILHA': ['RASTEIRINHA', 'SANDÁLIA', 'SAPATO'],
            'CHUTEIRA': ['TÊNIS', 'SAPATÊNIS', 'BOTA'],
            'SALTO ALTO': ['SANDÁLIA', 'SAPATILHA', 'BOTA'],
            'PANTUFA': ['CHINELO', 'MEIA', 'CROCS'],
            'CROCS': ['CHINELO', 'SANDÁLIA', 'PANTUFA']
        },
        questions: [
            'Em que ocasião você usa isso?',
            'Como seu pé fica depois de um dia inteiro com ele?',
            'Com que roupa isso combina?',
            'Em que lugar você NÃO usaria isso?',
            'O que dá pra fazer calçando isso?',
            'Que barulho ele faz quando você anda?',
            'Quanto tempo você leva pra calçar ele?',
            'Quantos pares desses você tem?'
        ]
    },
    {
        category: 'Acessórios',
        words: ['RELÓGIO', 'ÓCULOS', 'ÓCULOS DE SOL', 'BOLSA', 'CARTEIRA', 'MOCHILA', 'CINTO', 'CHAPÉU', 'BONÉ', 'TOUCA', 'CACHECOL', 'LUVA', 'PULSEIRA', 'COLAR', 'BRINCO', 'ANEL', 'ALIANÇA', 'TIARA', 'POCHETE', 'GUARDA-CHUVA'],
        similar: {
            'RELÓGIO': ['PULSEIRA', 'SMARTWATCH', 'ANEL'],
            'ÓCULOS': ['ÓCULOS DE SOL', 'BONÉ', 'CHAPÉU'],
            'ÓCULOS DE SOL': ['ÓCULOS', 'BONÉ', 'CHAPÉU'],
            'BOLSA': ['MOCHILA', 'POCHETE', 'CARTEIRA'],
            'CARTEIRA': ['BOLSA', 'POCHETE', 'MOCHILA'],
            'MOCHILA': ['BOLSA', 'MALA', 'POCHETE'],
            'CINTO': ['SUSPENSÓRIO', 'PULSEIRA', 'GRAVATA'],
            'CHAPÉU': ['BONÉ', 'TOUCA', 'TIARA'],
            'BONÉ': ['CHAPÉU', 'VISEIRA', 'TOUCA'],
            'TOUCA': ['GORRO', 'BONÉ', 'CHAPÉU'],
            'CACHECOL': ['LENÇO', 'GORRO', 'LUVA'],
            'LUVA': ['MEIA', 'TOUCA', 'CACHECOL'],
            'PULSEIRA': ['COLAR', 'RELÓGIO', 'ANEL'],
            'COLAR': ['CORRENTE', 'PULSEIRA', 'BRINCO'],
            'BRINCO': ['PIERCING', 'COLAR', 'ANEL'],
            'ANEL': ['ALIANÇA', 'PULSEIRA', 'BRINCO'],
            'ALIANÇA': ['ANEL', 'PULSEIRA', 'COLAR'],
            'TIARA': ['PRESILHA', 'TOUCA', 'BONÉ'],
            'POCHETE': ['BOLSA', 'MOCHILA', 'CARTEIRA'],
            'GUARDA-CHUVA': ['SOMBRINHA', 'CAPA DE CHUVA', 'CHAPÉU'],
            'SMARTWATCH': ['RELÓGIO', 'PULSEIRA', 'CELULAR']
        },
        questions: [
            'Em que parte do corpo isso se usa?',
            'Com que frequência você usa?',
            'Pra que serve, além de enfeitar?',
            'Quanto custa um, mais ou menos?',
            'Onde você guarda o seu?',
            'Em que ocasião você usaria?',
            'Dá de presente pra quem?',
            'Quem você conhece que usa um?'
        ]
    },
    {
        category: 'Partes da Casa',
        words: ['QUARTO', 'SALA', 'COZINHA', 'BANHEIRO', 'LAVANDERIA', 'VARANDA', 'GARAGEM', 'JARDIM', 'QUINTAL', 'ESCRITÓRIO', 'CORREDOR', 'SÓTÃO', 'PORÃO', 'DESPENSA', 'CLOSET', 'SUÍTE', 'CHURRASQUEIRA', 'PISCINA', 'TELHADO', 'ESCADA'],
        similar: {
            'QUARTO': ['SUÍTE', 'SALA', 'CLOSET'],
            'SALA': ['QUARTO', 'VARANDA', 'ESCRITÓRIO'],
            'COZINHA': ['COPA', 'DESPENSA', 'LAVANDERIA'],
            'BANHEIRO': ['LAVABO', 'SUÍTE', 'LAVANDERIA'],
            'LAVANDERIA': ['COZINHA', 'BANHEIRO', 'DESPENSA'],
            'VARANDA': ['SACADA', 'QUINTAL', 'JARDIM'],
            'GARAGEM': ['QUINTAL', 'PORÃO', 'CORREDOR'],
            'JARDIM': ['QUINTAL', 'VARANDA', 'PISCINA'],
            'QUINTAL': ['JARDIM', 'VARANDA', 'GARAGEM'],
            'ESCRITÓRIO': ['QUARTO', 'SALA', 'CLOSET'],
            'CORREDOR': ['HALL', 'ESCADA', 'SALA'],
            'SÓTÃO': ['PORÃO', 'DESPENSA', 'CLOSET'],
            'PORÃO': ['SÓTÃO', 'GARAGEM', 'DESPENSA'],
            'DESPENSA': ['CLOSET', 'COZINHA', 'SÓTÃO'],
            'CLOSET': ['DESPENSA', 'QUARTO', 'SÓTÃO'],
            'SUÍTE': ['QUARTO', 'BANHEIRO', 'CLOSET'],
            'CHURRASQUEIRA': ['VARANDA', 'QUINTAL', 'COZINHA'],
            'PISCINA': ['QUINTAL', 'JARDIM', 'BANHEIRO'],
            'TELHADO': ['SÓTÃO', 'VARANDA', 'GARAGEM'],
            'ESCADA': ['CORREDOR', 'HALL', 'VARANDA']
        },
        questions: [
            'O que você faz nesse lugar?',
            'Quanto tempo por dia você passa nele?',
            'Que móvel não pode faltar nele?',
            'O que dá pra ver quando você está nele?',
            'Quem da casa mais usa esse lugar?',
            'Que cheiro tem esse lugar?',
            'O que se guarda nesse lugar?',
            'Descreva como é esse lugar na sua casa'
        ]
    },
    {
        category: 'Lugares da Cidade',
        words: ['ESCOLA', 'HOSPITAL', 'SHOPPING', 'SUPERMERCADO', 'PADARIA', 'FARMÁCIA', 'BANCO', 'IGREJA', 'PRAÇA', 'PARQUE', 'ZOOLÓGICO', 'CINEMA', 'TEATRO', 'MUSEU', 'BIBLIOTECA', 'RESTAURANTE', 'LANCHONETE', 'PIZZARIA', 'SORVETERIA', 'ACADEMIA', 'DELEGACIA', 'CORREIOS', 'POSTO DE GASOLINA', 'AEROPORTO', 'RODOVIÁRIA', 'FEIRA', 'AÇOUGUE', 'LIVRARIA', 'PET SHOP', 'SALÃO DE BELEZA', 'HOTEL'],
        similar: {
            'ESCOLA': ['FACULDADE', 'CRECHE', 'BIBLIOTECA'],
            'HOSPITAL': ['CLÍNICA', 'FARMÁCIA', 'DELEGACIA'],
            'SHOPPING': ['SUPERMERCADO', 'FEIRA', 'CINEMA'],
            'SUPERMERCADO': ['FEIRA', 'AÇOUGUE', 'SHOPPING'],
            'PADARIA': ['CONFEITARIA', 'LANCHONETE', 'SUPERMERCADO'],
            'FARMÁCIA': ['CLÍNICA', 'HOSPITAL', 'SUPERMERCADO'],
            'BANCO': ['LOTÉRICA', 'CORREIOS', 'SUPERMERCADO'],
            'IGREJA': ['MUSEU', 'TEATRO', 'BIBLIOTECA'],
            'PRAÇA': ['PARQUE', 'CLUBE', 'FEIRA'],
            'PARQUE': ['PRAÇA', 'ZOOLÓGICO', 'CLUBE'],
            'ZOOLÓGICO': ['PARQUE', 'CIRCO', 'PET SHOP'],
            'CINEMA': ['TEATRO', 'SHOPPING', 'MUSEU'],
            'TEATRO': ['CINEMA', 'MUSEU', 'IGREJA'],
            'MUSEU': ['TEATRO', 'BIBLIOTECA', 'CINEMA'],
            'BIBLIOTECA': ['LIVRARIA', 'MUSEU', 'ESCOLA'],
            'RESTAURANTE': ['LANCHONETE', 'PIZZARIA', 'PADARIA'],
            'LANCHONETE': ['RESTAURANTE', 'PADARIA', 'PIZZARIA'],
            'PIZZARIA': ['RESTAURANTE', 'LANCHONETE', 'PADARIA'],
            'SORVETERIA': ['LANCHONETE', 'PADARIA', 'PIZZARIA'],
            'ACADEMIA': ['CLUBE', 'PARQUE', 'ESCOLA'],
            'DELEGACIA': ['FÓRUM', 'PREFEITURA', 'BANCO'],
            'CORREIOS': ['BANCO', 'LOTÉRICA', 'PREFEITURA'],
            'POSTO DE GASOLINA': ['OFICINA', 'LAVA-RÁPIDO', 'SUPERMERCADO'],
            'AEROPORTO': ['RODOVIÁRIA', 'PORTO', 'SHOPPING'],
            'RODOVIÁRIA': ['AEROPORTO', 'PORTO', 'POSTO DE GASOLINA'],
            'FEIRA': ['SACOLÃO', 'SUPERMERCADO', 'SHOPPING'],
            'AÇOUGUE': ['PEIXARIA', 'SUPERMERCADO', 'FEIRA'],
            'LIVRARIA': ['PAPELARIA', 'BIBLIOTECA', 'MUSEU'],
            'PET SHOP': ['VETERINÁRIO', 'SALÃO DE BELEZA', 'FARMÁCIA'],
            'SALÃO DE BELEZA': ['BARBEARIA', 'ACADEMIA', 'FARMÁCIA'],
            'HOTEL': ['POUSADA', 'RESORT', 'RODOVIÁRIA']
        },
        questions: lugarQuestionsPT
    },
    {
        category: 'Natureza',
        words: ['PRAIA', 'MAR', 'ILHA', 'RIO', 'LAGO', 'CACHOEIRA', 'MONTANHA', 'MORRO', 'FLORESTA', 'CAMPO', 'DESERTO', 'CAVERNA', 'VULCÃO'],
        similar: {
            'PRAIA': ['ILHA', 'MAR', 'LAGO'],
            'MAR': ['PRAIA', 'LAGO', 'RIO'],
            'ILHA': ['PRAIA', 'MAR', 'LAGO'],
            'RIO': ['LAGO', 'CACHOEIRA', 'MAR'],
            'LAGO': ['RIO', 'REPRESA', 'MAR'],
            'CACHOEIRA': ['RIO', 'LAGO', 'MONTANHA'],
            'MONTANHA': ['MORRO', 'VULCÃO', 'CAVERNA'],
            'MORRO': ['MONTANHA', 'CAMPO', 'VULCÃO'],
            'FLORESTA': ['MATA', 'CAMPO', 'MONTANHA'],
            'CAMPO': ['FAZENDA', 'MORRO', 'FLORESTA'],
            'DESERTO': ['PRAIA', 'CAMPO', 'MONTANHA'],
            'CAVERNA': ['GRUTA', 'MONTANHA', 'VULCÃO'],
            'VULCÃO': ['MONTANHA', 'CAVERNA', 'DESERTO']
        },
        questions: [
            'O que você faria nesse lugar?',
            'Que roupa combina com esse lugar?',
            'O que dá pra ouvir nesse lugar?',
            'Como é o clima lá?',
            'Você levaria quem pra conhecer?',
            'Quanto tempo você passaria lá?',
            'Que animal vive nesse lugar?',
            'Quanto tempo de viagem até um lugar desses?'
        ]
    },
    {
        category: 'Clima e Tempo',
        words: ['SOL', 'CHUVA', 'GAROA', 'VENTO', 'NEVE', 'NUVEM', 'TEMPESTADE', 'TROVÃO', 'RAIO', 'ARCO-ÍRIS', 'NEBLINA', 'GEADA', 'GRANIZO', 'TORNADO', 'FURACÃO', 'CALOR', 'FRIO', 'ENCHENTE'],
        similar: {
            'SOL': ['CALOR', 'NUVEM', 'ARCO-ÍRIS'],
            'CHUVA': ['GAROA', 'TEMPESTADE', 'ENCHENTE'],
            'GAROA': ['CHUVA', 'NEBLINA', 'TEMPESTADE'],
            'VENTO': ['TEMPESTADE', 'TORNADO', 'FRIO'],
            'NEVE': ['GEADA', 'GRANIZO', 'FRIO'],
            'NUVEM': ['NEBLINA', 'CHUVA', 'SOL'],
            'TEMPESTADE': ['CHUVA', 'TROVÃO', 'FURACÃO'],
            'TROVÃO': ['RAIO', 'TEMPESTADE', 'CHUVA'],
            'RAIO': ['TROVÃO', 'TEMPESTADE', 'SOL'],
            'ARCO-ÍRIS': ['SOL', 'CHUVA', 'NUVEM'],
            'NEBLINA': ['GAROA', 'NUVEM', 'GEADA'],
            'GEADA': ['NEVE', 'NEBLINA', 'FRIO'],
            'GRANIZO': ['NEVE', 'CHUVA', 'GEADA'],
            'TORNADO': ['FURACÃO', 'TEMPESTADE', 'VENTO'],
            'FURACÃO': ['TORNADO', 'TEMPESTADE', 'ENCHENTE'],
            'CALOR': ['SOL', 'VERÃO', 'VENTO'],
            'FRIO': ['GEADA', 'NEVE', 'VENTO'],
            'ENCHENTE': ['CHUVA', 'TEMPESTADE', 'FURACÃO']
        },
        questions: [
            'O que você faz quando o tempo está assim?',
            'Que roupa combina com isso?',
            'Como você se sente quando está assim?',
            'Em que lugar do mundo isso acontece muito?',
            'O que pode acontecer de ruim quando está assim?',
            'Que som isso faz?',
            'Em que época do ano isso acontece mais?',
            'Pra onde você iria num dia assim?'
        ]
    },
    {
        category: 'Material Escolar',
        words: ['LÁPIS', 'CANETA', 'LAPISEIRA', 'BORRACHA', 'CADERNO', 'LIVRO', 'MOCHILA', 'ESTOJO', 'RÉGUA', 'TESOURA', 'COLA', 'APONTADOR', 'PASTA', 'MARCA-TEXTO', 'CALCULADORA', 'AGENDA', 'PAPEL', 'GRAMPEADOR', 'CANETINHA', 'LÁPIS DE COR', 'GIZ DE CERA'],
        similar: {
            'LÁPIS': ['LAPISEIRA', 'CANETA', 'LÁPIS DE COR'],
            'CANETA': ['LÁPIS', 'CANETINHA', 'MARCA-TEXTO'],
            'LAPISEIRA': ['LÁPIS', 'CANETA', 'BORRACHA'],
            'BORRACHA': ['CORRETIVO', 'APONTADOR', 'LÁPIS'],
            'CADERNO': ['AGENDA', 'LIVRO', 'PAPEL'],
            'LIVRO': ['CADERNO', 'REVISTA', 'AGENDA'],
            'MOCHILA': ['PASTA', 'ESTOJO', 'BOLSA'],
            'ESTOJO': ['PASTA', 'MOCHILA', 'CADERNO'],
            'RÉGUA': ['ESQUADRO', 'COMPASSO', 'TESOURA'],
            'TESOURA': ['ESTILETE', 'COLA', 'RÉGUA'],
            'COLA': ['FITA ADESIVA', 'TESOURA', 'CORRETIVO'],
            'APONTADOR': ['BORRACHA', 'LAPISEIRA', 'ESTOJO'],
            'PASTA': ['ESTOJO', 'MOCHILA', 'CADERNO'],
            'MARCA-TEXTO': ['CANETINHA', 'CANETA', 'GIZ DE CERA'],
            'CALCULADORA': ['RÉGUA', 'CELULAR', 'AGENDA'],
            'AGENDA': ['CADERNO', 'LIVRO', 'CALENDÁRIO'],
            'PAPEL': ['CADERNO', 'CARTOLINA', 'LIVRO'],
            'GRAMPEADOR': ['FURADOR', 'CLIPS', 'TESOURA'],
            'CANETINHA': ['MARCA-TEXTO', 'LÁPIS DE COR', 'CANETA'],
            'LÁPIS DE COR': ['GIZ DE CERA', 'CANETINHA', 'LÁPIS'],
            'GIZ DE CERA': ['LÁPIS DE COR', 'CANETINHA', 'MARCA-TEXTO']
        },
        questions: [
            'Pra que você usa isso na escola?',
            'Onde você guarda isso?',
            'O que você faz quando alguém pega e não devolve?',
            'Quanto tempo dura o seu?',
            'De que cor costuma ser o seu?',
            'Quantos desses você já perdeu na vida?',
            'Quem usa isso além de estudante?',
            'Quanto custa um, mais ou menos?'
        ]
    },
    {
        category: 'Brinquedos',
        words: ['BONECA', 'CARRINHO', 'BOLA', 'PIPA', 'QUEBRA-CABEÇA', 'LEGO', 'IOIÔ', 'PIÃO', 'PATINS', 'BAMBOLÊ', 'CORDA', 'BALANÇO', 'ESCORREGADOR', 'GANGORRA', 'PELÚCIA', 'DOMINÓ', 'XADREZ', 'BARALHO', 'MASSINHA', 'SLIME', 'CAMA ELÁSTICA', 'BOLHA DE SABÃO'],
        similar: {
            'BONECA': ['PELÚCIA', 'FANTOCHE', 'CARRINHO'],
            'CARRINHO': ['PIÃO', 'LEGO', 'BONECA'],
            'BOLA': ['PETECA', 'BAMBOLÊ', 'PIPA'],
            'PIPA': ['BALÃO', 'PETECA', 'BOLA'],
            'QUEBRA-CABEÇA': ['LEGO', 'DOMINÓ', 'XADREZ'],
            'LEGO': ['QUEBRA-CABEÇA', 'MASSINHA', 'CARRINHO'],
            'IOIÔ': ['PIÃO', 'PETECA', 'BAMBOLÊ'],
            'PIÃO': ['IOIÔ', 'PETECA', 'BOLA'],
            'PATINS': ['SKATE', 'PATINETE', 'BICICLETA'],
            'BAMBOLÊ': ['CORDA', 'BOLA', 'IOIÔ'],
            'CORDA': ['BAMBOLÊ', 'ELÁSTICO', 'BOLA'],
            'BALANÇO': ['GANGORRA', 'ESCORREGADOR', 'CAMA ELÁSTICA'],
            'ESCORREGADOR': ['BALANÇO', 'GANGORRA', 'CAMA ELÁSTICA'],
            'GANGORRA': ['BALANÇO', 'ESCORREGADOR', 'BAMBOLÊ'],
            'PELÚCIA': ['BONECA', 'FANTOCHE', 'QUEBRA-CABEÇA'],
            'DOMINÓ': ['BARALHO', 'XADREZ', 'QUEBRA-CABEÇA'],
            'XADREZ': ['DAMAS', 'DOMINÓ', 'BARALHO'],
            'BARALHO': ['DOMINÓ', 'DAMAS', 'XADREZ'],
            'MASSINHA': ['SLIME', 'ARGILA', 'LEGO'],
            'SLIME': ['MASSINHA', 'ARGILA', 'BOLHA DE SABÃO'],
            'CAMA ELÁSTICA': ['ESCORREGADOR', 'BALANÇO', 'PISCINA DE BOLINHAS'],
            'BOLHA DE SABÃO': ['BALÃO', 'PIPA', 'SLIME']
        },
        questions: [
            'Onde você brincava com isso?',
            'Com quantas pessoas dá pra brincar?',
            'Como era o seu na infância?',
            'Que idade tem quem mais brinca com isso?',
            'O que precisa pra brincar com isso?',
            'Como você fica depois de brincar com isso?',
            'Em que lugar é melhor brincar com isso?',
            'Compare o tamanho dele com outra coisa'
        ]
    },
    {
        category: 'Ferramentas',
        words: ['MARTELO', 'CHAVE DE FENDA', 'CHAVE INGLESA', 'ALICATE', 'SERROTE', 'FURADEIRA', 'PREGO', 'PARAFUSO', 'TRENA', 'ESCADA', 'LIXA', 'PINCEL', 'ENXADA', 'PÁ', 'MANGUEIRA', 'MACHADO', 'VASSOURA', 'BALDE', 'REGADOR'],
        similar: {
            'MARTELO': ['MARRETA', 'MACHADO', 'ALICATE'],
            'CHAVE DE FENDA': ['CHAVE INGLESA', 'PARAFUSADEIRA', 'ALICATE'],
            'CHAVE INGLESA': ['CHAVE DE FENDA', 'ALICATE', 'MARTELO'],
            'ALICATE': ['CHAVE INGLESA', 'MARTELO', 'CHAVE DE FENDA'],
            'SERROTE': ['MACHADO', 'FACÃO', 'MARTELO'],
            'FURADEIRA': ['PARAFUSADEIRA', 'CHAVE DE FENDA', 'MARTELO'],
            'PREGO': ['PARAFUSO', 'MARTELO', 'ALICATE'],
            'PARAFUSO': ['PREGO', 'CHAVE DE FENDA', 'FURADEIRA'],
            'TRENA': ['FITA MÉTRICA', 'RÉGUA', 'ESCADA'],
            'ESCADA': ['ANDAIME', 'BALDE', 'PÁ'],
            'LIXA': ['ESPÁTULA', 'PINCEL', 'SERROTE'],
            'PINCEL': ['ROLO DE TINTA', 'ESPÁTULA', 'LIXA'],
            'ENXADA': ['PÁ', 'RASTELO', 'MACHADO'],
            'PÁ': ['ENXADA', 'RASTELO', 'BALDE'],
            'MANGUEIRA': ['REGADOR', 'BALDE', 'PÁ'],
            'MACHADO': ['SERROTE', 'FACÃO', 'MARTELO'],
            'VASSOURA': ['RODO', 'PÁ', 'ESFREGÃO'],
            'BALDE': ['BACIA', 'REGADOR', 'PÁ'],
            'REGADOR': ['MANGUEIRA', 'BALDE', 'PÁ']
        },
        questions: [
            'Pra que serve isso?',
            'Quem costuma usar isso?',
            'Onde isso fica guardado na sua casa?',
            'O que pode dar errado usando isso?',
            'Que barulho isso faz?',
            'Em que situação você usou isso pela última vez?',
            'Compare o peso disso com outro objeto',
            'Quem te ensinou a usar isso?'
        ]
    },
    {
        category: 'Utensílios de Cozinha',
        words: ['PANELA', 'FRIGIDEIRA', 'PANELA DE PRESSÃO', 'CHALEIRA', 'ASSADEIRA', 'COLHER DE PAU', 'ESPÁTULA', 'CONCHA', 'PENEIRA', 'RALADOR', 'ABRIDOR', 'TÁBUA', 'FACA', 'GARFO', 'COLHER', 'PRATO', 'TIGELA', 'COPO', 'CANECA', 'XÍCARA', 'JARRA', 'GARRAFA', 'BANDEJA', 'ESCORREDOR'],
        similar: {
            'PANELA': ['PANELA DE PRESSÃO', 'FRIGIDEIRA', 'CHALEIRA'],
            'FRIGIDEIRA': ['PANELA', 'ASSADEIRA', 'CHALEIRA'],
            'PANELA DE PRESSÃO': ['PANELA', 'CHALEIRA', 'FRIGIDEIRA'],
            'CHALEIRA': ['BULE', 'JARRA', 'PANELA'],
            'ASSADEIRA': ['TRAVESSA', 'FRIGIDEIRA', 'BANDEJA'],
            'COLHER DE PAU': ['ESPÁTULA', 'CONCHA', 'COLHER'],
            'ESPÁTULA': ['COLHER DE PAU', 'CONCHA', 'FACA'],
            'CONCHA': ['ESCUMADEIRA', 'COLHER DE PAU', 'COLHER'],
            'PENEIRA': ['ESCORREDOR', 'COADOR', 'RALADOR'],
            'RALADOR': ['DESCASCADOR', 'PENEIRA', 'FACA'],
            'ABRIDOR': ['SACA-ROLHAS', 'DESCASCADOR', 'FACA'],
            'TÁBUA': ['BANDEJA', 'PRATO', 'FACA'],
            'FACA': ['GARFO', 'COLHER', 'TESOURA'],
            'GARFO': ['COLHER', 'FACA', 'COLHER DE PAU'],
            'COLHER': ['GARFO', 'COLHER DE PAU', 'CONCHA'],
            'PRATO': ['TIGELA', 'TRAVESSA', 'BANDEJA'],
            'TIGELA': ['POTE', 'PRATO', 'JARRA'],
            'COPO': ['CANECA', 'TAÇA', 'XÍCARA'],
            'CANECA': ['XÍCARA', 'COPO', 'TAÇA'],
            'XÍCARA': ['CANECA', 'COPO', 'TAÇA'],
            'JARRA': ['GARRAFA', 'BULE', 'COPO'],
            'GARRAFA': ['JARRA', 'COPO', 'CANECA'],
            'BANDEJA': ['TÁBUA', 'PRATO', 'TRAVESSA'],
            'ESCORREDOR': ['PENEIRA', 'COADOR', 'RALADOR']
        },
        questions: [
            'Pra que serve isso na cozinha?',
            'O que acontece se isso for ao fogo?',
            'De que material costuma ser?',
            'Com que frequência você usa?',
            'Como você lava isso?',
            'Em que momento da refeição isso aparece?',
            'Onde isso fica guardado?',
            'O que acontece se isso cair no chão?'
        ]
    },
    {
        category: 'Cores',
        words: ['VERMELHO', 'AZUL', 'AMARELO', 'VERDE', 'LARANJA', 'ROXO', 'ROSA', 'MARROM', 'PRETO', 'BRANCO', 'CINZA', 'BEGE', 'DOURADO', 'PRATEADO', 'LILÁS', 'VINHO', 'TURQUESA'],
        similar: {
            'VERMELHO': ['VINHO', 'LARANJA', 'ROSA'],
            'AZUL': ['TURQUESA', 'ROXO', 'VERDE'],
            'AMARELO': ['DOURADO', 'LARANJA', 'BEGE'],
            'VERDE': ['TURQUESA', 'AZUL', 'AMARELO'],
            'LARANJA': ['AMARELO', 'SALMÃO', 'VERMELHO'],
            'ROXO': ['LILÁS', 'VINHO', 'AZUL'],
            'ROSA': ['LILÁS', 'SALMÃO', 'VERMELHO'],
            'MARROM': ['BEGE', 'VINHO', 'PRETO'],
            'PRETO': ['CINZA', 'MARROM', 'VINHO'],
            'BRANCO': ['BEGE', 'CINZA', 'PRATEADO'],
            'CINZA': ['PRATEADO', 'PRETO', 'BRANCO'],
            'BEGE': ['BRANCO', 'MARROM', 'AMARELO'],
            'DOURADO': ['AMARELO', 'PRATEADO', 'LARANJA'],
            'PRATEADO': ['CINZA', 'DOURADO', 'BRANCO'],
            'LILÁS': ['ROXO', 'ROSA', 'AZUL'],
            'VINHO': ['VERMELHO', 'ROXO', 'MARROM'],
            'TURQUESA': ['AZUL', 'VERDE', 'LILÁS']
        },
        questions: [
            'O que na sua casa tem essa cor?',
            'Que comida tem essa cor?',
            'Que peça de roupa você tem nessa cor?',
            'Que sentimento essa cor passa?',
            'Que outra cor combina com ela?',
            'Que animal tem essa cor?',
            'Em que ocasião você usaria essa cor?',
            'Que time ou bandeira usa essa cor?'
        ]
    },
    {
        category: 'Partes do Corpo',
        words: ['CABEÇA', 'OLHO', 'NARIZ', 'BOCA', 'ORELHA', 'PESCOÇO', 'OMBRO', 'BRAÇO', 'MÃO', 'DEDO', 'UNHA', 'BARRIGA', 'COSTAS', 'PERNA', 'JOELHO', 'PÉ', 'CABELO', 'SOBRANCELHA', 'DENTE', 'LÍNGUA', 'COTOVELO', 'TORNOZELO', 'COXA', 'CALCANHAR', 'QUEIXO', 'TESTA'],
        similar: {
            'CABEÇA': ['TESTA', 'PESCOÇO', 'OMBRO'],
            'OLHO': ['SOBRANCELHA', 'NARIZ', 'ORELHA'],
            'NARIZ': ['BOCA', 'OLHO', 'ORELHA'],
            'BOCA': ['LÍNGUA', 'DENTE', 'NARIZ'],
            'ORELHA': ['NARIZ', 'OLHO', 'QUEIXO'],
            'PESCOÇO': ['OMBRO', 'QUEIXO', 'COSTAS'],
            'OMBRO': ['PESCOÇO', 'BRAÇO', 'COSTAS'],
            'BRAÇO': ['PERNA', 'OMBRO', 'COTOVELO'],
            'MÃO': ['PÉ', 'DEDO', 'BRAÇO'],
            'DEDO': ['UNHA', 'MÃO', 'PÉ'],
            'UNHA': ['DEDO', 'MÃO', 'CABELO'],
            'BARRIGA': ['PEITO', 'COSTAS', 'COXA'],
            'COSTAS': ['OMBRO', 'BARRIGA', 'PESCOÇO'],
            'PERNA': ['COXA', 'BRAÇO', 'JOELHO'],
            'JOELHO': ['COTOVELO', 'TORNOZELO', 'COXA'],
            'PÉ': ['MÃO', 'TORNOZELO', 'CALCANHAR'],
            'CABELO': ['SOBRANCELHA', 'BARBA', 'UNHA'],
            'SOBRANCELHA': ['CÍLIOS', 'CABELO', 'OLHO'],
            'DENTE': ['LÍNGUA', 'BOCA', 'UNHA'],
            'LÍNGUA': ['DENTE', 'BOCA', 'LÁBIO'],
            'COTOVELO': ['JOELHO', 'OMBRO', 'PULSO'],
            'TORNOZELO': ['PULSO', 'JOELHO', 'CALCANHAR'],
            'COXA': ['PERNA', 'JOELHO', 'BRAÇO'],
            'CALCANHAR': ['TORNOZELO', 'PÉ', 'JOELHO'],
            'QUEIXO': ['TESTA', 'BOCA', 'NARIZ'],
            'TESTA': ['QUEIXO', 'SOBRANCELHA', 'CABEÇA']
        },
        questions: [
            'Pra que serve essa parte do corpo?',
            'Quantas dessa parte a gente tem?',
            'Perto de que outra parte ela fica?',
            'O que acontece quando ela machuca?',
            'O que você usa pra cuidar dela?',
            'O que você consegue fazer com ela?',
            'Que acessório ou roupa se usa nela?',
            'Como ela se mexe?'
        ]
    },
    {
        category: 'Festas e Celebrações',
        words: ['ANIVERSÁRIO', 'CASAMENTO', 'NATAL', 'ANO NOVO', 'PÁSCOA', 'CARNAVAL', 'FESTA JUNINA', 'HALLOWEEN', 'FORMATURA', 'BATIZADO', 'CHÁ DE BEBÊ', 'CHURRASCO', 'DIA DAS MÃES', 'DIA DOS PAIS', 'DIA DOS NAMORADOS', 'DIA DAS CRIANÇAS', 'NOIVADO', 'FESTA DE 15 ANOS'],
        similar: {
            'ANIVERSÁRIO': ['FESTA DE 15 ANOS', 'DIA DAS CRIANÇAS', 'FORMATURA'],
            'CASAMENTO': ['NOIVADO', 'FORMATURA', 'BATIZADO'],
            'NATAL': ['ANO NOVO', 'PÁSCOA', 'ANIVERSÁRIO'],
            'ANO NOVO': ['NATAL', 'CARNAVAL', 'ANIVERSÁRIO'],
            'PÁSCOA': ['NATAL', 'DIA DAS CRIANÇAS', 'ANIVERSÁRIO'],
            'CARNAVAL': ['ANO NOVO', 'FESTA JUNINA', 'HALLOWEEN'],
            'FESTA JUNINA': ['CARNAVAL', 'HALLOWEEN', 'ANIVERSÁRIO'],
            'HALLOWEEN': ['CARNAVAL', 'FESTA JUNINA', 'PÁSCOA'],
            'FORMATURA': ['CASAMENTO', 'FESTA DE 15 ANOS', 'ANIVERSÁRIO'],
            'BATIZADO': ['CHÁ DE BEBÊ', 'CASAMENTO', 'ANIVERSÁRIO'],
            'CHÁ DE BEBÊ': ['BATIZADO', 'ANIVERSÁRIO', 'CASAMENTO'],
            'CHURRASCO': ['ANIVERSÁRIO', 'ANO NOVO', 'FESTA JUNINA'],
            'DIA DAS MÃES': ['DIA DOS PAIS', 'DIA DAS CRIANÇAS', 'DIA DOS NAMORADOS'],
            'DIA DOS PAIS': ['DIA DAS MÃES', 'DIA DAS CRIANÇAS', 'DIA DOS NAMORADOS'],
            'DIA DOS NAMORADOS': ['DIA DAS MÃES', 'CASAMENTO', 'NOIVADO'],
            'DIA DAS CRIANÇAS': ['DIA DAS MÃES', 'PÁSCOA', 'NATAL'],
            'NOIVADO': ['CASAMENTO', 'DIA DOS NAMORADOS', 'FORMATURA'],
            'FESTA DE 15 ANOS': ['ANIVERSÁRIO', 'FORMATURA', 'CASAMENTO']
        },
        questions: [
            'O que se come nessa data?',
            'Que música toca nessa festa?',
            'O que você veste pra ir?',
            'Que presente combina com essa data?',
            'Em que mês costuma acontecer?',
            'Quem você chamaria pra essa festa?',
            'Como é a decoração?',
            'Qual foi a última vez que você foi numa dessas?'
        ]
    },
    {
        category: 'Jogos e Games',
        words: ['MINECRAFT', 'FORTNITE', 'FREE FIRE', 'ROBLOX', 'AMONG US', 'FIFA', 'GTA', 'MARIO', 'SONIC', 'POKEMON', 'CANDY CRUSH', 'CLASH ROYALE', 'TETRIS', 'PAC-MAN', 'VALORANT', 'COUNTER-STRIKE', 'THE SIMS', 'GOD OF WAR', 'MORTAL KOMBAT'],
        similar: {
            'MINECRAFT': ['ROBLOX', 'FORTNITE', 'THE SIMS'],
            'FORTNITE': ['FREE FIRE', 'VALORANT', 'MINECRAFT'],
            'FREE FIRE': ['FORTNITE', 'PUBG', 'VALORANT'],
            'ROBLOX': ['MINECRAFT', 'FORTNITE', 'AMONG US'],
            'AMONG US': ['ROBLOX', 'FALL GUYS', 'FREE FIRE'],
            'FIFA': ['PES', 'ROCKET LEAGUE', 'FREE FIRE'],
            'GTA': ['RED DEAD', 'FREE FIRE', 'MINECRAFT'],
            'MARIO': ['SONIC', 'DONKEY KONG', 'PAC-MAN'],
            'SONIC': ['MARIO', 'PAC-MAN', 'DONKEY KONG'],
            'POKEMON': ['DIGIMON', 'MARIO', 'MINECRAFT'],
            'CANDY CRUSH': ['TETRIS', 'CLASH ROYALE', 'PAC-MAN'],
            'CLASH ROYALE': ['CLASH OF CLANS', 'CANDY CRUSH', 'FREE FIRE'],
            'TETRIS': ['CANDY CRUSH', 'PAC-MAN', 'MARIO'],
            'PAC-MAN': ['TETRIS', 'SONIC', 'MARIO'],
            'VALORANT': ['COUNTER-STRIKE', 'FREE FIRE', 'FORTNITE'],
            'COUNTER-STRIKE': ['VALORANT', 'FREE FIRE', 'CALL OF DUTY'],
            'THE SIMS': ['MINECRAFT', 'ROBLOX', 'GTA'],
            'GOD OF WAR': ['MORTAL KOMBAT', 'GTA', 'MINECRAFT'],
            'MORTAL KOMBAT': ['STREET FIGHTER', 'GOD OF WAR', 'FREE FIRE']
        },
        questions: [
            'Com quem você jogaria isso?',
            'Com quantas pessoas se joga?',
            'Como você fica jogando isso?',
            'Que idade tem quem mais joga isso?',
            'Desde quando você conhece esse jogo?',
            'Quanto tempo dura uma partida?',
            'O que precisa pra jogar isso?',
            'Que tipo de pessoa você imagina jogando?'
        ]
    },
    {
        category: 'Filmes e Séries',
        words: ['VINGADORES', 'HOMEM-ARANHA', 'BATMAN', 'SUPERMAN', 'HARRY POTTER', 'STAR WARS', 'SENHOR DOS ANÉIS', 'TITANIC', 'JURASSIC PARK', 'VELOZES E FURIOSOS', 'FROZEN', 'TOY STORY', 'SHREK', 'REI LEÃO', 'PROCURANDO NEMO', 'MINIONS', 'MOANA', 'DIVERTIDA MENTE', 'STRANGER THINGS', 'ROUND 6', 'LA CASA DE PAPEL', 'FRIENDS', 'GAME OF THRONES', 'BREAKING BAD', 'NARUTO', 'DRAGON BALL', 'ONE PIECE'],
        similar: {
            'VINGADORES': ['LIGA DA JUSTIÇA', 'HOMEM-ARANHA', 'X-MEN'],
            'HOMEM-ARANHA': ['BATMAN', 'SUPERMAN', 'VINGADORES'],
            'BATMAN': ['SUPERMAN', 'HOMEM-ARANHA', 'VINGADORES'],
            'SUPERMAN': ['BATMAN', 'HOMEM-ARANHA', 'VINGADORES'],
            'HARRY POTTER': ['SENHOR DOS ANÉIS', 'NARNIA', 'STAR WARS'],
            'STAR WARS': ['STAR TREK', 'SENHOR DOS ANÉIS', 'VINGADORES'],
            'SENHOR DOS ANÉIS': ['HARRY POTTER', 'GAME OF THRONES', 'STAR WARS'],
            'TITANIC': ['JURASSIC PARK', 'STAR WARS', 'VELOZES E FURIOSOS'],
            'JURASSIC PARK': ['KING KONG', 'GODZILLA', 'VELOZES E FURIOSOS'],
            'VELOZES E FURIOSOS': ['MISSÃO IMPOSSÍVEL', 'JURASSIC PARK', 'VINGADORES'],
            'FROZEN': ['MOANA', 'ENROLADOS', 'REI LEÃO'],
            'TOY STORY': ['SHREK', 'MINIONS', 'PROCURANDO NEMO'],
            'SHREK': ['MINIONS', 'TOY STORY', 'MADAGASCAR'],
            'REI LEÃO': ['MADAGASCAR', 'PROCURANDO NEMO', 'FROZEN'],
            'PROCURANDO NEMO': ['MOANA', 'REI LEÃO', 'TOY STORY'],
            'MINIONS': ['SHREK', 'TOY STORY', 'DIVERTIDA MENTE'],
            'MOANA': ['FROZEN', 'PROCURANDO NEMO', 'ENROLADOS'],
            'DIVERTIDA MENTE': ['TOY STORY', 'MINIONS', 'FROZEN'],
            'STRANGER THINGS': ['DARK', 'ROUND 6', 'HARRY POTTER'],
            'ROUND 6': ['LA CASA DE PAPEL', 'STRANGER THINGS', 'BREAKING BAD'],
            'LA CASA DE PAPEL': ['ROUND 6', 'BREAKING BAD', 'VELOZES E FURIOSOS'],
            'FRIENDS': ['HOW I MET YOUR MOTHER', 'THE BIG BANG THEORY', 'STRANGER THINGS'],
            'GAME OF THRONES': ['SENHOR DOS ANÉIS', 'VIKINGS', 'HARRY POTTER'],
            'BREAKING BAD': ['LA CASA DE PAPEL', 'ROUND 6', 'GAME OF THRONES'],
            'NARUTO': ['DRAGON BALL', 'ONE PIECE', 'POKEMON'],
            'DRAGON BALL': ['NARUTO', 'ONE PIECE', 'POKEMON'],
            'ONE PIECE': ['NARUTO', 'DRAGON BALL', 'POKEMON']
        },
        questions: [
            'Onde você assistiu isso?',
            'Que sentimento isso desperta?',
            'Pra que idade isso é indicado?',
            'Que nota de 0 a 10 você dá?',
            'De que época é?',
            'Pra quem você recomendaria?',
            'Que outro filme ou série parece com esse?',
            'Você assistiu com quem?'
        ]
    },
    {
        category: 'Personagens',
        words: ['MICKEY', 'MINNIE', 'PATO DONALD', 'PATETA', 'BOB ESPONJA', 'PATRICK', 'LULA MOLUSCO', 'HOMER SIMPSON', 'SCOOBY-DOO', 'TOM', 'JERRY', 'PICA-PAU', 'GARFIELD', 'PEPPA PIG', 'ELSA', 'WOODY', 'BUZZ LIGHTYEAR', 'PIKACHU', 'GOKU', 'CHAVES', 'MÔNICA', 'CEBOLINHA', 'CASCÃO'],
        similar: {
            'MICKEY': ['MINNIE', 'PATO DONALD', 'PATETA'],
            'MINNIE': ['MICKEY', 'MARGARIDA', 'PATETA'],
            'PATO DONALD': ['MARGARIDA', 'MICKEY', 'PATETA'],
            'PATETA': ['MICKEY', 'PATO DONALD', 'BOB ESPONJA'],
            'BOB ESPONJA': ['PATRICK', 'LULA MOLUSCO', 'MICKEY'],
            'PATRICK': ['BOB ESPONJA', 'LULA MOLUSCO', 'PATETA'],
            'LULA MOLUSCO': ['BOB ESPONJA', 'PATRICK', 'PATO DONALD'],
            'HOMER SIMPSON': ['BART SIMPSON', 'PETER GRIFFIN', 'PATETA'],
            'SCOOBY-DOO': ['PLUTO', 'GARFIELD', 'TOM'],
            'TOM': ['JERRY', 'GARFIELD', 'PICA-PAU'],
            'JERRY': ['TOM', 'PICA-PAU', 'MICKEY'],
            'PICA-PAU': ['TOM', 'JERRY', 'PATO DONALD'],
            'GARFIELD': ['TOM', 'SNOOPY', 'SCOOBY-DOO'],
            'PEPPA PIG': ['PATRULHA CANINA', 'BOB ESPONJA', 'MICKEY'],
            'ELSA': ['ANNA', 'RAPUNZEL', 'MOANA'],
            'WOODY': ['BUZZ LIGHTYEAR', 'SHREK', 'MICKEY'],
            'BUZZ LIGHTYEAR': ['WOODY', 'MICKEY', 'BOB ESPONJA'],
            'PIKACHU': ['SONIC', 'STITCH', 'SCOOBY-DOO'],
            'GOKU': ['VEGETA', 'NARUTO', 'SUPERMAN'],
            'CHAVES': ['CHAPOLIN', 'QUICO', 'HOMER SIMPSON'],
            'MÔNICA': ['CEBOLINHA', 'MAGALI', 'CASCÃO'],
            'CEBOLINHA': ['CASCÃO', 'MÔNICA', 'MAGALI'],
            'CASCÃO': ['CEBOLINHA', 'MÔNICA', 'MAGALI']
        },
        questions: [
            'Descreva um detalhe do visual dele',
            'Qual a principal característica dele?',
            'Qual a cena mais marcante dele?',
            'Como ele reagiria numa emergência?',
            'Quem você conhece que ama esse personagem?',
            'Como é a voz dele?',
            'De que cor ele é?',
            'Com quem ele anda junto?'
        ]
    }
];

// Track used words to avoid repetition
let usedWordsPT = [];

function getWordCategoriesPT() {
    return wordCategoriesPT;
}

function getRandomWordPT(categoryData) {
    const totalWords = wordCategoriesPT.reduce((sum, cat) => sum + cat.words.length, 0);
    const maxUsed = Math.floor(totalWords / 2);

    if (usedWordsPT.length >= maxUsed) {
        usedWordsPT = [];
    }

    const availableWords = categoryData.words.filter(w => !usedWordsPT.includes(w));
    const wordPool = availableWords.length > 0 ? availableWords : categoryData.words;
    const word = wordPool[Math.floor(Math.random() * wordPool.length)];

    if (!usedWordsPT.includes(word)) {
        usedWordsPT.push(word);
    }

    return word;
}
